#+BEGIN_COMMENT
.. title: On Trust, Companies and Characterial Notes
.. slug: on-characterial-notes
.. date: 2019-07-18 19:03:23 UTC+02:00
.. tags: perRep
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT


So I possibly just concluded the most stressful week at work that I
have ever experienced. At least so far.

I had to take a break from work. Take some rest in order to let the
brain breathe. Take a break in order to let the emotional charge
decompress. Take a break in order to understand what happened.

Now, it is a good time to write some notes about it. You learn from
the difficult times and you can take big learnings out of what
happened. 

{{{TEASER_END}}}

** On Trust

   This is an important element to me. It is the engine that makes the
   social living possible. The engine that rules the world.

   In order to see this, just think about you driving on a highway. Or
   crossing a road in Hanoi.

   The key point in both of the experiences is /trust/. Let's stay on
   the first example as I guess that most of the people do not have
   personal experience about crossing a road in Hanoi.

   The only way that cars can drive on a highway at 130 km/h is
   through trust. I trust the other drivers to stay on their lanes, to
   not make sudden and abrupt moves. Once that trust is given, I have
   no issues driving next to a car at high speed on a highway. I am
   confident that I can overtake the car - or be overtaken - without
   endangering anyone.

   The issue comes when this element completely fades away. When you
   do not know anymore who to trust.

   Imagine driving on a highway where you have zero trust on the other
   drivers. Where you in fact start to doubt that your goal - driving
   safely on the highway while respecting the rules - and the one of
   the other drivers are aligned.

   You can imagine then that at the first micro-movement on the
   highway, be it malicious or not, you may react with a sudden and
   abrupt wheel-steering. You can now well imagine that driving on a
   highway in such conditions is dangerous. It is a question of time
   before a huge incident happens.

   So this brings me to the following point, without beating about the
   bush: /how do you drive in big companies where the trust element is
   naturally flawed?/

** On Characterial Notes

   So this I have to take it as given by now. No place and need to
   hide, just accept it and control it.

   I have no mild character and I do not like to be used. Especially
   the latter. I have no patience for it. I think that many people
   have the belief when working with young people that they dispose
   of them.

   They assume a lack of experience and knowledge and couple it with
   the natural fear of the youth that does not know an environment in
   order to fulfill their goals.

   I see it differently, possibly due to my first important employer
   that instilled this mentality on me and never used or treated me
   superficially but rather as a future resource to invest in.

   This also goes very well along the lines of [[https://www.youtube.com/watch?v=to7nSEcEBJc][this]] parasha
   interpretation. The message is clear and guides you to treat well
   people you have influence over. It guides you /to have fear/,
   behave and be accountable when having the power over someone.

   It guides you not to abuse of people as they are image of Hashem
   and not to torture them by asking them to perform work that is
   /nullifying their soul/.

   Keep it well into your mind as this will make you a great people
   manager when it will be the time.

   The fundamental question in this dimension is the following:

   /How do you deal with people that have influence over you and do
   not glorify your soul and ambitions?/

   This is a question I still need to solve. You will always find such
   kind of people along your way and you will go for autodistruction
   in your career if you will not be able to solve this. 

** On Big Companies

   This brings me to the last point, the one of big companies, where
   the two issues above are exacerbated.

   On the one hand, in big companies lots of time managers are not
   accountable for misbehaving and abusing of their employees. Often
   they are required to do so by some general corporate policy and
   strategy. Or simply they must do so in order to get to their
   targets which might not involve many important qualitative factors.

   It is a big chain. Once accountability for the actions is lost,
   then all of the chain suffers from it.

   After all the companies are basically using the human psyche in
   order to fulfill their operations:

   #+begin_quote
For in most cases, the evil do not know they are evil. Those who carry
out atrocities don't know they are doing so; they are simply obeying
orders. Or waiting for a promotion.

Or doing what they have to do to get on, when all they really want is
to be home, safe and sound.

And they worry about their taxes, and about their kids' problems in
school.

But as they are thinking about home and wife and bills to be paid,
their hands unthinkingly hold the weapon; their eyes are on the fence
behind which other people are sobbing.
   #+end_quote

   Employees feel the situation and lack of purpose, they might even
   start to misbehave in order to seek out for revenge.

   On the other hand, competition exacerbates the situation... after
   all everyone is just waiting for a promotion.

   #+begin_quote
   Overall, because of competition among the people and conflicting
   goals set to the individuals in order to let problematic situation
   arise; the trust condition is difficult to achieve.

   Basically, you might end up on the crazy highway of section one.
   #+end_quote

   So the question here is: /how do you contrast the accountability
   and competitveness factors arising in big companies?/

** On a possible way out

   So the question is now how to deal with the natural tensions that
   emerge at work given the different factors described above.

   I am reading now a very interesting book: /Leaders - by Richard
   Nixon/.

   It is very interesting, because apart from giving you a historic
   refresher on some of the biggest events of the 20th century it
   gives a very colourful description of the personalities behind the
   great leaders of the 20th century. A glimpse from a person that
   participated in the shaping of the great events of his time and
   experienced everything first hand.

   The great leaders of the century, from /Churchill, to De Gaulle,
   from Adenauer to Kruscev/ had very different personalities. From
   introvert and reflexive characters to more impulsive and action
   based characters. Though, what they had in common is a strong
   personality. They never made compromises, believied firmly in some
   doctrine and followed it blindly. When they lost they retreated,
   studied and awaited their moment. 

   So this is a lesson learned for you. You can be the one out of a
   million or you can create your personality and doctrine. Do not
   oppress it; grow it.

   So turning back to the initial question: how to deal with the
   difficult situations as above; my answer is: /through ethics/.

   I am convinced in the power of ethics. I am convinced by the fact
   that people are moved by purpose and strong ethics creates
   purpose. Without it people will get bored at work, will not be
   motivated, they will be just moved on economic grounds and the
   results will be dire. 

   So in order to create a great team create a high sense of
   greatness, a sense of /grandeur/ a la De Gaulle. A sense of
   belonging and accomplishment through achievements.

   A great team that is ready to cooperate and trust each other in
   order to achieve something bigger. A team where its leaders are not
   motivated on economic grounds or on power grounds but rather on
   grounds of purpose. Then and just then you will have created or you
   will be participating in something big. Then and just then you will
   not leave the battlefield but rather stay on the pitch until the
   last drop of energy leaves up your body. Then and just then you
   will find the fulfillment you are searching for at work. Then and
   just then you will close up your eyes in the evening and smile
   waiting to rise up to new challenges the next morning.


