#+BEGIN_COMMENT
.. title: Macro Variables
.. slug: macro-variables
.. date: 2022-03-08 16:16:45 UTC+01:00
.. tags: macroeconomics, finance
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT

So here some notes about the macro side of the coin.

I started reading the [[https://www.zurich.com/en/economics-and-markets/publications][weekly publications]] of the macro-group of
Zurich.

I must say that it is interesting. I always loved macro.

I always recall the book of Blanchard. I think that this was the most
intersting theories I read throughout my academic life. Stat is
nice.. but way too much low level that higher world modeling dimension
is missing.

I mean think Black-Scholes. That is also fun if I think about it now
again. A simple mathematical formula - confusing tons of
practitioners - through that stat low level stuff moving trillions of
dollars which is then ultimately resulting from very questionable
first-order assumptions.

Sometimes I am fascinated about how this world sticks together and is
not simply falling apart. 

Anyways, back to Macroeconomics, at some point I thought that my life
was gonna be around it. /Kaynes vs. Hayek/ in an endless pointless
fight.

I think that there is an inherent beauty in observing that
macro-picture making guesses about how the dots are connected.

Speculating on the reaction of CB etc. lovely. At the end they all
follow the common principles. Until the "business" does not require a
big shift.

In any case here the list - which I guess will keep expanding in the
coming years.

It is important to understand all of these different components as if
you will stay for a long time in the industry and you will manage to
navigate data quickly some interesting patterns might start to emerge.

{{{TEASER_END}}}

** FIS-OIS Spread

   So today is 08/03/2022. Two weeks since Russia invaded Ukraine.

   So there is a big apprehension on what is gonna happen on financial
   markets. A big apprehension to understand how stressed they are.

   A leading indicator in this sense is the above spread. This is
   often displayed in these reports.

   So in order to understand it understand the following:

   - Overnight Rate:

     Back to the basics to your times in the financial space:

     #+begin_quote
The overnight rate is the interest rate at which a depository
institution (generally banks) lends or borrows funds with another
depository institution in the overnight market.

In many countries, the overnight rate is the interest rate the central
bank sets to *target monetary policy*.

In most circumstances, the overnight rate is the lowest available
interest rate, and as such, it is only available to the most
creditworthy institutions.
     #+end_quote

   - OIS - Overnight Indexed Swap:

     #+begin_quote
An Overnight Indexed Swap (OIS) is a fixed/floating interest rate swap
with the floating leg tied to a published index of a daily overnight
rate reference. The term ranges from one week to two years (sometimes
more).

The two parties agree to exchange at maturity, on the agreed notional
amount, the difference between interest accrued at the agreed fixed
rate and interest accrued through geometric averaging of the floating
index rate
     #+end_quote

   - FRA - forward rate agreement

     #+begin_quote
This one you know - studied at the time. 
     
The payment is based on the net difference between the interest rate
of the contract and the floating rate in the market—the reference rate.
     #+end_quote

   - FRA-OIS spread:

     Follows immediately from the reasoning above - that the
     difference between a FRA on 3 Month LIBOR and an OIS with
     maturity 3 months:

     #+begin_quote
measures the difference between the three-month Libor or the
inter-bank lending rate and the overnight index rate, which is the
risk-free rate set by central banks.
     #+end_quote

     and you can see how stressed the financial market are. I.e. the
     bigger the more fear there is among banks for longer term
     interbank loans. 


   
