#+BEGIN_COMMENT
.. title: Useful Network debugging Tools
.. slug: useful-network-debugging-tools
.. date: 2020-03-15 08:33:59 UTC+01:00
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT

#+BEGIN_EXPORT html
<br>
<br>
#+END_EXPORT

There are many handy tools you can leverage when debugging your
network. This is a brief list with possible commands to keep the
performance of your network under track and to identify the piece of
the network it is failing; i.e. whether it is a DNS, WebServer, DHCP
error or whatever. 

It moreover illustrates handy tools through which you can gain a
better understanding of internet protocols as you are able to open
individuals packages and frames at the different layers and observe
their payloads and headers.

{{{TEASER_END}}}


#+BEGIN_EXPORT html
<br>
#+END_EXPORT

* Ping
:PROPERTIES:
:header-args:shell: :exports both
:END:

This is a UNIX command that checks whether a destination is reachable.

As stated on Wikipedia:

#+begin_quote
Ping operates by sending Internet Control Message Protocol echo
request packets to the target host and waiting for an ICMP echo
reply. The program reports errors, packet loss, and a statistical
summary of the results, typically including the minimum, maximum, the
mean round-trip times, and standard deviation of the mean. 
#+end_quote


Interesting is moreover the option to customize the ping command with
the size of the payload, count of tests, the limit for the number of
network hops (TTL) that probes traverse, interval between the requests
and time to wait for a response.

Many systems provide a companion utility ping6, for testing on
Internet Protocol version 6 (IPv6) networks, which implement ICMPv6.


#+BEGIN_SRC sh :results output :exports both
ping google.com
#+END_SRC

#+RESULTS: 
#+begin_example
PING google.com (216.58.206.46): 56 data bytes
64 bytes from 216.58.206.46: icmp_seq=0 ttl=53 time=11.902 ms
64 bytes from 216.58.206.46: icmp_seq=1 ttl=53 time=2.523 ms
64 bytes from 216.58.206.46: icmp_seq=2 ttl=53 time=4.955 ms
64 bytes from 216.58.206.46: icmp_seq=3 ttl=53 time=8.905 ms
64 bytes from 216.58.206.46: icmp_seq=4 ttl=53 time=29.452 msping google.com
#+end_example


Setting the maximum amount of hops with the =-m= flag you can see for
instance what happens when the maximum amount specified is exceeded.

#+BEGIN_SRC sh :results output :exports both
ping google.com -m 10
#+END_SRC

#+RESULTS: 
#+begin_example
PING google.com (172.217.21.78): 56 data bytes
76 bytes from 62-101-124-125.fastres.net (62.101.124.125): Time to live exceeded
Vr HL TOS  Len   ID Flg  off TTL Pro  cks      Src      Dst
 4  5  00 5400 c17a   0 0000  01  01 7406 192.168.1.89  172.217.21.78 

Request timeout for icmp_seq 0
76 bytes from 62-101-124-125.fastres.net (62.101.124.125): Time to live exceeded
Vr HL TOS  Len   ID Flg  off TTL Pro  cks      Src      Dst
 4  5  00 5400 d583   0 0000  01  01 5ffd 192.168.1.89  172.217.21.78 
#+end_example

#+BEGIN_EXPORT html
<br>
#+END_EXPORT

* Traceroute

This is a computer network diagnostic commands for displaying the
route (path) and measuring transit delays of packets across an
Internet Protocol (IP) network

The idea is the following: traceroute sends multiple, special packets
toward that destinationn. As these packets work their way toward the
destination, they pass through routers.
When a router receives one of these packets, it sends back to the
source a short message that contains the name annd address of the
router. /(Computer Networking - A Top-Down Approach 7th Edition)/


The source host sending the traceroute request records the time that
elapses between when it sends a packet and when it receives the return
message as well as the name and address of the router. In this way it
is possible to record the route taken by the packet.
/(Computer Networking - A Top-Down Approach 7th Edition)/


#+BEGIN_SRC sh :exports both
traceroute www.google.it
#+END_SRC

#+RESULTS: 
#+begin_example
traceroute to www.google.it (172.217.21.67), 64 hops max, 52 byte packets
 1  dsldevice (192.168.1.254)  8.053 ms  1.609 ms  1.519 ms
 2  10.57.27.195 (10.57.27.195)  3.188 ms  2.529 ms  22.082 ms
 3  10.251.82.9 (10.251.82.9)  80.064 ms  22.095 ms  2.679 ms
 4  10.251.78.24 (10.251.78.24)  5.763 ms  2.692 ms  3.290 ms
 5  10.251.79.1 (10.251.79.1)  2.375 ms  2.978 ms  3.021 ms
 6  10.0.8.170 (10.0.8.170)  4.442 ms  8.238 ms  6.462 ms
 7  10.0.8.145 (10.0.8.145)  3.215 ms  3.198 ms  3.022 ms
 8  10.0.7.177 (10.0.7.177)  5.495 ms  3.516 ms  3.461 ms
 9  10.254.2.157 (10.254.2.157)  3.223 ms  3.205 ms  3.513 ms
10  62-101-124-94.fastres.net (62.101.124.94)  3.582 ms
    62-101-124-98.fastres.net (62.101.124.98)  3.368 ms  3.190 ms
11  62-101-124-9.fastres.net (62.101.124.9)  5.604 ms  4.959 ms
    62-101-124-13.fastres.net (62.101.124.13)  3.706 ms
12  93.62.86.153 (93.62.86.153)  3.373 ms  3.450 ms  3.383 ms
13  * * *
14  74.125.245.241 (74.125.245.241)  11.068 ms  8.961 ms
    216.239.48.230 (216.239.48.230)  6.834 ms
15  172.253.69.253 (172.253.69.253)  3.686 ms
    74.125.245.227 (74.125.245.227)  11.406 ms
    mil04s40-in-f3.1e100.net (172.217.21.67)  7.376 ms
#+end_example

In the example above you can see that my house is served by a
DSL. I am currently in Italy due to the extraordinary Coronavirus
situation. Interesting is that my dad claims we have a =fiber-optic=
internet connection contract. Would be fun to explore this further at
some point as in fact the connection here is quite poor. 

Notice that the index above states the router number the packet goes
through.
It is also important to notice that the traceroute does three trials,
i.e. it sends three different packets at equal intervals and measures
the round-trip for each. This can differ significantly. For instance
for the third router the first packet took nearly 4 times as the
second and 40 times as the third to complete the round-trip. This is
due to the *varying queuing delay* in time a router experience.

Finally, the asterisks at router 13vindicate that the target server
did not respond as traceroute expected before a timeout occurred -
this does not always indicate packet loss. If you suspect packet loss
because of asterisks in the output you can attempt to ping the
server. Probably on such networks there are Firewall settings that
prevent it from being tracerouted in the specific case.

#+BEGIN_EXPORT html
<br>
#+END_EXPORT

* Wireshark

Wireshark intercepts traffic and converts that binary traffic into
human-readable format. This makes it easy to identify what traffic is
crossing your network, how much of it, how frequently, how much
latency there is between certain hops, and so forth. This is for
instance useful when learning the Networking protocols and the packets
they exchage. For instance in the Dynamic Host Configuration Protocol
for requesting an IP address.

You can find an extensive guide to wireshark with hands-on exercises
to understand better the internet networking under [[https://gaia.cs.umass.edu/kurose_ross/wireshark.htm][this webpage]].





