#+BEGIN_COMMENT
.. title: Thesis, Term Papers and University Notes
.. slug: papers
.. date: 2020-04-12 12:53:19 UTC+02:00
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT

#+BEGIN_EXPORT html
<br>
<br>
#+END_EXPORT

This is a collection of my Master Thesis and some Term Papers written
during the University period.

#+BEGIN_EXPORT html
<br>
#+END_EXPORT

[[#mf_thesis][Master of Finance - Thesis]]

[[#fdr][False Discovery Rate - Theory and Control]]

[[#bayesian][Notes on Bayesian Statistics]]

[[#simulation][Notes on Simulation Methods]]

[[#multivariatestat][Notes on Multivariate Statistics]]

[[#times_series][Notes on Times Series]]

[[#layer3][Routing Configurations]]

[[#transport_protocol][Transport Protocol]]

[[#math3][Notes on Lin Algebra an Analysis]]

#+BEGIN_EXPORT html
<br>
#+END_EXPORT

** Master of Finance - Thesis
  :PROPERTIES:
  :CUSTOM_ID: mf_thesis
  :END:

The idea was to analyze the foreign exchange disconnect puzzle
claiming a weak relation among macroeconomic fundamentals and
FX-rates. Given the small sample used by the reference papers [[https://scholar.google.it/scholar?hl=it&as_sdt=0%252C5&q=meese+rogoff+1983&btnG=&oq=meese][Meese
and Rogoff (1983a & 1983b)]] that documented the phenomena I decided to
further investigate the puzzle collecting data for a 20 years period
and to contribute to the literature by testing the performance of
univariate and multivariate models. Moreover, on the top of it I
assessed the performance of the generalized tree structured model of
[[https://www.alexandria.unisg.ch/32631/][Audrino and Bühlmann (2001)]] similar /in spirit/ to the CART models,
where the difference is that you would not fit linearly the end nodes
but rather according to a parametric model of your choice. You can
find the code for the Thesis [[https://github.com/MarcoHassan/Exchange-Rates-Modelling][here]].

 #+BEGIN_EXPORT html
 <br>
 <br>
 #+END_EXPORT

 #+begin_export html
 <object data="../../pdfs/Thesis.pdf" type="application/pdf"
	 width="100%" height="600px" align="center">
   <iframe   jsname="L5Fo6c" jscontroller="usmiIb"
	     jsaction="rcuQ6b:WYd;" class="YMEQtfL6cTce-purZT L6cTce-pSzOP"
	     frameborder="0" allowfullscreen="" src="../../pdfs/Thesis.pdf"
	     width="100%" height="600px" align="center"/>

 </object>
 #+end_export


 #+BEGIN_EXPORT html
 <br>
 <br>
 #+END_EXPORT

** False Discovery Rate - Theory and Control
  :PROPERTIES:
  :CUSTOM_ID: fdr
  :END:

This is a presentation a colleague and me had to present for the
[[https://stat.ethz.ch/lectures/as20/seminar.php#course_materials][seminar of statistics of ETH zurich in the Fall of 2020]]. 

It was a good exercise to confront such purely mathematical papers
with little or no guidance and it was a great satisfaction tackling
them piece by piece and presenting them to our classmates. 

It was also good the seminar to tackle a mathematical research area in
a systematic way as it showed me the way on how to systematically
confront a new research area and how adding more pieces to the puzzle
the image will become systematically clearer.

 #+BEGIN_EXPORT html
 <br>
 <br>
 #+END_EXPORT

 #+begin_export html
 <object data="../../pdfs/BH_presentation.pdf" type="application/pdf"
	 width="100%" height="600px" align="center">
   <iframe   jsname="L5Fo6c" jscontroller="usmiIb"
	     jsaction="rcuQ6b:WYd;" class="YMEQtfL6cTce-purZT L6cTce-pSzOP"
	     frameborder="0" allowfullscreen="" src="../../pdfs/Thesis.pdf"
	     width="100%" height="600px" align="center"/>

 </object>
 #+end_export


 #+BEGIN_EXPORT html
 <br>
 <br>
 #+END_EXPORT




** Notes Bayesian Statistics HS-2019
  :PROPERTIES:
  :CUSTOM_ID: bayesian
  :END:

These are some notes on the first part of the ETH class on Bayesian
Statistics. The focus was mainly on setting the basis for an
understanding of Bayesian Statistics and its difference with
Frequentist Statistics.

Moreover, important focus was set on formulating non-informative priors
and the ideas behind them.

 #+BEGIN_EXPORT html
 <br>
 <br>
 #+END_EXPORT

 #+begin_export html
 <object data="../../pdfs/bayesian.pdf" type="application/pdf"
	 width="100%" height="600px" align="center">
   <iframe   jsname="L5Fo6c" jscontroller="usmiIb"
	     jsaction="rcuQ6b:WYd;" class="YMEQtfL6cTce-purZT L6cTce-pSzOP"
	     frameborder="0" allowfullscreen="" src="../../pdfs/bayesian.pdf"
	     width="100%" height="600px" align="center"/>

 </object>
 #+end_export


 #+BEGIN_EXPORT html
 <br>
 <br>
 #+END_EXPORT


** Notes Simulation Methods HS-2019
  :PROPERTIES:
  :CUSTOM_ID: simulation
  :END:


This PDF contains some notes on Simulation. These were discussed in
relation to the difficulties of integrating over the bayesian posterior
distributions that might be analytically not solvable. 

 #+BEGIN_EXPORT html
 <br>
 <br>
 #+END_EXPORT

 #+begin_export html
 <object data="../../pdfs/simulation.pdf" type="application/pdf"
	 width="100%" height="600px" align="center">
   <iframe   jsname="L5Fo6c" jscontroller="usmiIb"
	     jsaction="rcuQ6b:WYd;" class="YMEQtfL6cTce-purZT L6cTce-pSzOP"
	     frameborder="0" allowfullscreen="" src="../../pdfs/simulation.pdf"
	     width="100%" height="600px" align="center"/>

 </object>
 #+end_export


 #+BEGIN_EXPORT html
 <br>
 <br>
 #+END_EXPORT


** Notes on Applied Multivariate Statistics FS 2020
  :PROPERTIES:
  :CUSTOM_ID: multivariatestat
  :END:

  This section contains some notes on multivariate statistics. This
  was a course I particularly enjoyed. The script goes over some
  important technique such as PCA, Factor Analysis, MDS, Clustering,
  Classification Trees and Manifolds (IsoMaps).

#+BEGIN_EXPORT html
<br>
<br>
#+END_EXPORT

 #+begin_export html
 <object data="../../pdfs/multivariatestat.pdf" type="application/pdf"
	 width="100%" height="600px" align="center">
   <iframe   jsname="L5Fo6c" jscontroller="usmiIb"
	     jsaction="rcuQ6b:WYd;" class="YMEQtfL6cTce-purZT L6cTce-pSzOP"
	     frameborder="0" allowfullscreen="" src="../../pdfs/multivariatestat.pdf"
	     width="100%" height="600px" align="center"/>

 </object>
 #+end_export


 #+BEGIN_EXPORT html
 <br>
 <br>
 #+END_EXPORT


** Notes on Applied Times Series FS 2020
  :PROPERTIES:
  :CUSTOM_ID: times_series
  :END:


  This section contains some notes on times series statistics. It
  pretty much goes over the basics in a strong and solid way. It does
  not cover multivariate times series such as the Vector
  Autoregression and the Vector Error Correction Model. You might
  refer to your notes on Empirical Real Estate finance for that. The
  script goes over state-space models. I do not remember if I included
  these in the notes; this is however one of my favourite topics and
  would be fun if you have some spare time at some point to read books
  that covers the topic in depth.

#+BEGIN_EXPORT html
<br>
<br>
#+END_EXPORT

 #+begin_export html
 <object data="../../pdfs/Times_Series.pdf" type="application/pdf"
	 width="100%" height="600px" align="center">
   <iframe   jsname="L5Fo6c" jscontroller="usmiIb"
	     jsaction="rcuQ6b:WYd;" class="YMEQtfL6cTce-purZT L6cTce-pSzOP"
	     frameborder="0" allowfullscreen="" src="../../pdfs/Times_Series.pdf"
	     width="100%" height="600px" align="center"/>

 </object>
 #+end_export

 #+BEGIN_EXPORT html
 <br>
 <br>
 #+END_EXPORT


** Routing Configurations - Project FS 2020
  :PROPERTIES:
  :CUSTOM_ID: layer3
  :END:

This is the report for a group project were we had to set up and
configure an Internet Connection. We were Playing the Role of an
Autonomous System. 

We had first to configure the routers within our AS by setting the
correct interfaces configurations, the correct OSPF configuration to
properly populate the router tabeles via Dijkstra's Shortest Path, the
iBGP full mash and finally to properly configure eBGP. We finally had
to implement the proper BGP policies to our peers, costumers and
providers.  

 #+BEGIN_EXPORT html
 <br>
 <br>
 #+END_EXPORT

 #+begin_export html
 <object data="../../pdfs/Report_Group87.pdf" type="application/pdf"
	 width="100%" height="600px" align="center">
   <iframe   jsname="L5Fo6c" jscontroller="usmiIb"
	     jsaction="rcuQ6b:WYd;" class="YMEQtfL6cTce-purZT L6cTce-pSzOP"
	     frameborder="0" allowfullscreen="" src="../../pdfs/Report_Group87.pdf"
	     width="100%" height="600px" align="center"/>

 </object>
 #+end_export


 #+BEGIN_EXPORT html
 <br>
 <br>
 #+END_EXPORT



** Transport Protocol - Project FS 2020
  :PROPERTIES:
  :CUSTOM_ID: transport_protocol
  :END:


For this project we had to implement the classical Go-Back-N,
Selective Repeat and Selective Acknowledgment and Congestion Control
on the receiver and sender side of the TCP connection. The python
script based on scapy cannot be published at the moment as future
students might profit from them.

Below the handed in semester paper that should give an impression on
our solution:

 #+BEGIN_EXPORT html
 <br>
 <br>
 #+END_EXPORT

 #+begin_export html
 <object data="../../pdfs/group87_transport.pdf" type="application/pdf"
	 width="100%" height="600px" align="center">
   <iframe   jsname="L5Fo6c" jscontroller="usmiIb"
	     jsaction="rcuQ6b:WYd;" class="YMEQtfL6cTce-purZT L6cTce-pSzOP"
	     frameborder="0" allowfullscreen="" src="../../pdfs/group87_transport.pdf"
	     width="100%" height="600px" align="center"/>

 </object>
 #+end_export


 #+BEGIN_EXPORT html
 <br>
 <br>
 #+END_EXPORT


** Mathematics III HS 2015
  :PROPERTIES:
  :CUSTOM_ID: math3
  :END:

Some general notes on linear algebra and anlysis and some minor notes
into convex optimization.

 #+BEGIN_EXPORT html
 <br>
 <br>
 #+END_EXPORT

 #+begin_export html
 <object data="../../pdfs/MathIII_Summary.pdf" type="application/pdf"
	 width="100%" height="600px" align="center">
   <iframe   jsname="L5Fo6c" jscontroller="usmiIb"
	     jsaction="rcuQ6b:WYd;" class="YMEQtfL6cTce-purZT L6cTce-pSzOP"
	     frameborder="0" allowfullscreen="" src="../../pdfs/MathIII_Summary.pdf"
	     width="100%" height="600px" align="center"/>

 </object>
 #+end_export

 #+BEGIN_EXPORT html
 <br>
 <br>
 #+END_EXPORT
