#+BEGIN_COMMENT
.. title: On We Are on a Break
.. slug: on-we-are-on-a-break
.. date: 1970-02-22 10:34:14 UTC+01:00
.. tags: step down - step up 
.. category: 
.. link: 
.. description: 
.. type: text
.. status: private
#+END_COMMENT

Gosh. That kicked me. Out of a blue sky. There were issues but I
thought the relation was strong and that everything would be faced in
a mature way. Through discussion, through a fight, through a
commitment. 

{{{TEASER_END}}}

* Day 1

  So story of my life, after 3 years and something of relationship, I
  was told these magic 6 words by my girlfriend.

  I was surprised. A lot surprised. We have a long distance
  relationship. To be honest I do not believe in these break and reflect
  stories. It means the story is already over.

  She told me the 21/02/2021, by phone. Stressing her love. Saying it is
  for the best. Saying goodbye amorino at the end. I refused that
  sentence. Both at the phone and in myself. That is not how you
  act. Really? On the phone.

  The truth is also that I was pushing her to commit to put the
  relationship over the individual work achievements. I will do that in
  my life no matter what. So I was ready to do that as of now. She
  probably thinks differently. She is very ambitious and that was
  probably too much for her.

  Some say I am a kid and it is not normal to commit to the other over
  the job from such a young age. But really? If you don't do it now,
  then when? When responsabilties will augment? I do not believe that
  kind of narrative. If you follow a line you follow it from the
  beginning. Plus we were just discussing on committing on a city. I am
  sure that life is complex, and if you adapt, put good effort and you
  are good, you will do well no matter what. So I really do not
  understand when people act in an opportunistic way. They are probably
  just scared and not confident enough in their capabilities. I do not
  think that it is the case of her. She is not the type. There might be
  some aspect of work relating to this though. Plus in any case I am
  convinced that we both did work too much recently.

  Well, now I do not know if that is what is in her head. In fact,
  unfortunately I do not know at all what is in her head. She just told
  me at the phone in 5 min. And me, I was too surprised to get this news
  and in such a method. I could not start a conversation. A serious one
  asking what was wrong. We had met the weekend before. If she wanted to
  face things we could have done it then.

  Anyways, she promised a letter. I guess that there, there will be more
  motivations. I will then wait for this and see. In any case I really
  think that our relationship is on the ground. I do not see it as a
  true possibility to gain it back. Also trust. Yesterday night, in the
  first night; I was so tempted to say screw you. It's over; I will not
  wait here like a sentenced to death person. If there are issues let's
  face them and solve them otherwise let's let each other go, no matter
  how difficult that is.

  I resisted. I controlled myself. I decided to wait until the
  letter. Let's see what will come then.

  In any case the emotion of this first day is the following: *anger*. I
  am happy though that I could control it that far. Did not text her so
  far. And committed to wait and give it a try. Let's see how it will
  develop in the next couple of days.

* Day 2

  I texted her. I could not accept that we are on a break story. Like
  this, without any explanation. It was too much.

  I really think that if there are issues you go and solve them. So I
  texted her. I told her that either we would discuss and see what to
  do and face it or we would break up 100%.

  I think it was the right decision. She told me I am right. And she
  told me she agreed that she gave to little explanation. Let's see
  how it will evolve. She made me understand she is still in love. She
  just has this very aggressive strategy of fixing an issue of us. I
  do not see as the solution.

  I really hope we will be able to sort things out.

  In the last day I started to listen to one music album. I was
  listening to it before I did text her. It is so deep. It expresses
  well my feelings for her. It is [[https://www.youtube.com/watch?v=5YAX8wgdQRU][this wonderful album]]. I decided I
  will create a [[https://www.google.com/search?q=milktape][milktape]] for her birthday and give it to her. I will
  include some of the songs I like the most. A bit old fashioned but
  it is indeed one of the most romantic things and I guess one of the
  nicest presents one can get.
  
  I think now the most important thing is to understand how she feels
  really. And face her in the right way. She is a very special girl. I
  have to be careful with her. She does not speak much openly on what
  she has in mind. This entire situation is just a demonstration of
  that. Also, her big life hit. She just talked to me about it once in
  3 years. After I pushed a bit. She is so precious. But you must make
  her understand somehow that it is important to talk more.

  
* Day 3

   I am calm now. I do not feel that pressure of the first day
   today. I feel normal. Maybe that is wrong. I should call with her
   today. Let's see if she will call.

   I also booked for going to Frankfurt in two weekends. We will see
   how it will develop.

   Finger crossed.

   
* Day 4

   Ok so I did talk to her. Everything looks fine. It was just poor
   communication. I told her in any case that we have to improve in
   this dimension and that she has to open up a bit more.

   Meaning that she cannot do like this, i.e. not tell me what she has
   in mind for a longer period of time and the suddenly break out with
   such a huge thing. It mines trust in one relationship. She told me
   it was just this one thing that she kept from me.

   I told her that it is not good. Cause if she does not tell me that
   one thing and keeps it from me, then I cannot act on it. On top of
   it once I know it, in such a way, like now, I start to think that
   there could be 1000s other things that she is thinking under
   cover.

   And then it gets more difficult to be relaxed and be who you are.

   This is why information is important.

   
* Day 7

   I skipped a bit of days. Went skiing for a weekend with friends. It
   helped a bit to free up the mind. I talked with her when being
   there. Also with the other friends as they are friends in common.

   I think everything is back to normal now. More less. We will just
   have to solve this issue of us and start to talk more openly when
   things do not work.

   I will now stop to make daily updates and will continue with weekly
   updates.
   
* Day 14

   So I was in Frankfurt last weekend. It was nice. I slept in an
   hotel. We saw each other for dinner. We had a great time
   together. There is a great bound between us. I think that this
   surprise stressed it even more.

   We made out a strategy and a plan on how to deal with our issue in
   the future. I think everything will be good. Tackling it bit by
   bit.

   However, you should learn your lesson from it. You should not let
   it go for too long when there is something you do not like. On the
   long run otherwise everything will emerge. As we say in italian:
   /tutti i nodi vengono a galla/. So you have to deal with them at
   the right time.

* Day 21

   So we are now in this setting where we do not hear each other. She
   asked for it and I accepted at the end of a conversation. From my
   point of view is not changing too much. Because of her work we were
   not talking too much in either case on a daily basis. But now that
   you have to think about it you note it better.

   I am still in awaiting mode. I should still get a letter from her
   and I really hope that she will find the serenity from this
   period and that we will start a new white page after it.

* Day 28

  After two weeks we called. She seems to be good luckily. She is just
  working so much that it is crazy. The more time goes by, the more I
  think this is the real issue.

  At the moment there is little I can do to be honest. Just have
  patience and give time to the time. We will see at the end of the
  day how everything will evolve. I guess that we will have to wait
  until September and we have to test together again the living
  together. Just at this time we will start to slowly get back to
  where we were cause as at the moment it is just to difficult.

* Day 35

  Omg. it's already 35 days since it happens. I am tired of this
  situation and relation. We really have to see us more often. I have
  to wait more than one month to see her I understood. A bit too much
  for my taste. My energies are going away. I have to quickly gather
  them back.

  
* Day 42


  I am tired. I had to pull her ears. I mean I do not know what is
  going on with her. She is so unrespectful and she seems not to care
  anymore about the relationship. She has to understand that whatever
  is going on with her she has to care for the others.

  I should speak with her today Monday 05.04 as yesterday after 2
  weeks without talking as agreed she was sporadically answering or
  saying she would call later, which she never did.


* Songs for Milktape

  - No One's Gonna Love You (Band Horses)

  - Detlef Schrempf (Band Horses)

  - don't think twice, it's all right (bob dylan)  

  - Window Blues (Band Horses)

  - Homeward Bound (Studio Version) (Simon and Garfunkel)

  - leaving on a jet plane (denver)

  - c'est la vie (alfa)  

  - That sea, the Gambler (Gregory Alan Isakov) - it's an ablum. First
    one is nice.

  - That sea, the Gambler (Gregory Alan Isakov) - also at minute 29:30
    nice.

  - open your eyes (snow patrol)

  - new slang (the shins) *davvero bellissima*.

  - rocket man (elton john)  
  
  - patience (Guns N' Roses)

  - black (pearl jam)

  - hero (family of the year)

  - Dean Martin - That's Amore

  - another day in paradise (phil collins)

  - somewhere only we know (keane)

  - scenes from an italian restaurant (billy joel)

  - part one (band of horses)  

  - [[https://www.youtube.com/watch?v=0Hegd4xNfRo][Leon Bridges - River]]

  - Paolo Nutini - Iron Sky

  - flume - bon iver

  - simple song (the shins)

  - father and son (cat stevens)

  - vincent (don McLean)

*True Starting Date:* 22/02/2021
