#+BEGIN_COMMENT
.. title: Swagger and OpenAPI
.. slug: swagger-and-openapi
.. date: 2021-02-11 11:57:33 UTC+01:00
.. tags: API
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT


This post is a reference for further work. It is a milestone and a
reminder that such things exists and maybe you will use them at some
point depending on what work will you do.

{{{TEASER_END}}}

So I started to work in a messy project with very big APIs.

I am working with Swagger and =Openapi= specifications. It is a very
cool feature and you can navigate quickly the API with it. Given the
Openapi specification given as a =YAML= or =JSON= it gives you an
overview of all of the different APIs.

If they are well written according to the standards you should be able
to quickly read all the possible information relating to the API,
i.e. what you should pass, the schema of the thing you have to pass,
required fields etc.

As an end user it is quite practical to use and everything is more
less straightforward.

If you have to write it I guess that you would have to read deeper
into it [[https://swagger.io/specification/][here]]. If you will work as a data scientist you will probably
not have to deal with it too much.

If you will work as a data engineer or machine learning engineer or
architect at some point it might be useful to give it a read at some
point and make some documentation on how to properly set up and
specify APIs and not just do very rough flask APIs.

** UPDATE 22/04 - Very easy way to create swagger documentation in Flask

 There are also ways and packages to align flask with swagger. See for
 instance this [[https://github.com/rantav/flask-restful-swagger][here]]. From the code base that I am working on now it
 does not seem to be very special. You can just specify your apis in
 the json syntax from there and then you will serve them through your
 backend.

 What is maybe interesting is that the classical front-end is also set
 from there so that everything is ready to be consumed and you as
 back-end developer do not have to make too much effort for
 it. Probably like this. Double check at some later point if you need
 to use it.

 Yes, so I tested it and it is like that. In your flask you also will
 have a =swaggerui= folder. Just put it in your flask repo and forget
 about it. It gets all of the info of interest automatically as long
 as you use the correct syntax. Check at a demo project working with
 it [[https://github.com/neo4j-examples/neo4j-movies-template][here]].





