#+BEGIN_COMMENT
.. title: Mah sipur shel hamishpaha?
.. slug: mah-sipur-shel-mishpaha
.. date: 2022-01-22 15:38:06 UTC+01:00
.. tags: perRep
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT

{{{TEASER_END}}}


 #+begin_export html
<style>
.container {
  position: relative;
  left: 15%;
  margin-top: 60px;
  margin-bottom: 60px;
  width: 70%;
  overflow: hidden;
  padding-top: 56.25%; /* 16:9 Aspect Ratio */
  display:block;
  overflow-y: hidden;
}

.responsive-iframe {
  position: absolute;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  width: 100%;
  height: 100%;
  border: none;
  display:block;
  overflow-y: hidden;
}
</style>
 #+end_export

So this is an important post to me. 

It is important as I will put in here some very deep thoughts about
myself as a person. 

The thing is that I am starting to create some more personal posts, as
I see that blogging is a very nice thing and to limit it just to some
work-related thing would be an error. 

I want this blog to be part of my legacy. I want this blog to
ultimately represent myself as a whole. I want it to be a picture of
myself in time. 

I want my children to come here in decades and understand my story and
their story. This also because I think that the history of my family,
like most of the Jewish families stories, is very tragic and rich and
it was a pity for me to discover it just slowly in time. It delayed my
understanding of my /shorashim/ and it cost me precious time to shape
myself in a given direction from a very tender age, when everything is
much easier. 

To know and understand your story is important. Life is hard and
complex. It is hard and sometimes its meaning is not straightforward
and it is then easy to loose direction, to forget about higher
life-goals and ultimately end up living a void life. The same void
life that brings then young people without a purpose to start drinking
and making use of drugs, to people commit suicide, fight with each
other etc. etc. 

So let's come to the meat of the post...

* Mah sipur shel hamishpaha - on the father side?

  Well let's say that I did not understand the story of my family when
  I was young. 

  I remember that I was confused when seeing that part of my
  family. They were complex, weird, different. 

  Now, after some time, when growing up, getting to know their story,
  their legacy, their culture, now I understand things better. I
  understand that their character and behavior was dictated by their
  legacy and by their story of sorrow. 

  So in order to understand that piece of history, understand this:
  the story of your family is essential the one of the Jewish community
  of Libya:

   #+BEGIN_EXPORT html
   <br>
   <br>
   #+END_EXPORT
   
#+begin_export html
 <div class="container">
  <iframe class="responsive-iframe" src="https://www.youtube.com/embed/svvJYRDXQbI" frameborder="0" allowfullscreen;> </iframe>
 </div>
#+end_export

   #+BEGIN_EXPORT html
   <br>
   <br>
   #+END_EXPORT

   And in order to understand it even better watch the following

   #+BEGIN_EXPORT html
   <br>
   <br>
   #+END_EXPORT
   
#+begin_export html
 <div class="container">
  <iframe class="responsive-iframe" src="https://www.youtube.com/embed/x3H6cM1_2Bw" frameborder="0" allowfullscreen;> </iframe>
 </div>
#+end_export

   #+BEGIN_EXPORT html
   <br>
   <br>
   #+END_EXPORT

   Now understand that your family was one of the families that stayed
   in Libya until the very end, until the 1967 and the pogroms that
   happened following the six day war in Israel.

   Understand that your family was among the 5k Jews that stayed until
   the end due to economic interests as mentioned in the documentary
   above. I discovered in time that your family was among the most
   wealthy in the country. They apparently had a very large commercial
   business and had a lot of real estate there.

   With 1967 they lost it all. They lived the pogrom, were locked down
   for days with the fear of being killed. Later they eventually managed
   to come to Italy thanks to the help of the Italian government. They
   arrived with 20 dollars and 20 kg of personal effects as all of the
   other 5000 Jewish people that left Libya in 1967. 

   They were then among the 2000 Jews that stayed in Italy after their
   arrival. They settled down in Milan. This was possible for them cause in
   comparison to many other families, their wealthy business of the
   time had a smaller business unit in Italy and some part of the
   larger Hassan family was taking care of
   it. They helped the rest of the family - including my father,
   uncles and grandparents - to settle down in Italy.

   I think that my father's family never fully recovered. At least I
   am sure as far as my grand-parents are concerned. This is why they
   were weird and it was strange to go to see them. This is why they
   were different and I never liked too much spending time there when
   I was a child. I was just doing it because I understood that my
   father did care about it. 

   I think that as well said in the video at [[https://www.youtube.com/watch?v=x3H6cM1_2Bw&t=838s][this moment]] the real
   issue with their recovery was not the wealth loss but rather the
   identity loss. I think that for my grand-father it was a huge loss,
   from being an entrepreneur and on the head of a big business to
   have nothing to do in his time. And the cultural shock was huge for
   him as well: the complete different culture - I recall that
   the culture of my family, and you still see it my father and my
   character at times, was very much Arab.

   But the loss was not just limited to the grand-parents. It affected
   their children as well. My oldest uncle, that was around 20 when
   the pogrom of 1967 happened never fully managed to reboot his
   life. He never managed to start from scratch with the studies, the
   work and to construct a family in Italy. 

   The other two did manage. It was easier for them; my father was 10
   when the pogrom happened. Not without sorrow. My father once
   confessed me that he eventually became entrepreneur and started his
   own business in his early 20s in order to give again some
   entrepreneurial light to his father, which he saw highly suffering
   after settling down in Italy. 

   It is also incredible the connection with that bit of past from my father.
   This despite of the fact that he moved to Italy with 10. I still recall when he was
   diagnosed cancer how we used to spend afternoons watching videos of
   [[https://www.youtube.com/channel/UC5QS0Oa6zBbknPbHA8GRd8Q][Hamos Guetta]] youtube channel. I mean I moved to Switzerland with
   17 and I do not feel such a strong connection with Italy in this
   sense. But somehow surprisingly I do with Israel and that small
   number of Libya Jewish people. 

   That is interesting as I was raised up in a mixed family with
   secular traditions and liberal mindset. But this I guess is the curse of every
   person where the Jewish blood flows. You do not cancel such past
   and struggles and with time when you understand the relativity of
   the world it grows in you.

   In this sense, I do not know how it will proceed with me. I would
   like to preserve such roots in time. But everyone that knows a
   little bit the Jewish communities knows that it is not as easy for
   a person that grew up outside of a strict Jewish education as
   me. There is risk that such history will get lost in time. I am in
   a personal struggle which is not easy to solve. 

   I am paying my dues by further educating myself, growing my
   understanding of the Israeli story, understanding how everything
   came about, educating myself about what it means to be Jew,
   learning Jewish history, learning Hebrew. But will it be enough?
   Who knows... we will see. 

   In any case whatever the /sipur/ of my family will be in time,
   know this part of it. Know what your family has been
   through. Know that we once lost it all and we managed to slowly
   reconstruct ourselves. Know the suffering, inform yourself and
   educate yourself to the Jewish tradition and history as it is a rich
   one and it enriches the spirit of the individual as well. 

   This especially if growing up in the EU society which is
   traditionally anti-Israeli. Never feel ashamed of your roots. Too
   long I was probably fearing some judgment of the people due to my
   lack of understanding of the things. 

   Read and understand Jewish and Israeli history and you will start
   to understand what Israel is and don't ever let yourself be
   intimidated by your peers with little or no knowledge of Israel and
   its history. With little understanding of what Israel is and what
   it represent to Jewish people and families as mine that lost it all
   due to their religion. With little understanding of the
   difficulties of keeping a fragile nation alive. 

   Watch/read in this sense:

   - Exodus; Paul Newman

   - the classics of Holocaust

   - Letters of Jonathan Netanyahu

   - Israel - the history of a nation reborn

   - understand aliyah and its idea

   - understand taglit-birthright 

   etc. etc.

   



