#+BEGIN_COMMENT
.. title: On a Fragile Mind
.. slug: on-a-fragile-mind
.. date: 2024-01-26 18:24:07 UTC+01:00
.. tags: perRep
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT


Everything takes its toll. 

I had a happy life for most of my time. There were little ghosts in my
life; until:

#+begin_quote
Nel mezzo del cammin di nostra vita mi ritrovai per una selva oscura
ché la diritta via era smarrita.  

Ahi quanto a dir qual era è cosa dura esta selva selvaggia e aspra e
forte che nel pensier rinova la paura!

Tant’è amara che poco è più morte; ma per trattar del ben ch’i’ vi
trovai, dirò de l’altre cose ch’i’ v’ho scorte.
#+end_quote


So I will not focus on the details of the "selva oscura". I learned in
time that it is better to let it be. 

I still have to face the scars that beasts of the selva oscura left in
my soul. After all I am a human and I am [[https://www.youtube.com/watch?v=dfBj4i8MKH4][fragile]].

{{{TEASER_END}}}


** On the Human Being

   "You are a human being; you have the love of humanity in your
   heart". Cit.

   But then again:

   "Love takes it toll when it doesn't work". Cit.

   So you faced the lack of love. You have experienced the dark roads
   that let brothers and sisters killing each other.

   You experienced envy, violence, lack of morality, lack of
   compassion, power abuse. You saw first hand what happens when a
   handful of powerful human beings decide to put forth their agenda
   taking G-d outside of the picture. 

   Boundaries are overstepped. And when you strip away boundaries, you
   might start to misbehave. [[https://encyclopedia.ushmm.org/content/en/article/the-biological-state-nazi-racial-hygiene-1933-1939][Whatever is possible - can be done]]. 
   You might start to develop a sense of omnipotence. That might make
   you feel strong. 

   But then what about - rachamim?
   
   #+begin_export html
    <img src="../../images/Screenshot 2024-01-26 181654" class="center">
   #+end_export


** On Trust

   "What happens when life brings you down; when there is systemic
   contradiction?" Cit. 

   Once you have seen what the human being is capable of [[https://www.youtube.com/watch?v=nnEcwY6zIpw][it is hard to
   reboot]].

   The question after all is: [[https://www.youtube.com/watch?v=6TdvhkgTv2Y&t=167s][How do you know you can trust someone?]]

   The proposed answer is simple: you trust them. 

   Nonetheless if you have seen people following: "Elohim acherim", it
   is not easy. How do you know when opening up that they will not use
   the information shared it in their service to the acherim.

   You start to get paranoid. After all you were told that
   coincidences do not exist. That everything has a purpose and
   meaning. 

   But then again what are people chasing? What they are going after?
   Why are they so interested in your stories and thoughts?

   It is hard not to enter the negative loop. You experienced it
   yourself. You already had two major breakdowns where you lost trust
   in every single person that surrounded.

   Fear is the result.
   

** On Fear

   Here again [[https://www.youtube.com/watch?v=KZGfGJvY2Dg][Hollywood comes at rescue]].

   The same negative reinforcing loops you experienced yourself
   leading you to the mental crackdown.

   The solution is therefore clear: to love. The solution is to be
   brave. To see the good in the world and let the holy dark move
   without trying to change it; before it changes and affects you. 

   But then again - [[https://www.youtube.com/watch?v=H_MJAEBOERk][Jesus - what was that?]] The King was killed after
   all.

   And here the solution is probably to accept the fact that:
   "Life is a mistery - do not waste time trying to understand it".


** Where is the love?

   You are still trying to find that balance. The one you had before
   encountering the beasts of the "selva scura". You could easily
   trust everybody and love everything before. Without questioning too
   much. 

   But now everything it is different. How to live with the wolves,
   ghosts and hyenas? How do you eliminate fear from your life? 

   When you feel the lack of love [[https://www.youtube.com/watch?v=WpYeekQkAdc][the perils are great]].

   The solution is in Humor - and [[https://www.youtube.com/watch?v=7yzC-uW2w1c&t=213s][don't waste time trying to figuring
   life out]]. [[https://www.youtube.com/watch?v=FJ3N_2r6R-o][Laugh with the world]]; accept that the holy dark is moving
   too and then inshallah - live with love and focus on the bright
   side and do not let fear enter your life or you will have again to
   face that downward spiral leading to [[https://www.youtube.com/watch?v=1Epg_O8R358][your ultimate isolation]].


