#+BEGIN_COMMENT
.. title: Video Blog
.. slug: video-blog
.. date: 2021-01-03 14:27:07 UTC+01:00
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT

#+BEGIN_EXPORT html
<br>
<br>
#+END_EXPORT

I saw this tradition of a person recently. One video per month. I
liked it and will start it as well. 

This is my space of fun. My way to take a break from work and have a
laugh and/or thought with you - anonymous reader. 

#+BEGIN_EXPORT html
<br>
<br>
#+END_EXPORT


 #+begin_export html
<style>
.container {
  position: relative;
  left: 15%;
  width: 70%;
  overflow: hidden;
  padding-top: 56.25%; /* 16:9 Aspect Ratio */
  display:block;
  overflow-y: hidden;
}

.responsive-iframe {
  position: absolute;
  top: 60px;
  left: 0;
  bottom: 60px;
  right: 0;
  width: 100%;
  height: 100%;
  border: none;
  display:block;
  overflow-y: hidden;
}
</style>
 #+end_export



* 2021

** January 

How not to start with Bradbury? You will laugh a lot.  Do you believe
in miracles? Read the comment of Antonino Pio then. There will be the
surprise.

   #+begin_export html
<div class="container"> 
  <iframe class="responsive-iframe" src="https://www.youtube.com/embed/pBxp_Nx2vfc" frameborder="0" allowfullscreen;> </iframe>
</div>
   #+end_export
