#+BEGIN_COMMENT
.. title: Kubernetes
.. slug: Kubernetes
.. date: 2019-09-06 18:21:43 UTC+02:00
.. tags: IT Architecture
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT

A strong orchestrator tool that operates above the container level and
allows to manage a cluster to handle containers.

It is essentially the toolset that lets you manage containers.

Enterprises can use it to manage the lifecycle of containerized apps
in a cluster of nodes, which is a collection of worker machines such
as virtual machines (VMs) or physical machines.

In general kubernetes try to leverage clusters in order to avoid
having a single point of failure.

{{{TEASER_END}}}

Note that in the world of Kubernetes the terminology of the cluster is
slightly different to the one of Big Data.

While the virtual machine controlling other VMs is called master VM,
the other are not called /workers/ but rather /nodes/.

* Master

The master has multiple components, all under the umbrella of a single /control plane/.

The main componing is the API server. API server manages scheduling that goes through the REST services.

