#+BEGIN_COMMENT
.. title: Monitor Driver ThinkPad Dock-USB 3.0
.. slug: monitor-driver-thinkpad-dock-usb-30
.. date: 2019-10-19 09:35:01 UTC+02:00
.. tags: Hardware Config
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT


#+BEGIN_HTML
<br>
<br>
#+END_HTML

Last week I received the last piece to get up and running my ThinkPad
USB-3.0 docking station. While, the configuration worked out of the
box for windows systems, configuring the docking station with Ubuntu
OS was not straightforward.

{{{TEASER_END}}}

It turned out that the Ubuntu OS needed an installation of an external
driver in order to properly work with the docking station.

As always /stack-overflow/ was a useful friend and I was manage to
find [[https://support.displaylink.com/knowledgebase/articles/615714#ubuntu][this useful link]] outlining the necessary steps in order to
download the necessary dependencies and install the needed driver.

Once that is done your docking station should work out of the box.

You can then look at the connected monitors using the terminal command

#+begin_src sh
xrandr -q
#+end_src

And once you find the monitor, which you might want to change the
orientation you can run

#+begin_src sh
## xrandr --output <monitor name>  --rotate <direction>

xrandr --output DVI-I-2-2 --rotate left
#+end_src 



