#+BEGIN_COMMENT
.. title: Equity Factor Model
.. slug: equity-factor-model
.. date: 2022-05-19 15:58:38 UTC+02:00
.. tags: finance
.. category: 
.. link: 
.. description: 
.. type: text
.. status: private
#+END_COMMENT

So this post starts to dig into equity factor models.

Essentially you will understand how the factor models for your risk
systems are derived.

This basically goes in tandem with the fixed income risk factors
models briefly touched in your other post.

This is basically a very high level overview, on the intuition of the
way the big risk system providers generate their risk factors.

So the essential idea is always the same, get a linear approximations
for the risk based on some factors of interest.

{{{TEASER_END}}}

Equity factor models are specified for single countries (of which
there are 41 in total) plus the EMU - european monetary union - as a
single country model. On the top of it for the EMU you as well add
some specific country factors in order to make a differentiation
across the various countries.

Note that two classes of equity factors are used: /industry/ and
/style/ factors.

So basically the difference among the factors is roughly the
following.

- /industry factors:/

  these represent the industry of the equity - semiconductors, pharma,
  tobacco etc.

  this is for sure a strong driver for the returns.

- /style factors:/

  on the top of it you have the relevant style factors.

  these are the common factors used in the industry that checks more
  the common accounting and financial properties of the academic
  literature.

  Say for instace:

  - beta 

  - yields

  - growth

  etc. etc.

  With the two set of factors you do then the relevant regressions on the equity
  returns, in such a way you can estimate the relevant factors
  mentioned above. Note that the returns are trimmed - in the sense
  that they are capped in the case of too extreme returns.

  There are then some quirks on how to estimate everything but this
  is just computational issue that is solved by iterative methods
  trying to stabilize everything.

  Then apart from it everything is pretty standard and there is
  nothing fancy. Just a cross-sectional regression through which you
  get the factors in time and through which you can compute you
  covariance matrix and simulate everything.

  The only interesting bit is that you have factor loadings on that
  equity model, that are estimated in a first step. Then based on this
  you run your standard regression.

** Factor Loadings

   
*** Industry factors loadings

    So basically here you have already some loadings that already
    capture quite some fundamental information, in the economic sense.

    I.e. the loadings capture information about sales and assets in
    particular industries and their relation to the values of the
    companies.

    In particular they give the average value/sales and value/assets
    in an industry by regressing across all of the companies available.

  
*** 

  

  

  
   

