#+BEGIN_COMMENT
.. title: Helm
.. slug: helm
.. date: 2021-05-27 17:16:46 UTC+02:00
.. tags: Container Management
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT


This are some notes on Helm.

Recently I have downloaded a chart. I will have to change the
configurations of this.

I will have to configure static IP for the internal application
running in kubernetes such that my service will be externally
accessible. 

Here some notes based on that and some commands.

I will expand on this in the future depending how much I will have to
work with it.

{{{TEASER_END}}}

* Helm Important Commands

  First of all it makes sense to look at the deployed chart.

  You can get all of the info regarding your deployed chart via

  #+BEGIN_SRC sh
  helm get all <chart-name>
  #+END_SRC

  There the output might be especially long.

  In this sense you can also restrict the view to the manifest, say
  with

  #+BEGIN_SRC sh
  helm get manifest <chart-name>
  #+END_SRC

  That will likely also be long. This depending on the complexity of
  the chart.

  Notice

* Helm history and relases

  A good idea to start with helm is to read this [[http://technosophos.com/2017/03/23/how-helm-uses-configmaps-to-store-data.html][entry]].

  There it is still based on tiller and v2 but it should give you a
  basic idea.

  

  
  

  

