#+BEGIN_COMMENT
.. title: Equity Factor Model
.. slug: equity-factor-model
.. date: 2022-05-19 15:58:38 UTC+02:00
.. tags: finance
.. category: 
.. link: 
.. description: 
.. type: text
.. status: private
#+END_COMMENT

So this post starts to dig into equity factor models.

Essentially you will understand how the factor models for your risk
systems are derived.

This basically goes in tandem with the fixed income risk factors
models briefly touched in your other post.

This is basically a very high level overview, on the intuition of the
way the big risk system providers generate their risk factors.

So the essential idea is always the same, get a linear approximations
for the risk based on some factors of interest.

{{{TEASER_END}}}

Equity factor models are specified for single countries (of which
there are 41 in total) plus the EMU - european monetary union - as a
single country model. On the top of it for the EMU you as well add
some specific country factors in order to make a differentiation
across the various countries.

Note that two classes of equity factors are used: /industry/ and
/style/ factors.

So basically the difference among the factors is roughly the
following.

- /industry factors:/

  these represent the industry of the equity - semiconductors, pharma,
  tobacco etc.

  this is for sure a strong driver for the returns.

- /style factors:/

  on the top of it you have the relevant style factors.

  these are the common factors used in the financial space that checks more
  the common accounting and financial properties of the academic
  literature.

  Say for instace:

  - beta 

  - yields

  - growth

  etc. etc.

  With the two set of factors you do then the relevant regressions on the equity
  returns, in such a way you can estimate the relevant factors
  mentioned above. Note that the returns are trimmed - in the sense
  that they are capped in the case of too extreme returns.

  There are then some quirks on how to estimate everything but this
  is just computational issue that is solved by iterative methods
  trying to stabilize everything.

  Then apart from it everything is pretty standard and there is
  nothing fancy. Just a cross-sectional regression through which you
  get the factors in time and through which you can compute you
  covariance matrix and simulate everything.

  The only interesting bit is that you have factor loadings on that
  equity model, that are estimated in a first step. Then based on this
  you run your standard regression.


** Factor Loadings

   
*** Industry factors loadings

    So basically here you have already some loadings that already
    capture quite some fundamental information, in the economic sense.

    I.e. the loadings capture information about sales and assets in
    particular industries and their relation to the values of the
    companies.

    In particular they give the average value/sales and value/assets
    in an industry by regressing across all of the companies available.

    So you see that these information is actually ultimately used when
    processing your model.
  
*** Style factors loadings

    As mentioned these are factors that are relevant in the financial
    space coming out of the financial theories.

    I check next how these different things are expressed.

    
**** Beta Factor Loading

     Nothing new. 101 of finance.

     You basically estimate the coefficients for each security across
     time using a weighted regression.

     Then you have your alpha and beta coefficients.

**** Momentum Factor Loading

     This is constructed based on two main components:

     1. historical alpha:

	this are the alpha in time for a given security coming out
        from the CAPM.

     2. relative strength:

	this is basically a proper momentum measuring the returns in
        the previous tradings days.     

     How the two are mixed up is then based on some optimization
     exercise maximizing the explanatory power. This is however based
     on a grid search optimization and the way the grid is initialised
     is based on qualitative elements.

     
**** Earnings Yield Factor Loading

     This loading is basically the product of thee different
     statistics:

     - *predicted* earnings-to-price ratio 

     - *cash* earnings-to-price ratio

     - *trailing* earnings-to-price

     All of them are given different weights when constructing such
     measure. I guess that such parameters are determined in a similar
     way as described in the previous sub-chapter.
     
     
**** Growth Factor Loading

     Again a mix of different statistics. Have to understand where all
     of these parameters are entered into the system.

     - weighted average of long-term /predicted earnings growth/

     - five-year trailing /earnings growth/

     - five-year trailing /sales growth/
     
     I wonder how they compute such predictions.
     

**** Dividend-to-price Factor Loading

     Trailing 12 month dividend yield.
     
**** Book-to-price Factor Loading

     Last reported book value divided by market capitalization in
     period /t/.
     
**** Leverage Factor Loading

     Mix of three different statistics:

     - weighted average of market leverage (MLEV)

     - debt-to-assets ratio (DTOA)

     - book leverage (BLEV)

     So you see here the classical value investment metrics a la
     Graham.

     You can see then in the document if you are interested how all of
     these are exactly constructed. 
       
**** Liquidity Factor Loading

     Again through classical value investing statistics.

     Skipping everything for now as I do not want to get into it.

     
**** Size Factor Loading

     Some reasonings around the market cap of the company.

     So this measures the influence of the size of a company and
     having worked for quite big companies as of now I can well
     imagine why it enters as a factor.
     
     
**** Residual Volatilty Factor Loading

     Again average of statistics reporting some volatitlity
     statistics.
     
     
** Implied Volatility Factor Models

   So these are used for the exotic instruments, i.e. the different
   options and the mortgage backed securities.

   Here basically is the usual story of using a pricing function,
   invert it and get the volatility based on the observed price.

   In BarraOne the dependence on =K_i= is suppressed (only
   “at-the-money” implied volatilities are modelled) in which case the
   problem reduces to describing the evolution of the volatility term
   structure =σ_i (t, T_i)=.

         
   

