#+BEGIN_COMMENT
.. title: Accessing protected content via GET requests
.. slug: accessing-protected-content-via-get-requests
.. date: 2020-03-21 08:34:45 UTC+01:00
.. tags: web
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT

#+BEGIN_EXPORT html
<br>
<br>
#+END_EXPORT

Sometimes when I want to make notes I prefer to download an html file,
transform it to an =.org= file via =pandoc= and to edit and make notes
in org mode. 

Nonetheless if the technique works fine for non-protected HTML pages,
sometimes you are required to pass some authorization variables to
access a page. This post outline my solution to deal with the latter case.

{{{TEASER_END}}}

In this case you might want to authenticate on your browser, open for
instance the google developer tool, copy the file of interest into
your org file.

The solution is however quite tedious, especially if you have multiple
sites you want to download. A simpler solution is to open the google
developer tool and go under the networking settings. There you can
select the GET request to the server for your desired page.

Once you click on the request, that usually might be easily identified
in the network as it consumes the most of the bandwidth, you can
select the =Headers= tab and you can inspect the authorization, and
cookie headers passed with the GET request. 

You can finally save such headers in a =.json= and pass it with all of
your =GET= requests to your desired webpages. 

A minimal python script to do that is as follows:

#+begin_src python
import requests
import json

# both 'x-test' and 'x-test2' are sent


with open('/Users/marcohassan/Desktop/prova_header.json') as json_file:
    data = json.load(json_file)

a = requests.get('https://learning.oreilly.com/library/view/hbase-the-definitive/xxxxxxx/ch01.html', headers = data) 

with open('/Users/marcohassan/Desktop/prova.html', "w") as file:
    file.write(str(a.content))
#+end_src


To convert to the html to an org file you can finally run in your
shell

#+begin_src sh
pandoc -o prova.org -f html -t org prova.html 
#+end_src






