#+BEGIN_COMMENT
.. title: Book Wisdom
.. slug: book-wisdom
.. date: 2019-06-29 21:18:08 UTC+02:00
.. tags: perRep
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT


This posts contains some quotes that I liked when reading books.

{{{TEASER_END}}}

** State at any Cost

  #+begin_quote
  True friendships are acquired only in youth, and views or ideas cannot
  harm them.

  On the contrary, the older a person gets, forces from deep within him
  take him back more and more into the world of his boyhood and youth.

  (A State at Any Cost - Reconciliation of Zemach and Ben-Gurion).
  #+end_quote

  #+begin_quote
  A man is not always rational.

  It was not a single thing that broke him in the end, but rather an
  entire range of tensions, anxieties, and people, from Lavon to
  Kennedy, from Dayan to Nasser. Take all together it was now more than
  what he could handle.

  (A State at Any Cost - Ben-Gurion motivating his last resignment). 
  #+end_quote

  #+begin_quote
  He believed that the Jewish people chose God before God chose the
  Jews.

  "You chose God for yourselves (Joshua 24:22)".

  (A State at Any Cost - Ben-Gurion about the meaning of being Jew)
  #+end_quote

  #+begin_quote
  I do not believe that God spoke... but I also do not believe that
  there are only physical forces in the world.

  There is a thing called mind, no matter how it is called, there is
  something higher than physical processes, in the entire universe.

  (A State at Any Cost - Ben-Gurion on being a different Jew)
  #+end_quote

  #+begin_quote
  The thirst to write is of inestimable power.

  (A State at Any Cost - Zemach last written words before dying)
  #+end_quote

** Creative Schools - On the need of reformation of education

 #+begin_quote
 But Revolutions don't wait for legislation. They emerge from what
 people do at the ground level.

 Education does not happen in the committee rooms f the legislatures or
 in the rhetoric of politicians.

 (Creative Schools - On the need of reformation of education)
 #+end_quote

 #+begin_quote
 It's often said that we have to save the planet. I'm not so sure. 

 If you imagine the whole history of the Earth as one year, we showed
 up at less than one minute to midnight on December 31.

 (Creative Schools - On saving the Earth vs. Saving Human Life on Earth)
 #+end_quote

 #+begin_quote
There is an ever-widening skills gap between what schools are teaching
and what the economy actually needs.

The irony is that in many countries there's plenty of work to be done
but, despite the massive investments in education, too many people
don^t have the skills that are needed to do it.

Although all the rhetoric of the standards movement is about
employability, the emphasis has not been on courses that prepare
people directly for the work but on *raising standards in academic
programs*.

(Creative Schools - On a broken system based on standards and tests)
 #+end_quote

 #+begin_quote
In 2008 IBM published a survey of what characteristics organization
leaders need most in their staff. They spoke with fifteen hundred
leaders in eighty countries.

The two priorities were /adaptability to change/ and /creativity in
generating new ideas/.

They found these qualities lacking in many otherwise highly qualified
graduates.

(Creative Schools - On the lack of entrepreneurship in the education system)
 #+end_quote

 #+begin_quote
 Unsurprisingly, as Yong Zhao points out, there is an inverse
 relationship between countries that do well on standardized tests and
 those that demonstrate entrepreneurial flair.

(Creative Schools - On the lack of entrepreneurship in the education system)
 #+end_quote

 #+begin_quote
The lives we create are the result of all sorts of currents and
cross-currents, most of which we cannot anticipate in advance.

(Creative Schools - On the issue of standardizing education)
 #+end_quote

 #+begin_quote
I said earlier than to transform any situation you need three forms of
understanding: a critique of the way things are, a vision of how they
should be, and a theory of change for how to move from one to the
other.

(Creative Schools - On making changes)
 #+end_quote

 #+begin_quote
Quickly, though, humans demonstrate a power that sets us apart from
all other creatures: the power of symbolic thought, of which language
is the most obvious example.

In at least one fundamental respect, human beings are different from
the rest of life on earth: we do not live in the world directly, as
other species seem to do. Instead, we see it through frameworks of
ideas and values.

(Creative Schools - On human ways)
 #+end_quote
 
 #+begin_quote
Verbal communication is not only about literal meanings; it's also
about appreciating metaphor, analogy, allusion, and other poetic and
literary forms of language.

Communication is not only about words and numbers.  Some thoughts
can't be properly expressed in these ways at all. We also think in
sounds and images, in movement and gesture, which gives rise to our
capacities for music, visual arts, dance, and theater in all their
variations.

The ability to form and communicate our thoughts and feelings in all
these ways is fundamental to personal well-being and to collective
achievement.

(Creative Schools - On Communication; One of the eight core
competencies that schools should facilitate)
 #+end_quote



** Uno Nessuno Centomila

   On the part about the nature - [[https://annamariaromanello.wordpress.com/2017/03/26/uno-nessuno-e-centomila-di-luigi-pirandello-libro-secondo/][source]] (unfortunately I was
   listening to the audiobook and could not make notes).

       #+begin_quote
Dopo aver mostrato che l’uomo può costruire una casa, una città, ci
mostra che può aver bisogno di cercare la pace in campagna, dove la
pace esiste perché usciamo dal mondo che noi stessi abbiamo costruito:
un mondo fatto di case, di chiese e di piazze; un mondo costruito
dall’uomo e costruito” perchè non ci si vive più così per vivere, come
le piante, senza saper di vivere; bensì per qualche cosa che non c’è e
che vi mettiamo noi; per qualche cosa che dia senso e valore alla
vita; un senso, un valore che qua, almeno in parte, riuscite a
perdere, o di cui riconoscete l’affliggente vanità.” Moscarda sembra
desiderare di non aver più coscienza d’esser, come una pietra, come
una pianta!  L’uomo sa come si forma una nuvola che ignora la sua
esistenza ed è sola; ma sa l’uomo spiegare il perchè dei perchè?
Moscarda ricorda la fatica dell’ uomo; la sua pochezza di fronte
l’infinito; ricorda la vanità dei nostri affanni e mostra il contrasto
tra il volo di un semplice uccellino, che vola con ” un frullo e un
trillo” e quello dell’uomo che si alza da terra con un ” motore
strepitoso e puzzolente e la morte avanti.” Il nostro protagonista
alza la sua invettiva contro il mondo finto e meccanico” un altro
mondo nel mondo” , un mondo che ha senso e valore soltanto per l’uomo
che ne è l’artefice: Pirandello ci indica che la caduta dei valori del
suo tempo può portare alla pazzia; può portare al vaneggiare di
Moscarda che immagina di rientrare dalla campagna, camminando lungo il
Corso di Porta Vecchia, dove gli alberi, ” probabilmente”, non pensano
e le bestie non ragionano. Se potessero pensare… Chissà cosa
penserebbero degli uomini che, per godere della loro ombra, li
piantano in città. Forse… Che cosa stavano a fare lì, in mezzo a tanta
gente affaccendata! Orecchie non ne hanno, ma, forse, per crescere
hanno bisogno di silenzio, quel silenzio che c’è nella Piazzetta
dell’Olivelli, ove la terra ogni anno ne approfitta, perché crede che
lì non ci sia la città e che gli uomini se ne siano andati. Quindi,
l’erba cresce, ma per poco perchè lì, invece, è ancora città per cui
giungono gli spazzini a tagliarla, con grande meraviglia degli
uccellini che si chiedono la ragione della presenza di quegli spazzini
e scappano; non lo possono fare, invece, le bestie che tirano il carro
e, forse, tutte le creature, diverse dall’uomo, hanno un senso per sè
che l’uomo non può intendere: ci sarebbe bisogno di una maggiore
intesa tra l’ uomo e le altre creature che sembra si divertano a
mandare all’aria tutte le costruzioni umane con cicloni e
terremoti. Tuttavia, l’uomo ricostruisce, obbedendo a qualcosa,” che
non si sa cosa sia”, e trasforma la materia a modo suo, considerando
materia anche se stesso: perciò si ricostruisce come ricostruisce la
casa ed ognuno si ricostruisce in una forma che gli altri non gli
riconoscono, come ciascuno di noi non riconosce la forma con cui si
ricostruiscono gli altri; ” e la stessa cosa non è uguale per tuttie
anche per ciascuno di noi che può di continuo cangiare, e difatti
cangia di continuo e l’unica realtà è la forma momentanea che
riusciamo a dare a noi stessi, agli altri e alle cose:”la realtà di
tutti diventa quella che gli altri ci danno, ma si tratta di una
realtà valida per gli altri, non per noi: e ciò varrebbe per
tutti. Gli uomini si costruiscono come costruiscono le case, finché
dura la nostra volontà e i nostri sentimenti; quando volontà e
sentimenti vengono a mancare, ci accorgiamo delle nostre illusioni.
    #+end_quote    

 
