
#+BEGIN_COMMENT
.. title: prova latex
.. slug: prova-latex
.. date: 2019-09-22 10:43:50 UTC+02:00
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text
.. status: private
#+END_COMMENT


#+BEGIN_HTML
<br>
<br>
#+END_HTML

This is a private post where I keep a cheat sheet of working with
latex in org. 

Notice that nikola does not export proper latex chunks such as the one
below

#+BEGIN_LaTeX
\alpha * \pi *  \sum_{i}^{N}
#+END_LaTeX

It /does/ however export built in latex statements such as the
formula below:

\alpha * \pi *  \sum_{i}^{N}

Test it in the following weeks.

Like that you can write posts about your learning in statistics in
possibly a fast way.

*** Expression parsed?

Notice that org does not parse latex expression as the one above in
=verbatim=. The text in such mode is literally represented.

The same holds for example chunks as the one below.

#+begin_example
\alpha * \pi *  \sum_{i}^{N}
#+end_example

The *best solution* is therefore to write the mathematical formula on
a separate line centering that.

The below does not work cause html does not parse latex functions but
it centers the text so it potentially works with all of the other
things you are interested to center.

#+BEGIN_HTML
<p style="text-align:center;">
\alpha * \pi *  \sum_{i}^{N}
</p>
#+END_HTML

--- still need to understand how to center. In the meanwhile just
    write on a separate line.
