#+BEGIN_COMMENT
.. title: Proper REST API
.. slug: proper-rest-api
.. date: 2022-04-15 19:29:19 UTC+02:00
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT

So starting to dig a little bit deeper into the way to properly write
your APIs.

After the OpenAPI specifications and the integration with Swagger,
there is the component of hypermedia.

I like this added layer as it will allow you to very solidly program
your APIs and produce and consume them in a very programmatic way.

{{{TEASER_END}}}

In order to understand that component understand properly the three
layers of the maturity level everyone talks about.

You can check as well this project in planning mode - [[https://pypi.org/project/hypermedia/][here]]. Cool
project, it is in fact something missing in the python dev space.

* Three Layers of Maturity

  Check at the following three layers for producing and consuming
  APIs.

  Check at the following urls in order to understand it and
  understand where you are staying and the way you want to develop:

  - [[https://www.crummy.com/writing/speaking/2008-QCon/act3.html][source 1]]

  - [[https://martinfowler.com/articles/richardsonMaturityModel.html][source 2]] - essentially copy of first source

  - [[https://www.ics.uci.edu/~fielding/pubs/dissertation/top.htm][source 3]] - the real document posing a solid reference for
    web-based architectures and a must read in order to properly
    understand the logic. 

* Actually Writing them.

  So basically in spring you have an entire [[https://docs.spring.io/spring-hateoas/docs/current/reference/html/#client.traverson][hateoas suite]].

  In python you can start checking at [[https://flask-marshmallow.readthedocs.io/en/latest/][marshmallow]].

  I am starting to make some experiments in  [[https://github.com/MarcoHassan/mySpringPlayground][my helloworld example]].

  Still really in 101 phase. Will slowly progress in time as a side job.

