#+BEGIN_COMMENT
.. title: On some Accounting terms
.. slug: on-some-accounting-terms
.. date: 2022-06-03 09:31:05 UTC+02:00
.. tags: finance
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT

So this post will prove as a repository for work around accounting
terms and concepts.

Lots and part of the cake is this translation from accounting measures
to economic ones through which you manage your stuff.

The way this translation is done is important as it is quite core if
you want to get a thorough picture.

So this post contains some information in this dimension. As always
will start in a very light way and see if it grows then in time -
i.e. see if I come a lot across these concepts.

There is also all that big stuff of IFRS17 and IFRS9. Would be cool to
watch a quick video of it... take time at some point. Just to have a
high level understanding of that and what it is going on in this
sense.

This is important as, as mentioned in the RiskMetics paper:

#+begin_quote
For many institutions the bulk of activities are reported on an
accrual basis, i.e., transactions are booked at historical costs +/-
accruals.

Only a limited number of trading items are marked to market.
#+end_quote

{{{TEASER_END}}}

#+begin_export html
<style>

img {
display: block;
margin-top: 60px;
margin-bottom: 60px;
margin-left: auto;
margin-right: auto;
width: 70%;
height: 100%;
class: center;
}

.container {
position: relative;
left: 15%;
margin-top: 60px;
margin-bottom: 60px;
width: 70%;
overflow: hidden;
padding-top: 56.25%; /* 16:9 Aspect Ratio */
display:block;
overflow-y: hidden;
}

.responsive-iframe {
position: absolute;
top: 0;
left: 0;
bottom: 0;
right: 0;
width: 100%;
height: 100%;
border: none;
display:block;
overflow-y: hidden;
}
</style>
#+end_export

*** Accrual

    Accruals are revenues earned or expenses incurred which impact a
    company's net income on the income statement, although cash related
    to the transaction has not yet changed hands. Accruals also affect
    the balance sheet, as they involve non-cash assets and
    liabilities. Accrual accounts include, among many others, accounts
    payable, accounts receivable, accrued tax liabilities, and accrued
    interest earned or payable.


