#+BEGIN_COMMENT
.. title: Nice Web 2.0 Formatted Technical Documents
.. slug: nice-web-20-formatted-technical-documents
.. date: 2020-02-21 18:53:28 UTC+01:00
.. tags: emacs
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT

#+BEGIN_EXPORT html
<br>
<br>
#+END_EXPORT

The other day I randomly came across [[https://www.youtube.com/watch?v=0g9BcZvQbXU&t=192s][this nice youtube video]]. It was a
suggestion of youtube, so probably it is starting to get to know me
too well.

In any case the guy wrote a very nice =CSS= styleguide for technical
documentation that you can use when creating some technical
documentation.

You can then simply code in =orgmode= and by specifying the location
of the guy =CSS= style when exporting your org mode document into html
it will be nicely rendered and you will have then the opportunity to
nicely write your technical documentation.

{{{TEASER_END}}}

#+BEGIN_EXPORT html
<br>
#+END_EXPORT

* Set-up

In order to do this you can check out the [[https://github.com/fniessen/org-html-themes][repo]] with the specified CSS
styleguide.

You can then clone it. Then by simply inserting the following header

#+BEGIN_EXAMPLE
#+TITLE: IBM Blockchain Fabric
#+AUTHOR:    Marco Hassan 
#+DATE:      2020-02-12
#+LANGUAGE:  en
#+OPTIONS:   H:4 num:nil toc:2
#+SETUPFILE: ~/Desktop/TechnicalPosts/org-html-themes/setup/theme-readtheorg.setup

-----
#+END_EXAMPLE

specifying in the =setupfile= the path to our friend style files you
will end up exporting in the nice documentation format.

I experimented with it for a demo on Blockchain I had to recently
run. I created a github-page for this.

You can do that simply by creating a new repository in Github and by
specifying in the settings that you want the repository to act as a
Github Page. You will then be given an URL where your HTML page will
be rendered. Following this link and entering the path to the HTML
file you want to display you will see it in the nicely formatted
style.

You can have an idea of it - if I did not remove the repo yet -
following [[https://marcohassan.github.io/UnBlockDemo/DemoBlockChainKaffee.html][this link]].

/Side Note:/ I had to select a Theme and then to empty the =.yml= for
the page to be rendered. Not sure why it did not work in the first
place. Maybe I was to impatient.


