#+BEGIN_COMMENT
.. title: Sailing - on some bits of experience
.. slug: sailing-on-some-bits-of-experience
.. date: 2022-01-15 09:26:47 UTC+01:00
.. tags: sailing
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT

I still remember the time in Israel. This was the time I could sail
the best. 

I did quite some theory about the sailing physics back then and when
going 3-4h a week for 6 months... then you really start to read the
things at their best. I remember I could see if the sails were
properly set just by seeing how the wind was flowing into them. I
could read telltales and the flapping of the sails from the different
angles. 

After two years without practicing and checking at the theory
everything is gone. I noted though that in the last charter after one
week on the boat the concept were naturally coming back without even
too much of book study.

So here some notes about it - to let it stick into your mind and refresh it
from time to time.

{{{TEASER_END}}}


* On the flapping of the head-sail

  So here the concept is trivial and this is the one that will let you
  understand how to properly trim the sail and read the tell-tales.

  So if you go on clause-reach too much upwind too much wind will start
  to flow on both side of the sail. It will start flapping and the
  airfoil property with the difference in pressure that creates the
  lift will be gone.

  If you go too much down-wind the wind will not properly create the
  airfoil property as you can imagine that you can imagine that the
  wind will continue for its own direction and will not follow the
  airfoil. So it will start to be a push and not an airfoil and
  somewhere between a mix - this is why you set your sails more
  loosely... you give the wind less of a sharp curve and allow your
  sails to serve it better.

* On the tell-tales

  Once you understand the concept of the wind as per above you can
  well understand how to read the telltales.

  These are the little strips that are hanging on your head-sail.

  The concept is the following - if you are too much up-wind the
  tell-tales will start to flow up-to the sky. 

  Too much wind is flowing in and they will react by going high as the
  airfoil is not directing the wind anymore and you cannot properly
  sail.

  If you are too much downwind, then you will have less wind flowing
  on your sail. It will start to point to the boat.

  Just if it stays horizontally are you sailing in the proper
  direction to the wind. 

* On properly trimming the sails

  This leads directly to the next topic - the trimming of the sails. 

  The idea is the following - you know very well by know how much to
  trim them - just roughly so you can do it well.. Recall the idea 10
  cm from the iron thread stabilizing the main-post.

  Now - you can helm according to the tell-tails. Don't constantly
  look at the arrow up. It is too sensible. You will steer much better
  when focusing on the tell-tales bit and how the air is flowing in
  your sails. 

  You can then immediately see - am I at a decent angle with respect
  to the wind when sailing properly according to the tell-tales? If
  not you might have the option to sheet in or out.  

* TODO On the haul-speed

* On helming
  
  Recall do not move to much the helm. 


  Even with big waves that are
  quite annoying cause they cause your boat to move a lot - especially
  if they are coming at a diagonal angle as parts of your boat will
  follow it different times and so it is more difficult to find that
  perfect angle to sail to. 

  Recall that the wave effect will eventually balance out. 

  You just have to find the right angle to balance the weather
  helm. Recall as well that as much fun it is to sail with big weather
  helm it is not too good for the boat. So don't go appositely to it
  and set your steering and sails to limit it to a healthy degree.
  
* On gusts of wind

  You can see them arriving when you see waves with a bit of foam. 

* On the knots

* On the preventer

* On the thing with the post

* On the butterfly

* On the traveler

* TODO On the car-things on the side
