#+BEGIN_COMMENT
.. title: About Me
.. slug: aboutme
.. date: 2019-08-04 15:48:04 UTC+02:00
.. tags: 
.. category: 
.. link:
.. description: 
.. type: text

#+END_COMMENT



Hi you, 

I'm happy to see that you landed on my website. 

I am a young -emacs addicted- professional ready to start a career in a technological savvy organization that is ready to navigate the next decades through the power of innovation and revolutionary ideas.

My education started in the field of economics and finance; despite the mathematical elegance of the academic subjects I recently decided to abandon the idea to work in such fields due to the lack of project oriented end-to-end work and the lack of a final product and creation.

Keeping the best of my educational background I am now ready to shift my focus towards Software Engineering and the fast developing data-driven industries with the hope of making soon part of an ambitious group working towards turning revolutionary ideas into practice for the benefit of the community as a whole.



** Working Experience

- *IBM*    /Junior Software Engineer Sep 2019 -/

  Part time working student at IBM.


- *Expedia Group*    /Data Analyst Intern Jun 2019 - Aug 2019/

  Data analyst working as a Member of the Expedia Partner Solutions Analytics Team analyzing the recent developments in the B2B enterprise and templates solutions.

  ◦ Automated Monthly Performance Overview Releases through the creation of ad-hoc Tableau Dashboards.

  ◦ Developed SQL queries to answer Stakeholder Specific Questions.

  ◦ Took part on a forecasting project trying to model Account Receivables of Partners.


- *N-Frnds*    /Jun 2018 - Aug 2018/

  Business intern development for the cloud FinTech company offering banking services in rural areas where traditional business fails to arrive.

  ◦ Identified strategies to further penetrate and expand the 15 Mio. client basis in the Sub-Saharan market.

  ◦ Researched potential partnerships to realize synergies from 21 cloud SaaS patents of the company.

- *Overseas Trade Company*    /Student Assistant Jun 2015 - Jun 2018/

   Part-time assistant at the Sino-Italian gadget import-export family business.


** Education

- *Eidgenossische Technische Hochschule Zurich*   /Master of Science in Statistics Sep 2019 -/


- *University Of St. Gallen*   
  /Master of Arts in Banking and Finance Sep 2017 -2019/

  Focused on Quantitative Finance: Risk Modeling, Volatility Modeling and EVT.

- *Tel-Aviv University*    /Exchange Semester Oct 2018 - Feb 2019/

  Member of MBA class of 2018. Attended various management related courses.

  Completed courses on /Numerical Analysis/ and /Python Programming/ offered by the electrical engineering department as own initiative.

- *University of Zurich*    /Bachelor of Arts in Business and Economics Sep 2014 - Jun 2017/

  Focused on Macroeconomics and on obtaining a fertile mathematical and statistical humus. 

- *Scuola Svizzera di Milano*    /Swiss Matura Sep 2010 - Jun 2014/

  Gained a strong basis in EU most widely spoken languages (German, English, French, Italian) and fully enjoyed spending afternoons with friends.


** Tools

- Workflow: Git

- Editor: Emacs (I use it for everything -web browser, IDE, shell, Blogging, LaTeX and I am deeply in love with it)

- BI-Tools: Tableau, Omniture

- Scripting Languages: R, Python

- OO Languages: Python, C++

- Libraries: Leaflet, Ggplot, Ggmap, Urca, SQLdf, Dplyr, Tidyr, DBI, Rugarch, Partyr, Web3, Keras, Scikit-Learn, Numpy, Pandas, Tensorflow, Jupyter among the others


** Languages

   English, German, Italian, French

** Extracurricular Interests

   Sailing (recent but big passion), Rugby (something that stayed after having played 8 years) and a big AC Milan fan.



