#+BEGIN_COMMENT
.. title: Book Wisdom
.. slug: book-wisdom
.. date: 2019-06-29 21:18:08 UTC+02:00
.. tags: perRep
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT


This posts contains some quotes that I liked when reading books.

{{{TEASER_END}}}

** State at any Cost

  #+begin_quote
  True friendships are acquired only in youth, and views or ideas cannot
  harm them.

  On the contrary, the older a person gets, forces from deep within him
  take him back more and more into the world of his boyhood and youth.

  (A State at Any Cost - Reconciliation of Zemach and Ben-Gurion).
  #+end_quote

  #+begin_quote
  A man is not always rational.

  It was not a single thing that broke him in the end, but rather an
  entire range of tensions, anxieties, and people, from Lavon to
  Kennedy, from Dayan to Nasser. Take all together it was now more than
  what he could handle.

  (A State at Any Cost - Ben-Gurion motivating his last resignment). 
  #+end_quote

  #+begin_quote
  He believed that the Jewish people chose God before God chose the
  Jews.

  "You chose God for yourselves (Joshua 24:22)".

  (A State at Any Cost - Ben-Gurion about the meaning of being Jew)
  #+end_quote

  #+begin_quote
  I do not believe that God spoke... but I also do not believe that
  there are only physical forces in the world.

  There is a thing called mind, no matter how it is called, there is
  something higher than physical processes, in the entire universe.

  (A State at Any Cost - Ben-Gurion on being a different Jew)
  #+end_quote

  #+begin_quote
  The thirst to write is of inestimable power.

  (A State at Any Cost - Zemach last written words before dying)
  #+end_quote

** Creative Schools - On the need of reformation of education

 #+begin_quote
 But Revolutions don't wait for legislation. They emerge from what
 people do at the ground level.

 Education does not happen in the committee rooms f the legislatures or
 in the rhetoric of politicians.

 (Creative Schools - On the need of reformation of education)
 #+end_quote

 #+begin_quote
 It's often said that we have to save the planet. I'm not so sure. 

 If you imagine the whole history of the Earth as one year, we showed
 up at less than one minute to midnight on December 31.

 (Creative Schools - On saving the Earth vs. Saving Human Life on Earth)
 #+end_quote

 #+begin_quote
There is an ever-widening skills gap between what schools are teaching
and what the economy actually needs.

The irony is that in many countries there's plenty of work to be done
but, despite the massive investments in education, too many people
don^t have the skills that are needed to do it.

Although all the rhetoric of the standards movement is about
employability, the emphasis has not been on courses that prepare
people directly for the work but on *raising standards in academic
programs*.

(Creative Schools - On a broken system based on standards and tests)
 #+end_quote

 #+begin_quote
In 2008 IBM published a survey of what characteristics organization
leaders need most in their staff. They spoke with fifteen hundred
leaders in eighty countries.

The two priorities were /adaptability to change/ and /creativity in
generating new ideas/.

They found these qualities lacking in many otherwise highly qualified
graduates.

(Creative Schools - On the lack of entrepreneurship in the education system)
 #+end_quote

 #+begin_quote
 Unsurprisingly, as Yong Zhao points out, there is an inverse
 relationship between countries that do well on standardized tests and
 those that demonstrate entrepreneurial flair.

(Creative Schools - On the lack of entrepreneurship in the education system)
 #+end_quote

 #+begin_quote
The lives we create are the result of all sorts of currents and
cross-currents, most of which we cannot anticipate in advance.

(Creative Schools - On the issue of standardizing education)
 #+end_quote

 #+begin_quote
I said earlier than to transform any situation you need three forms of
understanding: a critique of the way things are, a vision of how they
should be, and a theory of change for how to move from one to the
other.

(Creative Schools - On making changes)
 #+end_quote

 #+begin_quote
Quickly, though, humans demonstrate a power that sets us apart from
all other creatures: the power of symbolic thought, of which language
is the most obvious example.

In at least one fundamental respect, human beings are different from
the rest of life on earth: we do not live in the world directly, as
other species seem to do. Instead, we see it through frameworks of
ideas and values.

(Creative Schools - On human ways)
 #+end_quote
 
 #+begin_quote
Verbal communication is not only about literal meanings; it's also
about appreciating metaphor, analogy, allusion, and other poetic and
literary forms of language.

Communication is not only about words and numbers.  Some thoughts
can't be properly expressed in these ways at all. We also think in
sounds and images, in movement and gesture, which gives rise to our
capacities for music, visual arts, dance, and theater in all their
variations.

The ability to form and communicate our thoughts and feelings in all
these ways is fundamental to personal well-being and to collective
achievement.

(Creative Schools - On Communication; One of the eight core
competencies that schools should facilitate)
 #+end_quote




 
