#+BEGIN_COMMENT
.. title: Grenada
.. slug: grenada
.. date: 2022-01-01 02:09:20 UTC+01:00
.. tags: perRep, travel
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT


#+begin_export html
<style>
img {
display: block;
margin-top: 60px;
margin-bottom: 60px;
margin-left: auto;
margin-right: auto;
width: 70%;
height: 100%;
class: center;
}

.container {
  position: relative;
  left: 15%;
  margin-top: 60px;
  margin-bottom: 60px;
  width: 70%;
  overflow: hidden;
  padding-top: 56.25%; /* 16:9 Aspect Ratio */
  display:block;
  overflow-y: hidden;
}

.responsive-iframe {
  position: absolute;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  width: 100%;
  height: 100%;
  border: none;
  display:block;
  overflow-y: hidden;
}
</style>


<style>
 {
  box-sizing: border-box;
  margin-top: 60px;
  margin-bottom: 60px;
}

.column {
  float: left;
  width: 50%;
  padding: 0px;
}

/* Clearfix (clear floats) */
.row::after {
  content: "";
  clear: both;
  display: table;
}
</style>

#+end_export

This posts holds some memory of my time in Grenada.

First time in the Caribbean. 

Did 7 days of sailing followed by 5 days on Grenada Island. 

The sailing bit was more dynamic. The piece on the island was mainly
beach, reading and gathering of thoughts. I would like to say relaxing
but that was not it. 

It was part of my solo trip and I must admit that I am not good at
relaxing when I am by myself. I always have something on my mind and
I think I need to be around people to properly relax, which is
strange. 

{{{TEASER_END}}}

* On a general impression

  As was the case for the New York bit of the trip I will structure
  this post in a similar way. 

  I will keep some notes here about the general impression and
  memories of the island. 

  I will then create some parts where I will put some picture and
  organize the memories. 

  So talking about the general impression let's start with the sailing
  part. 

  And here what should I say. Fantastic there are amazing places on
  this world I and really love to explore them and see them on a
  boat. 

  I will not go in the detail of my sailing learning and impression as I
  will write a specific post for it. I want to note here though that
  it was a quite different experience in comparison to my last one. I
  am not sure if the boat was more comfortable - it surely was. Wider
  etc. or if it was due to the structure of one charter vs. the other
  but this one was feeling much more comfortable. I recall that the
  mindset during the other - more intense more miles in 1/3 of the
  time - was slowly changing at the end. I was feeling more as a
  seaman. This time was also quite a bit about enjoying the places -
  around 30 miles per day - and I must say that this type of charting
  is quite for anyone and you might even do it with your more
  well-habit / more city type friends.

  On the note of people you met. It was nice to meet Alex. Very well
  seasoned sailor and it was nice to see how different the life of
  different human beings can be. I noted we lived in complete
  different universes. 

  He decided to frame his life around sailing. Live in contact with
  nature. Sail, travel and experience the world. Settle down in
  Grenada, create a family there with local people and integrate in a
  complete different reality. 

  I was also happy to meet Stewart a seasoned fisherman I had the
  pleasure to fish with. He is a gentleman - in the true spirit of the
  word - it's fun how fast you can tell actually. He is another person
  that decided to leave the western society as you know it to live in
  these natural paradises. First in Kenya and then when the tension
  was too high he decided to move to Grenada. He never made big money
  and he seemed to be struggling a bit because of that but
  he seemed to be fine with it making even some humor about it. He was also in a personal
  struggle when I met him as he just lost his life-partner over
  covid. Wish you good luck Stewart - you left a very nice impression
  on me. 

  Anyways, there is no such strong push for making a big career there. This is
  the curse and benediction of the western society. What pushes our
  western countries to their greatness and to their ruin - you can
  well see it in the U.S.A. where you have just been before. 

  When being on the island and around I was often recalling Charlie
  Chaplin and his famous speech in /the great dictator/: "and a good
  earth is rich, and has provided for everyone". Well it's funny that
  you get that feeling on an island that is GDP-measured much poorer
  than our western societies. 

  But I think this was not simply an impression but rather a matter of
  fact. There is pressure on these people; that is for sure. They also
  have to make their own living and like every other people I am sure
  they dream of being a great nation, more developed, more luxury,
  more comfort etc. But I think that despite it they are living a
  great life, the contact with nature puts the spirit at
  rest. Grenadians are possibly the most friendly people I ever
  met. Very open, talkative and nice. Always with a smile on their
  face and in laughter mood - and this one believe me is a great bit. 

  You felt safe even walking in the darkest hour alone in the streets
  being clearly the "western guy". 

  Anyways, that is mostly it. Regarding the second part of
  trip... nothing more to add as I see that I touched already many of
  the main points in the discussion above.

  The only thing I can add is maybe that I did expect it to be much
  more developed in terms of resorts, touristic infrastructure,
  restaurants etc. It was not and I was happy of the fact. 

* Memories
  
** On the memory of the Ant's chart

   The boat:

#+begin_export html
<img src="../../images/BoatName.HEIC" class="center">
#+end_export

   And the first feeling when sailing off direction Carriacou:

#+begin_export html
<div class="row">
  <div class="column">
    <img style="width:100%" src="../../images/SailOff1.HEIC">
  </div>
  <div class="column">
    <img style="width:100%" src="../../images/SailOff2.HEIC">
  </div>
</div>
#+End_export
   
** On an Ant's memory of the morning chartering

   Root planning, streams calculation, wind check

#+begin_export html
<div class="row">
  <div class="column">
    <img style="width:100%" src="../../images/MorningCharting.HEIC">
  </div>
  <div class="column">
    <img style="width:100%" src="../../images/MorningChartering1.HEIC">
  </div>
</div>
#+End_export

** On an Ant's memory of British vibes

   A must: the white tea break with these marvelous biscuits.

#+begin_export html
<div class="row">
  <div class="column">
    <img style="width:100%" src="../../images/EnglishVibes1.HEIC">
  </div>
  <div class="column">
    <img style="width:100%" src="../../images/EnglishVibes2.HEIC">
  </div>
</div>
#+End_export

** On an Ant's in Tyrill Bay

   First night in Carriacou and already loving the Grenadines

#+begin_export html
<div class="row">
  <div class="column">
    <img style="width:100%" src="../../images/TyrillBay1.HEIC">
  </div>
  <div class="column">
    <img style="width:100%" src="../../images/TyrillBay2.HEIC">
  </div>
  <div class="column">
    <img style="width:100%" src="../../images/TyrillBay3.HEIC">
  </div>
</div>
#+End_export

   Yeah-ehh we wept when remembering Zion:

#+BEGIN_EXPORT html
<video controls="controls" width="70%" height="100%" 
       src="../../videos/TyrrilBayVideo.MOV" class="center"></video>
#+END_EXPORT

   
** On an Ant memory of Tobago Cays

   That was for sure the highlight of the sailing. Wonderful
   staying. Beautiful sea, great eating.

   Did even manage to see a big turtle and a Ray.

#+begin_export html
<div class="row">
  <div class="column">
    <img style="width:100%" src="../../images/TobagoCays1.HEIC">
  </div>
  <div class="column">
    <img style="width:100%" src="../../images/TobagoCays2.HEIC">
  </div>
</div>
#+End_export

#+begin_export html
<div class="row">
  <div class="column">
    <img style="width:100%" src="../../images/TyrillBay3.HEIC">
  </div>
  <div class="column">
    <img style="width:100%" src="../../images/TyrillBay4.HEIC">
  </div>
</div>
#+End_export

#+begin_export html
<div class="row">
  <div class="column">
    <img style="width:100%" src="../../images/TyrillBay5.HEIC">
  </div>
  <div class="column">
    <img style="width:100%" src="../../images/TyrillBay6.HEIC">
  </div>
</div>
#+End_export

#+begin_export html
<div class="row">
  <div class="column">
    <img style="width:100%" src="../../images/TyrillBay8.HEIC">
  </div>
  <div class="column">
    <img style="width:100%" src="../../images/TyrillBay9.HEIC">
  </div>
</div>
#+End_export

** On an Ant's third night

   Do not recall the name of the bay. Would have to check in my
   sailing log-book. 

   What I do remember is a stunning sunset and the beauty of seeing
   then the moon and the orange that stays shortly after the sunset;
   together, in a single frame.

#+begin_export html
<div class="row">
  <div class="column">
    <img style="width:100%" src="../../images/ThirdNight.HEIC">
  </div>
  <div class="column">
    <img style="width:100%" src="../../images/ThirdNight2.HEIC">
  </div>
</div>
#+End_export

#+begin_export html
<div class="row">
  <div class="column">
    <img style="width:100%" src="../../images/ThirdNight3.HEIC">
  </div>
  <div class="column">
    <img style="width:100%" src="../../images/ThirdNight4.HEIC">
  </div>
  <div class="column">
    <img style="width:100%" src="../../images/TyrillBay5.HEIC">
  </div>
</div>
#+End_export

** On an Ant in Petite Martinique   

   Very nice, with that hike to mount Python where it seemed to be in
   eden or in the /campi risi/.

#+begin_export html
<div class="row">
  <div class="column">
    <img style="width:100%" src="../../images/PetiteMartinique1.HEIC">
  </div>
  <div class="column">
    <img style="width:100%" src="../../images/PetiteMartinique2.HEIC">
  </div>
</div>
#+End_export

#+begin_export html
<div class="row">
  <div class="column">
    <img style="width:100%" src="../../images/PetiteMartinique3.HEIC">
  </div>
  <div class="column">
    <img style="width:100%" src="../../images/PetiteMartinique4.HEIC">
  </div>
</div>
#+End_export

#+begin_export html
<div class="row">
  <div class="column">
    <img style="width:100%" src="../../images/PetiteMartinique5.HEIC">
  </div>
  <div class="column">
    <img style="width:100%" src="../../images/PetiteMartinique6.HEIC">
  </div>
</div>
#+End_export

#+begin_export html
<div class="row">
  <div class="column">
    <img style="width:100%" src="../../images/PetiteMartinique7.HEIC">
  </div>
  <div class="column">
    <img style="width:100%" src="../../images/PetiteMartinique8.HEIC">
  </div>
</div>
#+End_export
   
** On a stop on Sandy Island

   What a beauty these small sandy limbs of ground that you can just
   reach by boat.

#+begin_export html
<div class="row">
  <div class="column">
    <img style="width:100%" src="../../images/TrueSandy1.HEIC">
  </div>
  <div class="column">
    <img style="width:100%" src="../../images/TrueSandy2.HEIC">
  </div>
</div>
#+End_export


** On an Ant's in St. Georges

   Enriching stop in St. Georges. Beautiful to wander around and see
   the city.

#+begin_export html
<div class="row">
  <div class="column">
    <img style="width:100%" src="../../images/StGeorge1.HEIC">
  </div>
  <div class="column">
    <img style="width:100%" src="../../images/StGeorge2.HEIC">
  </div>
</div>
#+End_export

#+begin_export html
<div class="row">
  <div class="column">
    <img style="width:100%" src="../../images/StGeorge3.HEIC">
  </div>
  <div class="column">
    <img style="width:100%" src="../../images/StGeorge4.HEIC">
  </div>
  <div class="column">
    <img style="width:100%" src="../../images/StGeorge5.HEIC">
  </div>
</div>
#+End_export
   

** On an Ant's fishing and fighting with Barracudas

#+begin_export html
<div class="row">
  <div class="column">
    <img style="width:100%" src="../../images/Fishing1.HEIC">
  </div>
  <div class="column">
    <img style="width:100%" src="../../images/Fishing2.HEIC">
  </div>
</div>
#+End_export

#+begin_export html
<div class="row">
  <div class="column">
    <img style="width:100%" src="../../images/Fishing3.HEIC">
  </div>
  <div class="column">
    <img style="width:100%" src="../../images/Fishing4.HEIC">
  </div>
</div>
#+End_export


** TODO On an Ant enjoying some beach time





