#+BEGIN_COMMENT
.. title: IBM Cloud Commands
.. slug: ibm-cloud-commands
.. date: 2020-02-05 13:09:09 UTC+01:00
.. tags: IBM Cloud Services
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT

#+BEGIN_EXPORT html
<br>
<br>
#+END_EXPORT

This post contains the major IBM cloud CLI commands to operate with
some of the data services in the cloud. 

It especially focus around DaaS and MLaaS. 

{{{TEASER_END}}}

#+BEGIN_EXPORT html
<br>
#+END_EXPORT

* Look at the ibmcloud connection set-ups

#+BEGIN_SRC sh :results output
## to check at general access configuration on IBM cloud
bx target

## to look at general macro characteristics of your account
ibmcloud account show
#+END_SRC

Important is that you might have different resources bounded to
different data centers in different regions.

When using a service from the =ibmcloud CLI= it is important that you
make sure you are in the region where the resources and services are
deployed.

To change region you can make use of the following command

#+BEGIN_SRC sh
#ibmcloud target -r <region-name>
ibmcloud target -r eu-de
#+END_SRC

Important is that if you need to change target account you can do so
by adding the =-c= flag and pointing to your account.

#+BEGIN_SRC sh
## ibmcloud login --sso -c #accountID 0xxxxxx...
#+END_SRC


* Cloud Foundry

This allows to easily create and deploy cloud-native apps. 

The first step in order to interact with your Cloud Foundry App and to
deploy your local code on the cloud is to configure your =ibm CLI= to
operate directly on the chosen CloudFoundry Organization where your
team will deploy the app.

In order to do that once you are in the proper region where your Cloud
Foundry Organization is configured you can specify the Cloud Foundry
organization you aim to interact with by running

#+BEGIN_SRC sh
ibmcloud target --cf
#+END_SRC
 
This will give you the possibility to interactively choose your
CloudFoundry organization and space.

An alternative is to set them separately by running

#+BEGIN_SRC sh
ibmcloud target -o myOrganization
ibmcloud target -s myspace
#+END_SRC

Once the IBM cloud is properly connected with your CloudFoundry
Organization it is possible to push your application via the following
commands.

#+BEGIN_SRC sh
#ibmcloud cf push <app-name specified in the manifest file>
ibmcloud cf push myapp
#+END_SRC

If successful you should be able then to see the running application
by running.

#+BEGIN_SRC sh :exports both
ibmcloud cf apps 
#+END_SRC

#+RESULTS:
| Invoking | 'cf       | apps'... |           |           |      |       |         |    |                         |
|          |           |          |           |           |      |       |         |    |                         |
| Getting  | apps      | in       | org       | myFirsOrg | /    | space | develop | as | marco.hassan@ibm.com... |
| OK       |           |          |           |           |      |       |         |    |                         |
|          |           |          |           |           |      |       |         |    |                         |
| name     | requested | state    | instances | memory    | disk | urls  |         |    |                         |
| minimal  | started   | 1/1      | 64M       | 1G        | xxx  |       |         |    |                         |
| nluApp   | stopped   | 0/1      | 256M      | 1G        | xxx  |       |         |    |                         |

Above you can see I have a minimal python application running as well
as a stopped NLU application.

You can find the specifics of how to set up a python application by
reading [[https://docs.cloudfoundry.org/buildpacks/python/index.html][this]] cloud foundry official documentation. A thing that caused
my some trouble the first time when deploying is that your Flask
application should be set to listen on =PORT=8080=. This is because
the Python buildpacks expects your Python Application to listen to
this port.

Important is moreover to specify all the necessary libraries your
application will need in order to run in a =requirement.txt= file as
well as the command that needs to be run in a =PROCFILE=. Finally you
can specify the runtime version in the =runtime.txt= file. A manifest
file should finally specify the memory and application name as well as
the route and further parameters.

Notice that a handy way to enter the required packages is to make use
of the ~pip3 freeze~ command. This will return the installed packages
on your virtual environment and you can copy these in your
=requirement.txt=. 

Finally you can find a good overview with all the possible parameters to specify
when setting up your CloudFoundry app at the [[https://v3-apidocs.cloudfoundry.org/version/3.78.0/index.html#the-app-manifest-specification][following link]].

* Interact with Watson ML 

You can change your IBM cloud region by setting

#+BEGIN_SRC sh
ibmcloud target -r us-south

## notice that depending on the region you might have different deployments. 
## deployments live in ibm datacenters and are hence bounded regionally.

## you can list your IBM Machine Learning Deployments using:

bx ml list instances

## In general bx ml is associated with CLI interaction with Watson
## Machine learning services.

## use the --help option whenever you are lost in the CLI 
#+END_SRC 

Notice that just because you have an existing instance ID it does not
mean that it is already set on your ibmcloud CLI. In order to set it
accordingly you have to specify it accordingly 

#+begin_src sh
bx ml set instance <instance-id>
#+end_src


* Object Storage

To interact with object storage instances via CLI you must be sure the
plug-in is installed.

#+BEGIN_SRC sh
ibmcloud plugin install cloud-object-storage
#+END_SRC

Once it is downloaded you will have to specify the way you want to interact with your Object Storage.

One way to do that is to specify your HMAC credentials to your Object Storage instance

#+BEGIN_SRC sh
 ibmcloud cos config hmac
#+END_SRC

Once entered the necessary /aki key/ and /secret access key/ you will
be able to access all of yours different buckets.

#+begin_src sh
ibmcloud cos list-buckets
#+end_src

For using the IAM authentification it is moreover possible to specify the

#+begin_src sh
 ibmcloud cos config crn
#+end_src

And enter the /resource_instance_id/ of the cloud object storage instance available in the cloud credentials. 


* Cloudant

