#+BEGIN_COMMENT
.. title: Music that Touched Me
.. slug: music-that-touched-me
.. date: 2019-07-03 14:41:27 UTC+02:00
.. tags: perRep
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT


I will start a compilation of music that touched me and that evoked
something in me.

It is again intended as a repository that will develop in time. Maybe
one day when I will be old and will have many empty days to fill up -
I will come back to this repo and listen to this music and I will see
what it will evoke in me.

Let's start without a fix date and let's see how often I add pieces
and I will adjust then the speed. I listen to a lot of music so I do
not want this repo to grow very fast in an undirected way. Scarcity
makes the experience better, so you will likely have to put some
constrains once you understand how much you publish.

{{{TEASER_END}}}


* 03/07/2021

  - [[https://www.youtube.com/watch?v=Nh1NlXky9D0][Old Friend - Agus & Julia Stone]] : very peaceful song. You can find
    the calm and peace when listening to this song. Everything slowly
    fades away and you feel like a little dot that tries hard to get
    to something big while in reality our experience as human beings
    on earth is much more represented by calm quite moment where we
    can transcend daily routine and get to this deeper level. 


