#+BEGIN_COMMENT
.. title: On We Are on a Break
.. slug: on-we-are-on-a-break
.. date: 1970-02-22 10:34:14 UTC+01:00
.. tags: step down - step up 
.. category: 
.. link: 
.. description: 
.. type: text
.. status: private
#+END_COMMENT

Gosh. That kicked me. Out of a blue sky. There were issues but I
thought the relation was strong and that everything would be faced in
a mature way. Through discussion, through a fight, through a
commitment. 

{{{TEASER_END}}}

* Day 1

So story of my life, after 3 years and something of relationship, I
was told these magic 6 words by my girlfriend.

I was surprised. A lot surprised. We have a long distance
relationship. To be honest I do not believe in these break and reflect
stories. It means the story is already over.

She told me the 21/02/2021, by phone. Stressing her love. Saying it is
for the best. Saying goodbye amorino at the end. I refused that
sentence. Both at the phone and in myself. That is not how you
act. Really? On the phone.

The truth is also that I was pushing her to commit to put the
relationship over the individual work achievements. I will do that in
my life no matter what. So I was ready to do that as of now. She
probably thinks differently. She is very ambitious and that was
probably too much for her.

Some say I am a kid and it is not normal to commit to the other over
the job from such a young age. But really? If you don't do it now,
then when? When responsabilties will augment? I do not believe that
kind of narrative. If you follow a line you follow it from the
beginning. Plus we were just discussing on committing on a city. I am
sure that life is complex, and if you adapt, put good effort and you
are good, you will do well no matter what. So I really do not
understand when people act in an opportunistic way. They are probably
just scared and not confident enough in their capabilities. I do not
think that it is the case of her. She is not the type. There might be
some aspect of work relating to this though. Plus in any case I am
convinced that we both did work too much recently.

Well, now I do not know if that is what is in her head. In fact,
unfortunately I do not know at all what is in her head. She just told
me at the phone in 5 min. And me, I was too surprised to get this news
and in such a method. I could not start a conversation. A serious one
asking what was wrong. We had met the weekend before. If she wanted to
face things we could have done it then.

Anyways, she promised a letter. I guess that there, there will be more
motivations. I will then wait for this and see. In any case I really
think that our relationship is on the ground. I do not see it as a
true possibility to gain it back. Also trust. Yesterday night, in the
first night; I was so tempted to say screw you. It's over; I will not
wait here like a sentenced to death person. If there are issues let's
face them and solve them otherwise let's let each other go, no matter
how difficult that is.

I resisted. I controlled myself. I decided to wait until the
letter. Let's see what will come then.

In any case the emotion of this first day is the following: *anger*. I
am happy though that I could control it that far. Did not text her so
far. And committed to wait and give it a try. Let's see how it will
develop in the next couple of days.


*True Starting Date:* 22/02/2021
