#+BEGIN_COMMENT
.. title: A personal Repo - Movies, Art and Things to Do
.. slug: things-to-do-in-zh
.. date: 2016-08-28 16:41:37 UTC+02:00
.. tags: perRep
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT

#+BEGIN_EXPORT html
<br>
<br>
#+END_EXPORT

This is a personal post where I keep some personal activities/places I
am aim to visit at some point.

I am further structuring this post. I am adding a movie
section. Moreover, I will start to briefly write some memories and
personal thoughts for the completed activities.

{{{TEASER_END}}}

* Movies

** Watched

  - Pinocchio (Begnigni version and Del Toro version)

    --> update

  - Lion King 2 (Disney)

  - Atlantis (Diseny)

  - [[https://en.wikipedia.org/wiki/After_Life_(TV_series)][After Life]] (2019 - ):

    This is a Netflix series.

    Outstanding. I really like it. It teaches you to put things in
    perspective. The thing that you should be better able to deal
    with.

    It teaches you the importance of a full life. It teaches you the
    importance of the little things that you often forget in the life
    that you are living.

    It teaches you how hard life can hit. It teaches you to never
    surrender. To stay strong.

    It teaches you not to judge people by their status.

    On the top of it, it has a lot of humour such that it is greatly
    recommended. 

  - [[https://en.wikipedia.org/wiki/Tick,_Tick..._Boom!_(film)][Tick tick... Boom]] (2021):

    Nice movie because of the story. Also nice to see New York and be
    able to recognize all of the places. 

    It is as well possible to better understand what Broadway truly
    is. Maybe in this sense I did the wrong decision in going to watch
    one of the big classic. Next time I should rather go and watch
    something more modern and even an off-broadway one. 

    I think the music was not that great. The musical component in the
    way it was framed does give a light touch to the tragedy of the
    movie. I think that something in the process gets lost though. It
    could have been a more intense movie looking at the story without
    having much clue on the underlying character. 

    Maybe it was best depicted as that but this just people with a
    bigger knowledge of the person and events than me can say.

  - [[https://en.wikipedia.org/wiki/The_Hand_of_God_(film)][E stata la mano di Dio]] (2021):

    Another great movie of Paolo Sorrentino. After /La grande
    bellezza/ he hit the target again.

    A different movie. Less poetic. Less vanity. More sorrow.

    I think the movie is beautiful as is his message. Not clear, not
    straight, obscure as often in his movies.

    Everyone is free to interpret it his way. I like to think that the
    message of the movie is all in the 2 minutes when he talks with
    the movie director.

    For 90 min. Sorrentino shows us the /lousy world/. The one that we
    always have - one way or the other - to face and swollow.

    And then suddenly, that 5 min. talking. That message:

    do not break down.

    do not loose your integrity.

    do not come undone.

    that /"non ti disunire"/.
   
  - [[https://zff.com/en/archive/85998/][All these Sons]] (2021):

    Very beautiful, went there with friends at the zurich film
    festival. 

    It was beautiful cause even two protagonists of the movie were
    present after the movie for a Q&A session.

    Incredible what is still happening in 21st century. Every time you
    think that racial issues are over. But than badaboom. You
    understand that you live in a bubble. That realities very far from
    your own one exists. Rough realities, were that some sporadic
    heros try to make better.

    Also interesting how they approach everything as a fight of will
    and how they simply push the young people to look at themselves
    differently. All the rest will follow. A rethoric I highly agree
    with, as I think that things are not difficult to do. Everything
    is a matter of will; it's just that finding the will and the
    motivation for doing things in a difficult world like ours is not
    always that easy.

  - [[https://www.youtube.com/watch?v=0hF5HnVdIqI][Rue 8 de l'Humanite]] (2021):

    Alors, très jolie le film.

    Très amusant - il respect la traditionne de le cinèma fracaise.

    Quand je l'avais regarde, j'ai eu un coup. Il n'est pas possible
    que on avait vraimont vécu cette historie.

    Ancor plus amusant était le fait que le même jour que j'avais regarde
    le film avec mes pensées délirantes - j'avais mon premiers
    symptômes du coronavirus. J'ai été testé positif le lendemain.

    Encroyable... 

  - [[https://en.wikipedia.org/wiki/Shtisel][Shtisel]] (2021):

    I was home over Easter. I watched with the family the third
    season. Very nice series. Much better than [[https://de.wikipedia.org/wiki/Unorthodox_(Miniserie)][unorthodox]]. There
    everything was a little bit too much exasperated.

    This is nice. I would say it's kosher. It well summarizes the
    Jewish mentality with all its pro and cons.
    
  - [[https://www.youtube.com/watch?v=aKtvrvZC8OY][Il mondo che vorrei]] (2021):

    This was an interview with [[https://it.wikipedia.org/wiki/Papa_Francesco][Pope Francesco I]]. It was a good
    watch. In a rough world that is hard to navigate is always good to
    listen to such people reminding the true christian values on which
    the western society build on. These are not values augmenting the
    individualism but rather stressing the importance of the community
    that we must protect and remind us.

    The message was centered about fostering a culture of /us/ in
    contrast to an /egocentric/ view, in promoting a culture where we
    have [[https://www.youtube.com/watch?v=fhVsgxlYsEA][empathy]] and care for the others. In refusing a culture of
    waste, where if we do not like something, if something creates a
    problem or if something/someone does not fit, well we throw it
    away, be it a human being or a thing, instead of trying to solve
    the problem with it.

    Good fellow as always Pope Francesco, may he stay healthy.

  - [[https://www.youtube.com/watch?v=BHi-a1n8t7M][Marriage Story]] (2020):

    Another wow movie. You should remember this when marrying. It
    describes in a terrific way how things can go wrong for little
    reasons. I mean simply time and divergence of opinions. Things
    that you can hardly predict in advance. And still there is love
    but auto-destruction kicks in and there is nothing you can do
    while you are absorbed by spiral. 

  - [[https://en.wikipedia.org/wiki/Rose_Island_(film)][L'isola delle rose]] (2020):

    Wow! What an incredible story. I love it. It is a daydreamer story
    like me. Makes well the point of the italian genius. It lives in a
    different dimension. We idealist animals...

  - [[https://www.youtube.com/watch?v=En1jkf34xjc][La vita davanti a sé]] (2020):

    Very good movie. Strong like Momo. It is a very mixed movie. It
    encompasses many feelings and it is much food for thoughts. There
    is not a bottom line to it and it is not a light watch where there
    not need to be a bottom line. 

    It is difficult to write a snippet summarizing it. I liked it. One
    of the things I liked was the power of Momo. I guess that a key in
    the movie is how the energy of such people when channeled in the
    right will make them shine. The weird element of the lion in the
    movie goes in this direction. There is a lion / fire in some
    people and it can turn to very good or bad outcomes depending on
    who is there in the path of such people - be it Madame Rosa or the
    other guy.

    Interesting is also to notice that not the spoiled child, but
    rather the suffered one will have the fire. Help such people and
    let them shine.

  - [[https://www.youtube.com/watch?v=SMuQfYdgWxw][Sorelle Macaluso]] (2020):

    Wow wow wow!!! There are film directors that do movies. They stay in
    the daily life of each of us and touch daily topics. Mundane - I
    think this is the word.

    This transcends everything. What a beautiful mind the one of the
    movie director. To get the gravity of the life and what each one
    of us needs to face in our life and bring it on the big screen in
    such a way is simply... wow. And the lyrics that goes along the
    movie. It's liberty music. Despite the hard life we are able to
    face it and go on with such a power. Crazy movie. Possibly one of
    the best, if not the best I ever saw.

    And I usually do not touch or go along the female vs male story. I
    do not like dichotomies. But damn it you feel the touch of a
    female soul in the movie. And if this is what we missed, give way
    to the woman on the big screen.

  - [[https://en.wikipedia.org/wiki/Marriage_Story][Marriage Story]] (2019):

    Beautiful movie. I like it cause it treats the drama of the end of
    a love story in a realistic way.

    Too often people want to set reasons in cases where no reason
    exists. The beauty of the movie lies here. It shows how love
    between people can end because of divergence of opinion and how if
    not faced in the correct way can be extremely disruptive.

    It points out to the importance of being mature and to let things
    go the way they are. 

  - [[https://www.youtube.com/watch?v=RUOH8_HYDtA][Cyrano mon Amour]] (2019):

    Good movie. Confirms my personal opinion about French movies:
    these are generally the best movies when you look for a light but
    tasty watch. The key of the French majesty of movies production is
    to bring deep stories in a light way to the viewer while keeping
    the importance of the message in the movie.

    Here and there this specific movie falls into some mainstream,
    which might hurt some more sophisticated viewer but generally a
    good watch that underlines how sometimes the best in life does not
    come by following rigid structures. 

    Have to watch the Cyrano at some Opernhaus at some point now..

    Also interesting is that now you can understand better [[https://www.youtube.com/watch?v=T_wnAnIM3cw][the song of
    Guccini]]. I understood the power of the text but some links where
    missing and now it clicked.

  - [[https://www.youtube.com/watch?v=5UijUOy0MmE][The Spy]] (2019):

    Another interesting story that is Israeli-related.

    Another interesting testimony of the effort of the Israeli society
    and its people in order to keep the Israeli dream alive.

    Unfortunately, other blood that flew - todah Eliyahu Ben-Shaul
    Cohen.

  - [[https://it.wikipedia.org/wiki/Old_Man_%26_the_Gun][The Old Man & The Gun]] (2018):

    Nice movie and watch. It teaches the importance of elegance and
    style in life. That demeanor that everyone wants to have but just
    a few achieve. It is funny as basically in the plot the demeanor
    of the person completely excuses his acts. You and everyone in the
    movie sympathize with him.

    Just a pity for the end. He did not reach maturity and it lives
    you with the doubt that guy was just a psycho. But maybe it was
    just in his style and that is the beauty of it. Throwing
    everything away to save this little but important thing of
    yours.


  - [[https://www.youtube.com/watch?v=QkZxoko_HC0][Green Book]] (2018):

    Very nice movie. It shows how narrow minded people can easily
    be.. Talking and acting just based on habits and norms without
    questioning the system and going further. There is a convenience
    in doing that, which is undeniable. Best things happen though if
    you managed to transcend it.

    Also very important the motive of dignity in Doc. Shirely.

    I liked a lot in this sense the quote

    #+begin_quote
    You Never Win With Violence. You Only Win When You Maintain Your Dignity.
    #+end_quote

    beautiful idea and yet so difficult to maintain.

  - [[https://www.youtube.com/watch?v=CGzKnyhYDQI][Loving Vincent]] (2017):

    Nice movie. It is kind of a thriller. Recommended watch, just
    because of the particular painting style it is recommended.

    It is also a nice watch in the sense that you get easily
    transported. 

    Interesting way to talk about Van Gogh in this particular indirect
    way. I think at the end they well manage to give a picture of him.

  - [[https://en.wikipedia.org/wiki/Il_a_d%C3%A9j%C3%A0_tes_yeux][Il a déjà tes yeux]] (2017):

    Very nice movie. Extremely funny. I love Manu. But also serious in
    the topic. Without ever being too heavy. Very recommended.

  - [[https://www.youtube.com/watch?v=MYzFieit8dI][Mayerowitz Stories]] (2017):

    Well, there are many movies. Some are different. This is one of
    these. Some movies you know from the very beginning what it is
    gonna come. This not. It evolves and evolves and evolves and then
    it finishes.

    It's a nice family story.

  - [[https://www.youtube.com/watch?v=NRADS6wT3nc][Bienvenue à Marly-Gomont]] (2016):

    It talks about a nice story. It is a story about
    integration. Again a typical french comedy. Sometimes fun,
    sometimes serious and in general a very pleasant and constructive
    watch.

    The message of the story is the usual. But it is always good to
    watch one more movie making the point. Myself as emigrant know
    the point. Every time when moving out and entering a new
    community you will face opposition. Don't think it is personal it
    is just how the world spins. And if you are bright enough then you
    will have the courage and the duty to oppose such mechanism and
    promote different outcomes like the one in the movie. 

  - [[https://www.youtube.com/watch?v=dKYaEPdcV1g&t=3s][War Dogs]] (2016):

    Dark comedy crime movie. Interesting cause it is based on a true
    story. I generally do not like such kind of movies as they make
    the watcher sympathize on bad behaviour by making it /hollywood
    cool/. At the end you enjoy watching it but it is a double edge
    sword for the reasons above. If you read it by taking a step back,
    there is a learning also in such movie in how even an apparently
    good soul as David gets easily tricked by the moment and takes up
    bad habits. We all had that kind of Efraim friend.

    So bottom line always remember that you are walking on thin ice
    and it is easy to get out of track. Keep faith and stay solid on
    good values.

  - [[https://en.wikipedia.org/wiki/Whiplash_(2014_film)][Whiplash]] (2014):

    This is a movie that I watched on some plane when traveling
    somewhere. Looking at the date it went out, it was probably during my first
    travel to the United States when I visited the west coast.

    Strange animal the memory. Out of the blue. In 2022 during my solo
    travel - after sailing, at the time of Grenada when I had quite some spare time -
    I had suddenly to watch this movie again. So this says a lot about
    the power of this movie and how much it sticks around inside a
    person. 

    So turning to a brief comment of it as usual. 

    Nice movie. Clear plot and lots of tension. 

    The general question that remains open at the end is the
    following: 

    Is Fletcher behaviour justifiable? Does it makes sense the way he
    thinks and behaves? 

    And on the top of it - is Neiman intelligent? Or let's rather use
    a more appropriate word instead of the much abused /intelligent/
    one: /stable/. 

    Is Neiman stable enough to be with a character like Fletcher? Does
    Fletcher have enough empathy to set the proper limits when pursuing
    his story-line?

    I think this is the correct line of reasoning. I personally like
    people that push. I try to push myself. So essentially I do not
    condemn Fletcher idea. But I also believe in emotional
    intelligence and that humans have to be /good/ 
    to the core. None of this was shown by Fletcher. This is the
    /tragedy/ of the movie. A /fragile/ kid in the hands of a person
    just focused in the pursuit of his goal that does not take the human
    side into account. 

    I also like to read the comment on youtube to see what people
    [[https://www.youtube.com/watch?v=ZZY-Ytrw2co][think]]. Very interesting the debate around the final. Is it a
    tragedy? Is it a victory? 

    People even start to talk about hedonism. Much fun to see the
    philosopher come out.

  - [[https://www.youtube.com/watch?v=4RI0QvaGoiI][Notting Hill]] (1999):

    Nice movie. With the magic British touch. I think that even more
    interesting than the classical love story of the movie is the
    friendship among the librarian's group of friends.

    It was so sincere with that British humor. I think that this is
    one of the greatest strength of the brits people. They are not
    picky and can see tragedies with different lenses.

    I would sign a paper to be able to make such jokes and laugh with
    my dearest friends when life will make me feel miserable. 
  
  - [[https://www.youtube.com/watch?v=oYTfYsODWQo][Stand by me]] (1986):

    I never had any friends later on like the ones I had when I was
    twelve. Jesus, does anyone?

    Good sentence as an end of the movie. Movie telling a simple
    story. No big surprises. But still good. This is what simple
    stories telling a piece of every child life can achieve. There is
    no message but still the story is powerful. And the end makes the
    message in the end, with a sentence - at the end. Nice movie.

  - [[https://www.youtube.com/watch?v=9GzCG6lpFUw&t=57s][Vacanze Romane]] (1953):

    Was nice to see such an old movie. The story is outdated as in
    2020 no one would ever come up with such a story. These were
    rather fights from a previous generation.

    Or maybe I guess that in some countries you would still have such
    a story, what is different however is how the movie would be
    interpreted. It would be more scenographic today, the message
    would be more aggressive, more direct. 

    This is a thing that I think got lost with respect to older
    movies. They were more elegant and romantic. I do not know if it
    was due to the fact that there was a different way to live the
    public dimension in that age. They were different and this
    difference emerges when watching such an old movie.

    It reminded me of my grand-dad, he used to have some of this
    gentleman demeanor that is a leitmotiv in the movie. It got lost,
    for better or for worse, replaced by a young wilder generation.


** Possible Watch

  - Pan's labyrinth - I think that with the new consciousness that
    might be a very very interesting view. 

  - [[https://www.youtube.com/watch?v=ikvO2I_wj5s][otto e mezzo]].

  - [[https://en.wikipedia.org/wiki/The_Highwaymen_(film)][The Highwaymen]] - story of bonnie and clyde - recent movie about it
    by Netflix. Must be good. Have heard of it a couple of times by
    now. It is a story that stays in the general memory o fthe
    people. So should be interesting. 
    
  - check movies of Wes Anderson. I have no idea how he is. But one
    guy said that the /new slang/ song of the shins could fit well
    into a movie of his. I love this song deeply. So I must at least
    check a movie of his. Sounds logic - doesn't it??
    
  - The Secret Life of Walter Mitty

  - Il tempo delle mele

  - https://en.wikipedia.org/wiki/BoJack_Horseman
    

* Books

** Read

   - [[https://www.amazon.com/Ancient-Secret-Flower-Life-Vol/dp/1891824171][The ancient secret of the Flower of Life]] (Melchizedek):

     Well this one should rather stay without commentary.

     I think I will never get the book, at least not fully. 

   - [[https://www.amazon.it/Vita-Natura-Una-visione-sistemica/dp/885523076X][Vita e natura - una visione sistemica]] (Capra e Luisi):

     IN PROGRESS - write about it
   
   - [[https://www.amazon.com/Lioness-Golda-Meir-Nation-Israel/dp/0805242376][Lioness: Golda Meir and the Nation of Israel]] (Klagsbrun):

     IN PROGRESS - write about it.

   - [[https://it.wikipedia.org/wiki/Svegliare_i_leoni][Svegliare I leoni]] (Ayelet Gundar-Goshen):

     TODO - write about it.
     
   - [[https://www.amazon.com/Leaders-Richard-Nixon/dp/0446512494][Leaders]] (Richard Nixon):

     TODO - write about it.

   - [[https://books.google.ch/books/about/My_Promised_Land.html?id=8fdvAgAAQBAJ&source=kp_book_description&redir_esc=y][My Promised Land]] (Ari Shavit):

     TODO - write about it.

   - [[https://en.wikipedia.org/wiki/The_Hummingbird][Il Colibri]] (Sandro Veronesi):

     TODO - write about it.     

   - [[https://it.wikipedia.org/wiki/Povera_gente][Povera Gente]] (Fedor Dostoevskij):

     TODO - write about it.     
   
   - [[https://it.wikipedia.org/wiki/Le_notti_bianche][Le Notti Bianche]] (Fedor Dostoevskij):

     TODO - write about it.

   - [[https://en.wikipedia.org/wiki/Letter_to_His_Father][Brief an den Vater]] (Franz Kafka):

     So this is a great piece. I liked it better in comparison to the
     Trial.

     You note how sharp the mind of Franz is here. When you read a
     book of him it is always about a thrid party. There might be
     something in it but there is always a certain degree of
     detachment in it.

     When people write something that is that personal it is
     different. You immediately notice and get all of the struggles
     and uncertainties of the person when reading the letters.

     You immediately feel how difficult it must be to rise up next to
     such invasive personalities. On the other hand you see how much
     of the sorrow is caused in wanting to satisfy such
     personalities. You need to kill the figure so to say in order to
     fully be free and make your road in your life. You have to get
     rid from the chains so to say.

     Anyways that is pretty much it. I must also refer to the part
     where he talks about the jewish religion. Was smiling a lot when
     listening to it, experienced much of it on my skin and I must say
     that he put it down in a wonderful way. I think that in this
     sense he is missing still the bigger picture that you just get
     when you get more into it but I must say that if you experience
     jewishness in a very mild and superficial way as many secular
     jews do, than the feeling is exactly that one. 
   
   - [[https://en.wikipedia.org/wiki/The_Trial][The Trial]] (Franz Kafka):

     Difficult book. I found it quite slow and heavy at times. I guess
     this is necessary in order to deliver the message of the book and
     give us this feeling of oppression that Josef K. is living.

     I get it but, /oh boy what a book/. Did not expect something as
     this from one of the most acclaimed books of a well known author
     as Kafka.

     Now turning to the book, it is a great piece of book in the
     end. I mean not the lightest, not the most pleasant to read but
     it surely gives you something.

     The entire book you are waiting for something to
     happen. Something that would give sense to all of the
     book. Something that will eventually make cristal clear what is
     happening.

     This does not eventually come.

     I think this is a bit the message of the book. You see Josef who
     is a bright thinker. And you see how he does not manage to get
     out of his troublesome situation, getting ultimately acquainted
     to the trial to the point where he starts thinking of guilt.

     To the point where his energies are gone. To the point where he
     ruins himself. To the point where the mechanic of an
     incomprehensible machine of the world defeats him.

     Make sure you do not end in a similar way. You are experiencing
     yourself these very mechanism that Kafka talks about. It is not a
     trial but the mechanism of the trial are very well present in our
     everyday life. So how to manage to break out from them and the
     non-sense? To break out from the inertia.
        
   - [[https://en.wikipedia.org/wiki/White_Nights_(short_story)][White Nights]] (Fyodor Dostoevsky):

     Nice, short and juicy.

     I guess that this is the reason why Dostoevsky entered the
     Olympus of the Russian literature. You are just transported into
     the narration.

     The fact that all of the book is narrated in first person helps
     you to really feel as being there, as being the person.

     I mean it is different to the books that I usually read. Usually
     I like to read books that leave you with some new insight. With
     some new concept to think about, with something new.

     This is not that kind of book.

     It is just a book telling a simple story that lets you feel the
     emotions of the character narrating his story.

     It is emotions that everyone already experienced at least one in
     his life such that it is easy to get the message.

     I must say that I liked it but yeah nothing to say more than
     it. Just a nice story to read and get transported into.     

   - [[https://www.amazon.com/Israel-Concise-History-Nation-Reborn/dp/0062368745][Israel - A Concise History of a Nation Reborn]] (Daniel Gordis):

     So very nice book. Nothing to say.

     It delivers what it promises in its title.

     Well written, easy to follow and it gives a great overview of all
     the difficulties the young state had to go through.

     Its dilemmas. Its most defining events.

     Its tragedies and internal conflicts.

     The difficult decisions that ought to be made.

     The character of the nation.

     Very recommended book in order to better understand the history
     of the country. Gives you quite some picture and it is easy to
     follow as well structured as opposed for instance to the
     biography of Ben Gurion. 
   
   - [[https://www.amazon.com/Letters-Jonathan-Netanyahu-Commander-Entebbe/dp/9652292672][Letters of Jonathan Netanyahu]] (Johnathan Netanyahu):

     What to say. Possibly the greatest book I have ever read. 

     Many books try to push our mindset in one direction or the
     other. Make us do some required bit of philosophy or enlarge our
     knowledge. 

     This is different. It elevates the spirit in all of us. It is
     simply a collection of letters that were not even meant to be
     published. 

     They tell the story of a man. A great man. That reminds us how
     important it is to have purpose in life. 

     The thing that strikes most about him is the degree of
     emotional intelligence and of lateral view. On the top of it
     impossible not to stress how he was focused on the essential
     things in life. Mundane topics were far from him. A man with
     something to tell. A man with a purpose.

     A raw model for every one of us. Thank you for having been Jonathan.

   - [[https://it.wikipedia.org/wiki/Uno,_nessuno_e_centomila][Uno, Nessuno, Centomila]] (Luigi Pirandello):

     Very beautiful book. Read it during the quarantine. The time I
     cought covid and had to stay by myself for 10 days.

     I must say this is not the best book to read during the
     qurantine. This due to its disruptive message. You might question
     too much when being confronted with such a big topic staying all
     alone in your house.

     The message is beautiful. It touches one the vanity of the
     human. It touches the mechnics of life. And how a person that
     refuses the cerimony we are all bounded to live in is declared as
     a madman.

     I especially liked the chapter on the nature. Where he escapes in
     the countryside and starts to make a critique to modern cities and
     societies. Very deep and very true. Refer to it [[https://marcohassan.github.io/bits-of-experience/posts/book-wisdom/][here]].
    
   - [[https://www.amazon.de/confine-del-futuro-dellintelligenza-artificiale-ebook/dp/B07P5TVJVB][Il Confine del Futuro]] (Francesca Rossi):

     So particular book. If you want to go in the nitty-gritty of the
     topic that is not the right book for you. It is quite high-level
     and this is the reason why it has average reviews on Amazon.

     I must say that I partly agree with the people. On the one hand,
     you can clearly see that the author did not go the extra mile in
     writing the book but simply leveraged the name, the position, and
     the buzz for the topic for selling the book. In this sense there
     is a bit too much of auto-reference that when not backed by
     interesting content might hurt some reader. That was proved by the
     Amazon reviews, nobody likes ego-centric people.

     On the other hand, you might appreciate that is so high
     level. After all the author already excuses at the beginning for
     it and tells the public that is interested in the specifics of the
     subject to search for handbooks somewhere else. I can understand
     it, that is the ultimate difference between a /textbook/ and a
     /book/. Moreover, I think that there is value even in a
     non-obsessed and 100%-effort book or writing. After all, in such a
     way it is possible to write quick and dirty content going to the
     gist of the problem without loosing too much time on petty
     details. Of course you should have the skills to do that but I
     think that the author has the authority to do that.

     In this sense I think that the author manages well to bring some
     /meta-level/ thinking when talking about AI and machine
     learning. This is typical of italian people, we are platonic by
     education.

     When thinking in these terms, I think that it is possible to say
     that it is a good book - it manages well to reach what a textbook
     cannot get - a high level, non-complicated, overview of the topic.

     In this sense, I found of particular interest in the book the
     following elements:

     - the difference between slow and fast thinking.

       I like that differentiation and I never thought about it in such
       an explicit way. [[https://www.orellfuessli.ch/shop/home/artikeldetails/ID28756725.html][There is a book]] that goes over it - probably I
       should read it nextish.

       That is a very nice concept that I immediately applied to the
       book when reading it. It is kind of interesting how all of the
       concepts expressed in the book are nothing new to anyone working
       or dealing with AI/machine learning/applied
       statistics.

       Nonetheless, we get acquainted about all of that common
       knowledge as a side effect of doing some work; i.e. we get it in
       the fast way of thinking without making it ever explicit. While
       in contrast when you read a 100-pages book expressing all of
       that common knowledge you are forced to start your slow thinking
       process about the topics. Even more when writing a post about it
       later then. This activates an entire different way of thinking
       about it and it raises new consciousness.
     
     - the macro-level differentiation between machine-learning
       (learning by example) and the procedural learning (learning by
       fix-rule).

       I think that this differentiation is of particular importance
       even if the line gets sometimes blurry when you think about
       it. After all everything is a set of instructions - a procedural
       learning - and it is not always as easy the difference. You
       might well think of machine learning algorithms as being
       deterministic, as a well specified set of rules apply to them.

       This is also where I think that the general public confusion
       occurs when talking about black-box.

       A black-box simply occurs when the algorithm is applied to some
       microlevel (say the pixel level), the human is not able to make
       sense of. When human are not able to make sense of the input and
       how it is transformed as we do not find any connection or simple
       storytelling for it, we start to talk about black-box. After all
       I never heard anyone talking about black-box for a regression
       although the mathematical ultimate concept between the
       "black-box neural networks" and regressions is not that far.

       I.e. you talk about black-box when the information extracted out
       of an object is of no practical use for a human being as we are
       not able to make sense of it at any level as we cannot read and
       interpret that piece of information.

       That is the ultimate strength of learning by example and the
       reason for the buzz around machine learning. You allow to
       extract information out of an entire new set of objects, which a
       human being is not able to make any sense of.

       This is the beauty of machine learning and why it is creating so
       much buzz. Not the single individual algorithm. Nor a complex
       mathematical formula in itself. This is an idea that a /book/
       can bring you but a /textbook/ cannot - or at least not in the
       same way as you need a stronger prolonged stimulus to think in
       these term and get out of that micro-level thinking you do in
       your routine when applying such things.

       The issue of these black-box models is then that the human has
       to go by trial and error to learn these patterns. We have to try
       to analyze some microlevel entity and see how it works. You have
       then reached the ultimate pure-black-box level so prone to
       overfitting.

       Finger-crossed: you have no idea of why a result occurred but
       you just hope and make some mathematical tricks that should
       convince you that your results are generalizable and adversarial
       resistant.

     - about the impossibility to distinguish between procedural
       learning and learning by example.

       interesting is that the meta-level that allows a human to get
       the idea of an object, is not known to the human in a procedural
       way. Also interesting is that it is not an example driven
       deducted idea.

       You are able to think in abstract terms - say a yellow hydra
       with the face of a dog - vs [[https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1nGGpfIgXevFXMyR_JFnghK9lAoUeAXeq1u6D8y-k8arlRarloNdoLz4SFyLE-79neRo&usqp=CAU][by example]].

       Or you can get the idea of quadruple out of a cat. This in
       contrast to the case of machine learning where in order to learn
       the idea of quadruple you would have to re-index and retrain all
       of your data and train again a different algorithm for the
       task.. you cannot also ask ML to make a generalization out of a
       category as it has no idea on how to do that.

       Interesting is in this sense to see and think about how we human
       are not even conscious ourselves about some structures of our
       thinking and decision making. We are black-boxes and this is the
       ultimate reason why we need psychologists to remember us such a
       thing and tell us that it is okey.

       However, funny is also the way we cannot accept a black-box
       object, pretending that each and every human decision is
       motivated by pure rational choices. Note that this tendency is
       not just in machine learning but it is pretty much installed in
       the human brain of any western person as a core and fundamental
       fix-point value. 

       Well, I see that I am starting to go too much into philosophical
       discussion. That is dangerous so I will let it and go back to my
       micro-level thinking.

   - [[https://en.wikipedia.org/wiki/The_Life_Before_Us][The Life Before Us]] (Romain Gary):

     Nice book. I read it in 10 days but I was rather busy. It is the
     book from which the movie - la vita davanti a se - originates. See
     above your impressions.

     If the movie made a good impression and was /strong/; well the
     book is at another level. I loved it. The strength of Momo is
     powered to the /nth/. It is the most beautiful thing: the fact
     that despite all of the bad things that can happen in life, when a
     heart is good, love will win. No compromises, like Momo always
     did, very conscious of his misfortune. It is probably that
     consciousness that made bearable the unbearable and forged a
     character as strong and pure as the one of Momo. 

   - [[https://www.amazon.com/State-Any-Cost-David-Ben-Gurion/dp/0374112649][A state at any Cost: The Life of David Ben-Gurion]] (Tom Segev):

     Well I must say that I agree with the reviews I have read about
     the book: not well written.

     I think that Segev could have been more thoughtful and could
     invested more time in organizing his very big research material
     and structure a bit more the book. It is way too long, the
     language and the way it is written not very engaging. I think that
     a common thread is sometimes missing.

     Despite of all of that, there is interesting things in the
     book. First of all the character of Ben-Gurion. What a beautiful
     character. Here Segev managed quite well to report the picture of
     the battled David character, albeit I think he took some liberty
     and biased a little bit the book at times in one direction or the
     other.

     In any case wonderful and charismatic person Ben-Gurion. It is
     kind of heart warming reading about the struggles of such a great
     person. You see once again that even people that managed great
     things in life faced quite some lows and difficulties often
     doubting of themselves.

     Important is to see how in the end no matter how hard he fell -
     especially in his youth - he managed to reach his goals. As it is
     framed in the book - not because he was an outlier or
     high-performer individual but rather because he had a very strong
     life purpose and was highly committed to it. Make the plan
     explicit and the rest will follow. I must admit that in
     comparison to Ben-Gurion I do not have a fix-point or north star
     that reaches in any level the one of him. I guess because at the
     end I like to take pleasure from small things. But I would like
     to fulfill myself in some dimension apart from the general family
     affection. Will still have to work on that.

     In any case going back to Ben-Gurion, one thing that I
     particularly like is that he was eating books. He had a curious
     mind and it was impressive the amount of interest he could
     multi-manage and the amount of books he read. I still remember
     when I visited his house - which is now a museum in Tel-Aviv. So
     many books. Crazy. In this sense you are improving in time. Of
     course you are not at the level but there is some Momentum, which
     I hope you will improve in time.

     Last but not least, I loved the fact that he was holding a
     diary. He was obsessed in organizing his thoughts by putting
     things in writing. I love it and I must say that here again I am
     improving through this Blog. It is a very good exercise and it
     helps as well to organize a bit better my life.

     And then yeah, what to say. It was good refresher of the history
     of Israel and what the land means to the Jewish people. What it
     cost and how many troubling moments and decisions where on its
     way. In this sense, I must say, there is better literature but it
     is fine as that was in fact not the purpose of the book.
    
   - [[https://en.wikipedia.org/wiki/If_This_Is_a_Man][If this is a Man]] (Primo Levi):

     It is a couple of years since I read this book. I read a few
     others in the meanwhile but I want to write a few notes on
     this. Even if notes are not fresh in my memory, what stroke me the
     most of this book was its content.

     I expected some very hash statement. Some deep philosophical
     questions. I expected to find all of that and more in the book. I
     was surprised. All of that kind of material is left just in the
     title of the book. One sentence: /if this is a man/. Without
     answer nor a question mark.

     That is the power of the book. It is true to itself. It is the
     true, naked message. It is the history of what such people had to
     live through in concentration camps.

     It talks about routine. It talks about how the people that
     survived managed the routine; just manage the routine with little
     escamotage. That is the daily life of all of us. Manage it at the
     microlevel conscious about a bigger picture but without giving it
     too much importance.

     And the book follows that pattern. It does not talk at the
     macro-level the complete folly of the Nazis. It talks at the
     micro-level of the horrible experience of the people.

     And it leaves the exercise of making sense of it, if at all
     possible, to you with that single title: /if this is a man/.


** Books to Read

   - [[https://www.amazon.com/Learned-Optimism-Martin-P-Seligman/dp/1442341130][Learned Optimism]]

   - [[https://www.orellfuessli.ch/shop/home/artikeldetails/ID28756725.html][Thinking, Fast and Slow]]

   - Books of William Saroyan (recommended by Jonathan Netanyahu in
     his letters).
  

* Theater

  - [[https://www.broadway.com/shows/the-phantom-of-the-opera/][The phantom of the Opera]] (2021)

    Was nice being in broadway. Nice show. Well done. I must admit
    that it was difficult at times for me to follow entirely the
    script. I mean I could well follow the broad plot and always
    understand most of it. But not 100%. This due to the musical
    component of it that was not always easy to follow for a
    non-native English speaker like me. 

    I remember that when I first watched the movie of it during my
    high-school time I was much more struck by the character of
    phantom and especially the end. It was much more of a struggle. I
    cannot understand how much this was missing in the show due to the
    point mentioned above and how much it was inherent in the design
    of the show.

    In any case nice to be in Broadway and to watch a Broadway classic
    was ultimately the goal such that I was very satisfied with it.

  - [[https://www.teatromanzoni.it/manzoni/it/spettacoli/scusa-sono-in-riunione-ti-posso-richiamare-1][Scusa sono in riunione... ti posso richiamare?]] (2021)

    The first part it is extremely nice. Very funny and at the same
    time very true.

    It talks about the life of all of us. The natural leitmotiv of our
    societies. How each and everyone of us follows in that bit and how
    in a funny way we become funny caricatures of societies schemas.

    The second part is a little bit random.. still funny at times. But
    it looses that part of reality that was in the first bit. In the
    first part the story is of the public. I.e. the actors in play
    represent each and everyone of us. I.e. in their story there is as
    well /our/ story. In the second part that relation bit
    disappears. It becomes /their/ story.

    The message at the end is nice. It tells you *not* to enter in
    that rabbit hole as Luciano did. To renounce - in order to keep
    your integrity. 


* Interesting Artists

(As of 15/12/2020)

- Michael Kachan (A)

- Vaca Mia Brintrup (A)

- Debbie Miller (B)

Others

- Doug Quillinan

- Antonio Sotomayor 

- Gregory Radionov (just water colours)

- Charles Levier

- Victor Coleman Anderson 

- Alexander Raymond Katz

- Sviatoslav Baziuk 

- Ruth Owens - How? 2017


* Travels/ Out of home door Activities

** Switzerland

*** Zurich

**** Museums

   - [[https://www.zuerich.com/en/visit/culture/museum-rietberg#internal][intercultural museum]] (B)

   - [[https://www.zuerich.com/en/visit/culture/zaz-bellerive#internal][space and urbanism museum]] (C)

   - [[https://www.kulturama.ch/][anatomy/biology museum]] (B)

**** Park 

   - [[http://www.weinrebenpark.ch/][bruno weber park]]. (A)

   - [[https://www.atlasobscura.com/places/mfo-park][oerlikon.. some weird plants go to take a look once you pass by]] (C)

   - [[https://www.atlasobscura.com/places/villa-patumbah][colonial villa in ZH]] ([[https://www.heimatschutzzentrum.ch/index.php?id=2239][link2]]) (B)

**** Sommergarten

   Probiere noch 
 
    - [[https://zumfrischenmax.ch/][zumfrischenmax]] - done after tutanchamon; ok nothing special -
 
    - das neue gerold's [[https://www.fraugerold.ch/de/guggach][garten in Bucheggplatz]].

**** Bar

   - [[https://www.zuerich.com/en/visit/restaurants/samigo-amusement#internal][chic bar with other friends]] (C)
 
   - [[https://www.atlasobscura.com/places/oepfelchammer][funny bar with friends]] (B) - done - 

   - nice bar [[https://www.zuerich.com/en/visit/nightlife/regenbogen-bar][im Niederdorf]] (B) - nice in summer funny live music on tuesdays -

*** Hikes

  - [[https://www.grimselwelt.ch/en/excursion-tips/trift][trift bridge hike]] (AA)


** Italy 

  - [[https://en.wikipedia.org/wiki/Villa_di_Pratolino][villa demidoff]] (B)

  - [[https://it.wikipedia.org/wiki/Lago_di_Carezza][lago dell'arcobaleno]] (A) - non balneabile solo per passeggiate tirolo.

  - [[https://www.camminatorianonimi.com/2020/07/11/alla-quercia-delle-streghe/][la quercia delle streghe]] (A) - passeggiata con sorpresa in toscana


*** Milano

**** Stazione Centrale 

   - [[https://www.atlasobscura.com/places/royal-pavilion-at-stazione-centrale][Stanze d'attesa reali]] (A)


** London

*** Open Air

  - [[https://www.atlasobscura.com/places/banksy-s-designated-graffiti-area][graffiti]] (A)

  - [[https://www.atlasobscura.com/places/greenwich-foot-tunnel][canary wharf activity]] - nothing big. if you should be there by
    chance with some time left. (C)

  - [[https://www.london-walking-tours.co.uk/the-seven-noses-of-soho.htm][funny activity.... can you find the noses]] ([[https://www.google.com/maps/d/u/0/viewer?msa=0&dg=feature&mid=1g06yOJHD6OORLaAM2IMKHeMtUDc&ll=51.512889089653505%2C-0.12930900000003298&z=15][use this map]]) (B)

*** Indoor

  - [[https://fotostrasse.com/london-canal-museum-kings-cross-ice-well/][London canal museum and ice well]] (C)

  - [[https://secretldn.com/growing-underground-farm/][Growing underground]] (C)

  - [[https://www.janewildgoose.co.uk/about_the_library.html][weird library / place]] (A)

  - [[https://www.soane.org/?gclid=Cj0KCQjw1qL6BRCmARIsADV9JtbFChEEtDysN4sajeI-cv-o_GN93lFT9AbRSD3a_cSKAi-rgseWs4MaAj81EALw_wcB][Sir John Soane's Museum]] - messy antiquities place (A)


** Israel

  - [[https://www.ilanagoormuseum.org/en/][ilana goor museum. yaffo - looks nice]] (B)

  - [[https://jonathanmtsai.wordpress.com/2010/11/19/hermits-house-herzliya/][heremit's house in herzliya]] (AA)

  - [[http://en.goramla.com/category/pool-of-arches][the pool of arches in Ramla]] (A)




