#+BEGIN_COMMENT
.. title: A personal Repo - Movies, Art and Things to Do
.. slug: things-to-do-in-zh
.. date: 2020-08-28 16:41:37 UTC+02:00
.. tags: travel
.. category: personal
.. link: 
.. description: 
.. type: text

#+END_COMMENT

#+BEGIN_EXPORT html
<br>
<br>
#+END_EXPORT

This is a personal post where I keep some personal activities/places I
am aim to visit at some point.

I am further structuring this post. I am adding a movie
section. Moreover, I will start to briefly write some memories and
personal thoughts for the completed activities.

{{{TEASER_END}}}

* Movies

** Watched

  - [[https://www.youtube.com/watch?v=aKtvrvZC8OY][Il mondo che vorrei]] (2021):

    This was an interview with [[https://it.wikipedia.org/wiki/Papa_Francesco][Pope Francesco I]]. It was a good
    watch. In a rough world that is hard to navigate is always good to
    listen to such people reminding the true christian values on which
    the western society build on. These are not values augmenting the
    individualism but rather stressing the importance of the community
    that we must protect and remind us.

    The message was centered about fostering a culture of /us/ in
    contrast to an /egocentric/ view, in promoting a culture where we
    have [[https://www.youtube.com/watch?v=fhVsgxlYsEA][empathy]] and care for the others. In refusing a culture of
    waste, where if we do not like something, if something creates a
    problem or if something/someone does not fit, well we throw it
    away, be it a human being or a thing, instead of trying to solve
    the problem with it.

    Good fellow as always Pope Francesco, may he stay healthy.

  - [[https://en.wikipedia.org/wiki/Rose_Island_(film)][L'isola delle rose]] (2020):

    Wow! What an incredible story. I love it. It is a daydreamer story
    like me. Makes well the point of the italian genius. It lives in a
    different dimension. We idealist animals...

  - [[https://www.youtube.com/watch?v=En1jkf34xjc][La vita davanti a sé]] (2020):

    Very good movie. Strong like Momo. It is a very mixed movie. It
    encompasses many feelings and it is much food for thoughts. There
    is not a bottom line to it and it is not a light watch where there
    not need to be a bottom line. 

    It is difficult to write a snippet summarizing it. I liked it. One
    of the things I liked was the power of Momo. I guess that a key in
    the movie is how the energy of such people when channeled in the
    right will make them shine. The weird element of the lion in the
    movie goes in this direction. There is a lion / fire in some
    people and it can turn to very good or bad outcomes depending on
    who is there in the path of such people - be it Madame Rosa or the
    other guy.

    Interesting is also to notice that not the spoiled child, but
    rather the suffered one will have the fire. Help such people and
    let them shine.

  - [[https://www.youtube.com/watch?v=RUOH8_HYDtA][Cyrano mon Amour]] (2019):

    Good movie. Confirms my personal opinion about French movies:
    these are generally the best movies when you look for a light but
    tasty watch. The key of the French majesty of movies production is
    to bring deep stories in a light way to the viewer while keeping
    the importance of the message in the movie.

    Here and there this specific movie falls into some mainstream,
    which might hurt some more sophisticated viewer but generally a
    good watch that underlines how sometimes the best in life does not
    come by following rigid structures. 

    Have to watch the Cyrano at some Opernhaus at some point now..

    Also interesting is that now you can understand better [[https://www.youtube.com/watch?v=T_wnAnIM3cw][the song of
    Guccini]]. I understood the power of the text but some links where
    missing and now it clicked.

  - [[https://www.youtube.com/watch?v=CGzKnyhYDQI][Loving Vincent]] (2017):

    Nice movie. It is kind of a thriller. Recommended watch, just
    because of the particular painting style it is recommended.

    It is also a nice watch in the sense that you get easily
    transported. 

    Interesting way to talk about Van Gogh in this particular indirect
    way. I think at the end they well manage to give a picture of him.

  - [[https://www.youtube.com/watch?v=MYzFieit8dI][Mayerowitz Stories]] (2017):

    Well, there are many movies. Some are different. This is one of
    these. Some movies you know from the very beginning what is gonna
    come. This not. It evolves and evolves and evolves and then it
    finishes. 


  - [[https://www.youtube.com/watch?v=NRADS6wT3nc][Bienvenue à Marly-Gomont]] (2016):

    It talks about a nice story. It is a story about
    integration. Again a typical french comedy. Sometimes fun,
    sometimes serious and in general a very pleasant and constructive
    watch.

    The message of the story is the usual. But it is always good to
    watch one more movie making the point. Myself as emigrant know
    the point. Every time when moving out and entering a new
    community you will face opposition. Don't think it is personal it
    is just how the world spins. And if you are bright enough then you
    will have the courage and the duty to oppose such mechanism and
    promote different outcomes like the one in the movie. 

  - [[https://www.youtube.com/watch?v=dKYaEPdcV1g&t=3s][War Dogs]] (2016):

    Dark comedy crime movie. Interesting cause it is based on a true
    story. I generally do not like such kind of movies as they make
    the watcher sympathize on bad behaviour by making it /hollywood
    cool/. At the end you enjoy watching it but it is a double edge
    sword for the reasons above. If you read it by taking a step back,
    there is a learning also in such movie in how even an apparently
    good soul as David gets easily tricked by the moment and takes up
    bad habits. We all had that kind of Efraim friend.

    So bottom line always remember that you are walking on thin ice
    and it is easy to get out of track. Keep faith and stay solid on
    good values. 

  - [[https://www.youtube.com/watch?v=oYTfYsODWQo][Stand by me]] (1986):

    I never had any friends later on like the ones I had when I was
    twelve. Jesus, does anyone?

    Good sentence as an end of the movie. Movie telling a simple
    story. No big surprises. But still good. This is what simple
    stories telling a piece of every child life can achieve. There is
    no message but still the story is powerful. And the end makes the
    message in the end, with a sentence - at the end. Nice movie.

  - [[https://www.youtube.com/watch?v=9GzCG6lpFUw&t=57s][Vacanze Romane]] (1953):

    Was nice to see such an old movie. The story is outdated as in
    2020 no one would ever come up with such a story. These were
    rather fights from a previous generation.

    Or maybe I guess that in some countries you would still have such
    a story, what is different however is how the movie would be
    interpreted. It would be more scenographic today, the message
    would be more aggressive, more direct. 

    This is a thing that I think got lost with respect to older
    movies. They were more elegant and romantic. I do not know if it
    was due to the fact that there was a different way to live the
    public dimension in that age. They were different and this
    difference emerges when watching such an old movie.

    It reminded me of my grand-dad, he used to have some of this
    gentleman demeanor that is a leitmotiv in the movie. It got lost,
    for better or for worse, replaced by a young wilder generation.



** Possible Watch

  - [[https://www.ifilmdavedere.it/top-100-film-da-vedere-assolutamente][good website with suggestions more or less in line with my taste]].

  - [[https://it.wikipedia.org/wiki/Gifted_-_Il_dono_del_talento][gifted]]

  - [[https://www.youtube.com/watch?v=-D-lrKAAwVI][qualcosa di meraviglioso]]


* Interesting Artists

(As of 15/12/2020)

- Michael Kachan (A)

- Vaca Mia Brintrup (A)

- Debbie Miller (B)


Others

- Doug Quillinan

- Antonio Sotomayor 

- Gregory Radionov (just water colours)

- Charles Levier

- Victor Coleman Anderson 

- Alexander Raymond Katz

- Sviatoslav Baziuk 

- Ruth Owens - How? 2017



* Travels/ Out of home door Activities

** Switzerland

*** Zurich

**** Museums

   - [[https://www.zuerich.com/en/visit/culture/museum-rietberg#internal][intercultural museum]] (B)

   - [[https://www.zuerich.com/en/visit/culture/zaz-bellerive#internal][space and urbanism museum]] (C)

   - [[https://www.kulturama.ch/][anatomy/biology museum]] (B)

**** Park 

   - [[http://www.weinrebenpark.ch/][bruno weber park]]. (A)

   - [[https://www.atlasobscura.com/places/mfo-park][oerlikon.. some weird plants go to take a look once you pass by]] (C)

   - [[https://www.atlasobscura.com/places/villa-patumbah][colonial villa in ZH]] ([[https://www.heimatschutzzentrum.ch/index.php?id=2239][link2]]) (B)

**** Sommergarten

   Probiere noch 
 
    - [[https://zumfrischenmax.ch/][zumfrischenmax]] - done after tutanchamon; ok nothing special -
 
    - das neue gerold's [[https://www.fraugerold.ch/de/guggach][garten in Bucheggplatz]].

**** Bar

   - [[https://www.zuerich.com/en/visit/restaurants/samigo-amusement#internal][chic bar with other friends]] (C)
 
   - [[https://www.atlasobscura.com/places/oepfelchammer][funny bar with friends]] (B) - done - 

   - nice bar [[https://www.zuerich.com/en/visit/nightlife/regenbogen-bar][im Niederdorf]] (B) - nice in summer funny live music on tuesdays -

*** Hikes

  - [[https://www.grimselwelt.ch/en/excursion-tips/trift][trift bridge hike]] (AA)


** Italy 

  - [[https://en.wikipedia.org/wiki/Villa_di_Pratolino][villa demidoff]] (B)

  - [[https://it.wikipedia.org/wiki/Lago_di_Carezza][lago dell'arcobaleno]] (A) - non balneabile solo per passeggiate tirolo.

  - [[https://www.camminatorianonimi.com/2020/07/11/alla-quercia-delle-streghe/][la quercia delle streghe]] (A) - passeggiata con sorpresa in toscana


*** Milano

**** Stazione Centrale 

   - [[https://www.atlasobscura.com/places/royal-pavilion-at-stazione-centrale][Stanze d'attesa reali]] (A)


** London

*** Open Air

  - [[https://www.atlasobscura.com/places/banksy-s-designated-graffiti-area][graffiti]] (A)

  - [[https://www.atlasobscura.com/places/greenwich-foot-tunnel][canary wharf activity]] - nothing big. if you should be there by
    chance with some time left. (C)

  - [[https://www.london-walking-tours.co.uk/the-seven-noses-of-soho.htm][funny activity.... can you find the noses]] ([[https://www.google.com/maps/d/u/0/viewer?msa=0&dg=feature&mid=1g06yOJHD6OORLaAM2IMKHeMtUDc&ll=51.512889089653505%2C-0.12930900000003298&z=15][use this map]]) (B)

*** Indoor

  - [[https://fotostrasse.com/london-canal-museum-kings-cross-ice-well/][London canal museum and ice well]] (C)

  - [[https://secretldn.com/growing-underground-farm/][Growing underground]] (C)

  - [[https://www.janewildgoose.co.uk/about_the_library.html][weird library / place]] (A)

  - [[https://www.soane.org/?gclid=Cj0KCQjw1qL6BRCmARIsADV9JtbFChEEtDysN4sajeI-cv-o_GN93lFT9AbRSD3a_cSKAi-rgseWs4MaAj81EALw_wcB][Sir John Soane's Museum]] - messy antiquities place (A)


** Israel

  - [[https://www.ilanagoormuseum.org/en/][ilana goor museum. yaffo - looks nice]] (B)

  - [[https://jonathanmtsai.wordpress.com/2010/11/19/hermits-house-herzliya/][heremit's house in herzliya]] (AA)

  - [[http://en.goramla.com/category/pool-of-arches][the pool of arches in Ramla]] (A)




