#+BEGIN_COMMENT
.. title: A personal Repo - Movies, Art and Things to Do
.. slug: things-to-do-in-zh
.. date: 2016-08-28 16:41:37 UTC+02:00
.. tags: perRep
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT

#+BEGIN_EXPORT html
<br>
<br>
#+END_EXPORT

This is a personal post where I keep some personal activities/places I
am aim to visit at some point.

I am further structuring this post. I am adding a movie
section. Moreover, I will start to briefly write some memories and
personal thoughts for the completed activities.

{{{TEASER_END}}}

* Movies

** Watched

  - [[https://en.wikipedia.org/wiki/Shtisel][Shtisel]] (2021):

    I was home over Easter. I watched with the family the third
    season. Very nice series. Much better than [[https://de.wikipedia.org/wiki/Unorthodox_(Miniserie)][unorthodox]]. There
    everything was a little bit too much exasperated.

    This is nice. I would say it's kosher. It well summarizes the
    Jewish mentality with all its pro and cons.
    
  - [[https://www.youtube.com/watch?v=aKtvrvZC8OY][Il mondo che vorrei]] (2021):

    This was an interview with [[https://it.wikipedia.org/wiki/Papa_Francesco][Pope Francesco I]]. It was a good
    watch. In a rough world that is hard to navigate is always good to
    listen to such people reminding the true christian values on which
    the western society build on. These are not values augmenting the
    individualism but rather stressing the importance of the community
    that we must protect and remind us.

    The message was centered about fostering a culture of /us/ in
    contrast to an /egocentric/ view, in promoting a culture where we
    have [[https://www.youtube.com/watch?v=fhVsgxlYsEA][empathy]] and care for the others. In refusing a culture of
    waste, where if we do not like something, if something creates a
    problem or if something/someone does not fit, well we throw it
    away, be it a human being or a thing, instead of trying to solve
    the problem with it.

    Good fellow as always Pope Francesco, may he stay healthy.

  - [[https://en.wikipedia.org/wiki/Rose_Island_(film)][L'isola delle rose]] (2020):

    Wow! What an incredible story. I love it. It is a daydreamer story
    like me. Makes well the point of the italian genius. It lives in a
    different dimension. We idealist animals...

  - [[https://www.youtube.com/watch?v=En1jkf34xjc][La vita davanti a sé]] (2020):

    Very good movie. Strong like Momo. It is a very mixed movie. It
    encompasses many feelings and it is much food for thoughts. There
    is not a bottom line to it and it is not a light watch where there
    not need to be a bottom line. 

    It is difficult to write a snippet summarizing it. I liked it. One
    of the things I liked was the power of Momo. I guess that a key in
    the movie is how the energy of such people when channeled in the
    right will make them shine. The weird element of the lion in the
    movie goes in this direction. There is a lion / fire in some
    people and it can turn to very good or bad outcomes depending on
    who is there in the path of such people - be it Madame Rosa or the
    other guy.

    Interesting is also to notice that not the spoiled child, but
    rather the suffered one will have the fire. Help such people and
    let them shine.

  - [[https://www.youtube.com/watch?v=SMuQfYdgWxw][Sorelle Macaluso]] (2020):

    Wow wow wow!!! There are film directors that do movies. They stay in
    the daily life of each of us and touch daily topics. Mundane - I
    think this is the word.

    This transcends everything. What a beautiful mind the one of the
    movie director. To get the gravity of the life and what each one
    of us needs to face in our life and bring it on the big screen in
    such a way is simply... wow. And the lyrics that goes along the
    movie. It's liberty music. Despite the hard life we are able to
    face it and go on with such a power. Crazy movie. Possibly one of
    the best, if not the best I ever saw.

    And I usually do not touch or go along the female vs male story. I
    do not like dichotomies. But damn it you feel the touch of a
    female soul in the movie. And if this is what we missed, give way
    to the woman on the big screen.

  - [[https://www.youtube.com/watch?v=RUOH8_HYDtA][Cyrano mon Amour]] (2019):

    Good movie. Confirms my personal opinion about French movies:
    these are generally the best movies when you look for a light but
    tasty watch. The key of the French majesty of movies production is
    to bring deep stories in a light way to the viewer while keeping
    the importance of the message in the movie.

    Here and there this specific movie falls into some mainstream,
    which might hurt some more sophisticated viewer but generally a
    good watch that underlines how sometimes the best in life does not
    come by following rigid structures. 

    Have to watch the Cyrano at some Opernhaus at some point now..

    Also interesting is that now you can understand better [[https://www.youtube.com/watch?v=T_wnAnIM3cw][the song of
    Guccini]]. I understood the power of the text but some links where
    missing and now it clicked.


  - [[https://it.wikipedia.org/wiki/Old_Man_%26_the_Gun][The Old Man & The Gun]] (2018):

    Nice movie and watch. It teaches the importance of elegance and
    style in life. That demeanor that everyone wants to have but just
    a few achieve. It is funny as basically in the plot the demeanor
    of the person completely excuses his acts. You and everyone in the
    movie sympathize with him.

    Just a pity for the end. He did not reach maturity and it lives
    you with the doubt that guy was just a psycho. But maybe it was
    just in his style and that is the beauty of it. Throwing
    everything away to save this little but important thing of
    yours.

  - [[https://www.youtube.com/watch?v=CGzKnyhYDQI][Loving Vincent]] (2017):

    Nice movie. It is kind of a thriller. Recommended watch, just
    because of the particular painting style it is recommended.

    It is also a nice watch in the sense that you get easily
    transported. 

    Interesting way to talk about Van Gogh in this particular indirect
    way. I think at the end they well manage to give a picture of him.


  - [[https://en.wikipedia.org/wiki/Il_a_d%C3%A9j%C3%A0_tes_yeux][Il a déjà tes yeux]] (2017):

    Very nice movie. Extremely funny. I love Manu. But also serious in
    the topic. Without ever being too heavy. Very recommended.

  - [[https://www.youtube.com/watch?v=MYzFieit8dI][Mayerowitz Stories]] (2017):

    Well, there are many movies. Some are different. This is one of
    these. Some movies you know from the very beginning what it is
    gonna come. This not. It evolves and evolves and evolves and then
    it finishes.

    It's a nice family story.


  - [[https://www.youtube.com/watch?v=NRADS6wT3nc][Bienvenue à Marly-Gomont]] (2016):

    It talks about a nice story. It is a story about
    integration. Again a typical french comedy. Sometimes fun,
    sometimes serious and in general a very pleasant and constructive
    watch.

    The message of the story is the usual. But it is always good to
    watch one more movie making the point. Myself as emigrant know
    the point. Every time when moving out and entering a new
    community you will face opposition. Don't think it is personal it
    is just how the world spins. And if you are bright enough then you
    will have the courage and the duty to oppose such mechanism and
    promote different outcomes like the one in the movie. 

  - [[https://www.youtube.com/watch?v=dKYaEPdcV1g&t=3s][War Dogs]] (2016):

    Dark comedy crime movie. Interesting cause it is based on a true
    story. I generally do not like such kind of movies as they make
    the watcher sympathize on bad behaviour by making it /hollywood
    cool/. At the end you enjoy watching it but it is a double edge
    sword for the reasons above. If you read it by taking a step back,
    there is a learning also in such movie in how even an apparently
    good soul as David gets easily tricked by the moment and takes up
    bad habits. We all had that kind of Efraim friend.

    So bottom line always remember that you are walking on thin ice
    and it is easy to get out of track. Keep faith and stay solid on
    good values. 

  - [[https://www.youtube.com/watch?v=oYTfYsODWQo][Stand by me]] (1986):

    I never had any friends later on like the ones I had when I was
    twelve. Jesus, does anyone?

    Good sentence as an end of the movie. Movie telling a simple
    story. No big surprises. But still good. This is what simple
    stories telling a piece of every child life can achieve. There is
    no message but still the story is powerful. And the end makes the
    message in the end, with a sentence - at the end. Nice movie.

  - [[https://www.youtube.com/watch?v=9GzCG6lpFUw&t=57s][Vacanze Romane]] (1953):

    Was nice to see such an old movie. The story is outdated as in
    2020 no one would ever come up with such a story. These were
    rather fights from a previous generation.

    Or maybe I guess that in some countries you would still have such
    a story, what is different however is how the movie would be
    interpreted. It would be more scenographic today, the message
    would be more aggressive, more direct. 

    This is a thing that I think got lost with respect to older
    movies. They were more elegant and romantic. I do not know if it
    was due to the fact that there was a different way to live the
    public dimension in that age. They were different and this
    difference emerges when watching such an old movie.

    It reminded me of my grand-dad, he used to have some of this
    gentleman demeanor that is a leitmotiv in the movie. It got lost,
    for better or for worse, replaced by a young wilder generation.


** Possible Watch

  - check movies of Wes Anderson. I have no idea how he is. But one
    guy said that the /new slang/ song of the shins could fit well
    into a movie of his. I love this song deeply. So I must at least
    check a movie of his. Sounds logic - doesn't it??
    
  - [[https://www.ifilmdavedere.it/top-100-film-da-vedere-assolutamente][good website with suggestions more or less in line with my taste]].


* Books

  - [[https://www.amazon.de/confine-del-futuro-dellintelligenza-artificiale-ebook/dp/B07P5TVJVB][Il Confine del Futuro]] (Francesca Rossi):

    So particular book. If you want to go in the nitty-gritty of the
    topic that is not the right book for you. It is quite high-level
    and this is the reason why it has average reviews on Amazon.

    I must say that I partly agree with the people. On the one hand,
    you can clearly see that the author did not go the extra mile in
    writing the book but simply leveraged the name, the position, and
    the buzz for the topic for selling the book. In this sense there
    is a bit too much of auto-reference that when not backed by
    interesting content might hurt some reader. As proved by the
    Amazon reviews, nobody likes ego-centric people.

    On the other hand, you might even appreciate that is so high
    level. After all the author already excuses at the beginning for
    it and tells the public that is interested in the specifics of the
    subject to search for handbooks somewhere else. I can understand
    it, that is the ultimate difference between a /textbook/ and a
    /book/. Moreover, I think that there is value even in a
    non-obsessed and 100%-effort book. After all, in such a way it is
    possible to write quick and dirty content going to the gist of the
    problem without loosing too much time petty details. Of course you
    should have the skills to do that but I think that the author has
    the authority to do that.

    In this sense I think that the author manages well to bring some
    /meta-level/ thinking when talking about AI and machine
    learning. This is typical of italian people, we are platonic by
    education.

    When thinking in these terms, I think that it is possible to say
    that it is a good book - it manages well to reach what a textbook
    cannot get - a high level, non-complicated, overview of the topic.

    In this sense, I found of particular interest in the book the
    following elements:

    - the difference between slow and fast thinking. I like that
      differentiation and I never thought about it in such an explicit
      way. [[https://www.orellfuessli.ch/shop/home/artikeldetails/ID28756725.html][There is a book]] that goes over it - probably I should read
      it nextish. That is a very nice concept that I immediately
      applied to the book when reading. It is kind of interesting how
      all of the concepts expressed in the book are nothing new to
      anyone working or dealing with AI/machine learning/applied
      statistics. Nonetheless, we get acquainted about all of that
      common knowledge, as a side effect of doing some work; i.e. we
      get it in the fast way of thinking without making it ever
      explicit. While in contrast when you read a 100-pages book
      expressing all of that common knowledge you are forced to start
      your slow thinking about the topics. Even more when writing a
      post about it later then. This activates an entire different way
      of thinking about it and it raises new consciousness.
     
    - the macro-level differentiation between machine-learning
      (learning by example) and the procedural learning (learning by
      fix-rule).

      I think that this differentiation is of particular importance
      even if the line gets sometimes blurry when you think about
      it. After all everything is a set of instructions - a procedural
      learning - and it is not always as easy the difference. You
      might well think of machine learning algorithms as being
      deterministic, as a well specified set of rules apply to them.

      This is also where I think that the general public confusion
      occurs when talking about black-box.

      This simply occurs, when once in a while the algorithm is
      applied to some microlevel (say the pixel level), the human is
      not able to make sense of. As human are not able to make sense
      of the input and how it is transformed as we do not find any
      connection or simple storytelling for it, we start to talk about
      black-box. After all I never heard anyone talking about
      black-box for a regression although the mathematical ultimate
      concept between the "black-box neural networks" and regressions
      is not that far.

      I.e. you talk about black-box when the information extracted out
      of an object is of no practical use for a human being as we are
      not able to make sense of it at any level as we cannot read and
      interpret that piece of information.

      That is the ultimate strength of learning by example and the
      reason for the buzz around machine learning. You allow to
      extract information out of an entire set of entities, which a
      human being is not able to make any sense of.

      The issue of these black-box models is then that the human has
      to go by trial and error to learn this patterns. Trying to
      analyze some microlevel entity and see how it works. You have
      then reached the ultimate pure-black-box level so prone to
      overfitting and finger-crossed as you have no idea of why a
      result occurred. 

      This is the beauty of machine learning and why it is creating so
      much buzz. Not the single individual algorithm. Nor a complex
      mathematical formula in itself. This is an idea that a /book/
      can bring you but a /textbook/ cannot - or at least not in the
      same way as you need a stronger prolonged stimulus to think in
      these term and get out of that micro-level thinking you do in
      your routine when working with such things.

    - interesting is that the meta-level that allows a human to get
      the idea of an object, is not known to the human in a procedural
      way. Also interesting is that it is not an example driven
      deducted idea.

      You are able to think in abstract terms - say a yellow hydra
      with the face of a dog - vs [[https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1nGGpfIgXevFXMyR_JFnghK9lAoUeAXeq1u6D8y-k8arlRarloNdoLz4SFyLE-79neRo&usqp=CAU][by example]].

      Or you can get the idea of quadruple out of a cat. This in
      contrast to the case of machine learning where in order to learn
      the idea of quadruple you would have to re-index and retrain all
      of your data and train again a different algorithm for the
      task.. you cannot also ask ML to make a generalization out of a
      category as it has no idea on how to do that.

      Interesting is in this sense to see and think about how we human
      are not even conscious ourselves about some structures of our
      thinking and decision making. We are black-boxes and these is
      the ultimate reason why we need psychologist to remember us that
      little thing and tell us that it is okey. However, funny is also
      the way we cannot accept a black-box outcome, pretending that
      each and every human decision is motivated by pure rational
      choices.

      Well, I see that I am starting to go too much into philosophical
      discussion. That is dangerous so I will let it and go back to my
      micro-level thinking.

    

  

  - [[https://en.wikipedia.org/wiki/The_Life_Before_Us][The Life Before Us]] (Romain Gary):

    Nice book. I read it in 10 days but I was rather busy. It is the
    book from which the movie - la vita davanti a se - originates. See
    above your impressions.

    If the movie made a good impression and was /strong/; well the
    book is at another level. I loved it. The strength of Momo is
    powered to the /nth/. It is the most beautiful thing: the fact
    that despite all of the bad things that can happen in life, when a
    heart is good, love will win. No compromises, like Momo always
    did, very conscious of his misfortune. It is probably that
    consciousness that made bearable the unbearable and forged a
    character as strong and pure as the one of Momo. 

  - [[https://www.amazon.com/State-Any-Cost-David-Ben-Gurion/dp/0374112649][A state at any Cost: The Life of David Ben-Gurion]] (Tom Segev):

    Well I must say that I agree with the reviews I have read about
    the book: not well written.

    I think that Segev could have been more thoughtful and could
    invested more time in organizing his very big research material
    and structure a bit more the book. It is way too long, the
    language and the way it is written not very engaging. I think that
    a common thread is sometimes missing.

    Despite of all of that, there is interesting things in the
    book. First of all the character of Ben-Gurion. What a beautiful
    character. Here Segev managed quite well to report the picture of
    the battled David character, albeit I think he took some liberty
    and biased a little bit the book at times in one direction or the
    other.

    In any case wonderful and charismatic person Ben-Gurion. It is
    kind of heart warming reading about the struggles of such a great
    person. You see once again that even people that managed great
    things in life faced quite some lows and difficulties often
    doubting of themselves.

    Important is to see how in the end no matter how hard he fell -
    especially in his youth - he managed to reach his goals. As it is
    framed in the book - not be cause he was an outliers or
    high-performer individual but rather because he had a very strong
    life purpose and was highly committed to it. Make the plan
    explicit and the rest will follow. I must admit that in comparison
    to Ben-Gurion I do not have a fix-point or north star that reaches
    in any level the one of him. I guess because at the end I like to
    take pleasure from small things. But I would like to fulfill
    myself in some dimension apart from the general family
    affection. Will still have to work on that.

    In any case going back to Ben-Gurion, one thing that I
    particularly like is that he was eating books. He had a curious
    mind and it was impressive the amount of interest he could
    multi-manage and the amount of books he read. I still remember
    when I visited his house - which is now a museum in Tel-Aviv. So
    many books. Crazy. In this sense you are improving in time. Of
    course you are not at the level but there is some Momentum, which
    I hope you will improve in time.

    Last but not least, I loved the fact that he was holding a
    diary. He was obsessed in organizing his thoughts by putting
    things in writing. I love it and I must say that here again I am
    improving through this Blog. It is a very good exercise and it
    helps as well to organize a bit better my life.

    And then yeah, what to say. It was good refresher of the history
    of Israel and what the land means to the Jewish people. What it
    cost and how many troubling moments and decisions where on its
    way. In this sense, I must say, there is better literature but it
    is fine as that was in fact not the purpose of the book.
    
  - [[https://en.wikipedia.org/wiki/If_This_Is_a_Man][If this is a Man]] (Primo Levi):

    It is a couple of years since I read this book. I read a few
    others in the meanwhile but I want to write a few notes on
    this. Even if notes are not fresh in my memory, what stroke me the
    most of this book was its content.

    I expected some very hash statement. Some deep philosophical
    questions. I expected to find all of that and more in the book. I
    was surprised. All of that kind of material is left just in the
    title of the book. One sentence: /if this is a man/. Without
    answer nor a question mark.

    That is the power of the book. It is true to itself. It is the
    true, naked message. It is the history of what such people had to
    live through in concentration camps.

    It talks about routine. It talks about how the people that
    survived managed the routine; just manage the routine with little
    escamotage. That is the daily life of all of us. Manage it at the
    microlevel conscious about a bigger picture but without giving it
    too much importance.

    And the book follows that pattern. It does not talk at the
    macro-level the complete folly of the Nazis. It talks at the
    micro-level of the horrible experience of the people.

    And it leaves the exercise of making sense of it, if at all
    possible, to you with that single title: /if this is a man/.


* Interesting Artists

(As of 15/12/2020)

- Michael Kachan (A)

- Vaca Mia Brintrup (A)

- Debbie Miller (B)

Others

- Doug Quillinan

- Antonio Sotomayor 

- Gregory Radionov (just water colours)

- Charles Levier

- Victor Coleman Anderson 

- Alexander Raymond Katz

- Sviatoslav Baziuk 

- Ruth Owens - How? 2017



* Travels/ Out of home door Activities

** Switzerland

*** Zurich

**** Museums

   - [[https://www.zuerich.com/en/visit/culture/museum-rietberg#internal][intercultural museum]] (B)

   - [[https://www.zuerich.com/en/visit/culture/zaz-bellerive#internal][space and urbanism museum]] (C)

   - [[https://www.kulturama.ch/][anatomy/biology museum]] (B)

**** Park 

   - [[http://www.weinrebenpark.ch/][bruno weber park]]. (A)

   - [[https://www.atlasobscura.com/places/mfo-park][oerlikon.. some weird plants go to take a look once you pass by]] (C)

   - [[https://www.atlasobscura.com/places/villa-patumbah][colonial villa in ZH]] ([[https://www.heimatschutzzentrum.ch/index.php?id=2239][link2]]) (B)

**** Sommergarten

   Probiere noch 
 
    - [[https://zumfrischenmax.ch/][zumfrischenmax]] - done after tutanchamon; ok nothing special -
 
    - das neue gerold's [[https://www.fraugerold.ch/de/guggach][garten in Bucheggplatz]].

**** Bar

   - [[https://www.zuerich.com/en/visit/restaurants/samigo-amusement#internal][chic bar with other friends]] (C)
 
   - [[https://www.atlasobscura.com/places/oepfelchammer][funny bar with friends]] (B) - done - 

   - nice bar [[https://www.zuerich.com/en/visit/nightlife/regenbogen-bar][im Niederdorf]] (B) - nice in summer funny live music on tuesdays -

*** Hikes

  - [[https://www.grimselwelt.ch/en/excursion-tips/trift][trift bridge hike]] (AA)


** Italy 

  - [[https://en.wikipedia.org/wiki/Villa_di_Pratolino][villa demidoff]] (B)

  - [[https://it.wikipedia.org/wiki/Lago_di_Carezza][lago dell'arcobaleno]] (A) - non balneabile solo per passeggiate tirolo.

  - [[https://www.camminatorianonimi.com/2020/07/11/alla-quercia-delle-streghe/][la quercia delle streghe]] (A) - passeggiata con sorpresa in toscana


*** Milano

**** Stazione Centrale 

   - [[https://www.atlasobscura.com/places/royal-pavilion-at-stazione-centrale][Stanze d'attesa reali]] (A)


** London

*** Open Air

  - [[https://www.atlasobscura.com/places/banksy-s-designated-graffiti-area][graffiti]] (A)

  - [[https://www.atlasobscura.com/places/greenwich-foot-tunnel][canary wharf activity]] - nothing big. if you should be there by
    chance with some time left. (C)

  - [[https://www.london-walking-tours.co.uk/the-seven-noses-of-soho.htm][funny activity.... can you find the noses]] ([[https://www.google.com/maps/d/u/0/viewer?msa=0&dg=feature&mid=1g06yOJHD6OORLaAM2IMKHeMtUDc&ll=51.512889089653505%2C-0.12930900000003298&z=15][use this map]]) (B)

*** Indoor

  - [[https://fotostrasse.com/london-canal-museum-kings-cross-ice-well/][London canal museum and ice well]] (C)

  - [[https://secretldn.com/growing-underground-farm/][Growing underground]] (C)

  - [[https://www.janewildgoose.co.uk/about_the_library.html][weird library / place]] (A)

  - [[https://www.soane.org/?gclid=Cj0KCQjw1qL6BRCmARIsADV9JtbFChEEtDysN4sajeI-cv-o_GN93lFT9AbRSD3a_cSKAi-rgseWs4MaAj81EALw_wcB][Sir John Soane's Museum]] - messy antiquities place (A)


** Israel

  - [[https://www.ilanagoormuseum.org/en/][ilana goor museum. yaffo - looks nice]] (B)

  - [[https://jonathanmtsai.wordpress.com/2010/11/19/hermits-house-herzliya/][heremit's house in herzliya]] (AA)

  - [[http://en.goramla.com/category/pool-of-arches][the pool of arches in Ramla]] (A)




