#+BEGIN_COMMENT
.. title: Finance General Concepts
.. slug: finance-general-concepts
.. date: 2018-06-28 10:57:26 UTC+02:00
.. tags: finance
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT


This is another of the posts that is likely to increase in time.

More concepts will flow in here and it will become more complete in
time.

This is what I actually miss from my first Masters - I was not working
in a digital way at the times. This is a pity cause lots of this
knowledge is gone in a non-consummable way. There were quite a few
handy things that I could use as mental frameworks at my current job....

Would be cool at some time to time to take some time and integrate
there the concepts in the different relevant posts for the particular
category.

In any case have a look [[https://thismatter.com/][at this]]... just read an article there and it
was well written and it seems to be an interesting project where to
have a look at once in a while... layout aside of course... I mean
checked a bit again and I have to say that at times it is quite
coarse.. but that is what you mean once in a while and then you can
check at the things in more detail...

{{{TEASER_END}}}

** Credit ratings - Some thoughts on Issuer Rating and Seniority

   So basically you would have to check a little bit more into the
   detail on how these issuer ratings are defined...

   I started this exploration as I wanted to understand if the
   seniority of a bond is included in the rating being a quite
   important factor..

   I ended up [[https://thismatter.com/money/bonds/bond-ratings-and-credit-risk.htm][here]] - see link with last paragraph above.

   So you see that the first important distinction that you have to
   understand... understand always if a person is talking about an
   /issuer rating/ or a particular security rating.

   These can be quite different. 

   Note now that these ratings are like the University rankings. In
   themselves they do not tell you anything. You have to check how
   they are composed if you really want to understand the absolute
   number / score.

   It is the concept of aggregation of information where then
   ultimately a ton of information is lost. Again can use them as a
   very rough indicator but obviously if you know how they are
   composed and you have a little bit of a clue about what you are
   interested in you could come up with something more tailored.

   
*** make that research in this sense.... would be cool to check at the methodologies of these...

    of course this would be a different job... but I guess that it is
    good to have a little bit of understanding in this dimension given
    the importance of these securities for the business.

    ------

    ok... so I guess this is the reason why you were not able to find
    anything... it is all proprietary.... so if you want to make some
    analysis based on financial ratios, seniority etc.. well than you
    are left on your own with your tools.

    Interesting how an entire industry spins around such aggregated
    ratings without even knowing in detail how they are computed...

    I mean I am quite sure that there are some spillovers of these
    proprietary mechanism from ppl working in these agencies and
    transferring to other financial institutions.. but well you are
    out of it until you don't meet or talk with the right ppl.

