#+BEGIN_COMMENT
.. title: On Investment Management of a big Insurance
.. slug: on-investment-management-of-a-big-insurance
.. date: 2021-10-25 16:11:36 UTC+02:00
.. tags: investment management
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT

Wow.. things are starting to get interesting. The issue is that in the
new job, you do not simply have to tackle down a system that looks
challenging to tackle down, with lots of tech involved and, possibly,
a fair amount of math.

You have as well to deal with a business machine that is equally
complex. The organization and the structure of the entire machine
is interesting.

In order to well perform at the job a good understanding of both is
necessary. So I am taking a bit of time now to structure the
understing in this dimension and to understand how the investment
management machine works in bigger insurance companies.

Note that I am keeping these notes very general and I am just writing
here publicly available information. This notes mainly derive on the
public document outling the structure of [[https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjbpPqt5eXzAhVE_KQKHdhmA_YQFnoECAMQAQ&url=https%3A%2F%2Fwww.zurich.com%2F-%2Fmedia%2Fproject%2Fzurich%2Fdotcom%2Fsustainability%2Fdocs%2Finvestment-management-value-creation-2014.pdf%3Fla%3Den&usg=AOvVaw2m5DSA7AYGq9OfYan1QB7h][zurich insurance investment
management]], which is very well in line with what I can observe in my
position.

In order to expand your understanding in this sense, you can [[https://www.oecd.org/investment/evolution-insurer-strategies-long-term-investing.pdf][read the
following document by oecd]].

Note that such a general macro-view is necessary as through it you
will make better sense on the applicaiton of your market-risk system
and can better understand the stakeholder you will have to deal with. 


{{{TEASER_END}}}
  
* What is special in the Investment Management Business of Insurances

  So the most basic principle is that the investment management
  process is dictated by the insurance business. This makes very well
  sense. As banks have to think in terms of possible credit withdrawal
  and bank runs when investing, insurances have to think in terms of
  claims and monitor the standard and non-standard (think of NatCat)
  cash-flow implied by such claims.

  Now depending on the type of insurance business you have a different
  duration for your claims that will dictate a different investment
  strategy.

  This is were the first big component of Investment Management at an
  Insurance Company kicks in:

  - Asset Liability Management:

    Here the idea is to match the asset side of the balance sheet to
    the liabilities side. So the idea is to have an investement
    management strategy that matches the cash flows derived from the
    two.

    In simple words Asset Liability Management *generates the minimum-risk
    portfolio* that ensures the market values of assets and liabilities
    move in tandem when markets move

  - Strategic Asset Allocation:

    Here the idea is to select the correct asset class mix in order to
    generate the best possible risk-reward positioning, this obviously
    considering all of the necessary constraints implied by the
    regulatory capital and ALM considerations.

    In order to make this allocation and select the best long-term
    risk-reward positioning a set of risk factors are
    considered. Assets are then mapped to such risk-factors. Usual
    risk-factors are: interest rate risk, credit risk, term structure
    risk, equity and commodities risk. Based on the mapping to risk
    factors you would then select your positioning of choice.

  So basically the interesting part of investment management in an
  insurance company in comparison to fund management houses is that in
  the latter you do not have to make big considerations on the
  liability side. I.e. there you get the manadate from the client to
  invest a given amount and you are typically benchmarked against a
  market/index of reference.

  When setting the investment strategy for an insurance company the
  strategy is different. You first consider the liabilities and based
  on that you will derive the investment strategy, where the benchmark
  will usually not be a market/index of reference but rather the the
  yield on a government bond portfolio of the highest available credit
  quality - i.e. the risk-free rate.

  On the top of it you can make some minor reasoning based on /beta/
  and /alpha/, but I undestand this is a rather minimal
  component. Especially the alpha is minimal - it is in the market
  strategy team defining the tactical asset allocation and hence not
  part of my team covering the bigger picture.
      
* From a Regulation Perspective

  Regulators generally require insurance companies to hold sufficient
  assets to back liabilities in every insurance business. The reserves
  must suffice to pay-out expected claims and benefits, *even in the
  unplanned case that the insurer stops writing new business*.

  So the main take-away is that regulators require that insurers
  *do not rely on new premiums to pay for claims* and benefits
  underwritten in the past.

  This is the reason why you will have all of these scenario in your
  system and have to perform different simulations for it. 
  
* On a global vs local vision

  So basically you dictate then the global investement strategy of the
  group based on this kind of reasoning and about computing the
  optimum at group level. You want to have largest possible cake at
  group level so to say. 

  You have then the different country specific regional investment
  management that implement strategy. There is interaction about group
  level considerations and local level considerations in order to
  define who can take what risks and manage what part of the
  investments.

  I.e. local investment commitees are responsible in assuring all of
  the local constrains such as regulation, legal, accounting and tax
  are fulfilled. 

  

  
