#+BEGIN_COMMENT
.. title: Music that Touched Me
.. slug: music-that-touched-me
.. date: 2019-07-03 14:41:27 UTC+02:00
.. tags: perRep
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT


I will start a compilation of music that touched me and that evoked
something in me.

It is again intended as a repository that will develop in time. Maybe
one day when I will be old and will have many empty days to fill up -
I will come back to this repo and listen to this music and I will see
what it will evoke in me.

Let's start without a fix date and let's see how often I add pieces
and I will adjust then the speed. I listen to a lot of music so I do
not want this repo to grow very fast in an undirected way. Scarcity
makes the experience better, so you will likely have to put some
constrains once you understand how much you publish.

{{{TEASER_END}}}

** 29/10/2021

   - [[https://www.youtube.com/watch?v=RknUh1LapJs][Cycling Trivialities]] - very melodic and nostalgic. beautiful.

** 06/08/2021

   - [[https://www.youtube.com/watch?v=vkLOg252KRE&list=RDGMEMBhrNM15bN0pM50WECpic-A&index=5][The War on Drugs - Under The Pressure]] - Very nice piece of
     guitar.

** 07/08/2021

   - [[https://www.youtube.com/watch?v=ZMbgETDKuAs][Bloom Album]] - Very chilled album. I like it a lot to calm
     down. It's a period where I am also rediscovering albums and
     their value. There is in fact something good in them instead
     that jumping around from unrelated song to another unrelated
     song.

** 06/08/2021

   - [[https://www.youtube.com/watch?v=yt7O8gDy0DA&list=RDf4it9vK6G7o&index=11][The Trapeze Swinger]] - very nice and chilled music. Nice when you
     want to reconnect with yourself. 

** 20/07/2021

   - [[https://www.youtube.com/watch?v=gr7bsCd4yrA][il pifferaio magico]] - nice rap. It keeps me calm in these dense
     days. 

** 16/07/2021

   - [[https://www.youtube.com/watch?v=WKE9XRCtnSU][ניצחת איתי הכל]] - I do not even understand the words. But that is
     so peaceful. I really like this song. [[https://lyricstranslate.com/de/%D7%A0%D7%99%D7%A6%D7%97%D7%AA-%D7%90%D7%99%D7%AA%D7%99-%D7%94%D7%9B%D7%9C-youve-won-all-me.html][Here]] the translation - a
     beautiful love song as you could get from the intensity of the
     song.

** 03/07/2021

   - [[https://www.youtube.com/watch?v=Nh1NlXky9D0][Old Friend - Agus & Julia Stone]] : very peaceful song. You can find
     the calm and peace when listening to this song. Everything slowly
     fades away and you feel like a little dot that tries hard to get
     to something big while in reality our experience as human beings
     on earth is much more represented by calm quite moment where we
     can transcend daily routine and get to this deeper level. 
