
#+BEGIN_COMMENT
.. title: prova latex
.. slug: prova-latex
.. date: 2019-09-22 10:43:50 UTC+02:00
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text
.. status: private
#+END_COMMENT


#+BEGIN_HTML
<br>
<br>
#+END_HTML

This is a private post where I keep a cheat sheet of working with
latex in org. 

Notice that nikola does not export proper latex chunks such as the one
below

#+BEGIN_LaTeX
\alpha * \pi *  \sum_{i}^{N}
#+END_LaTeX

It /does/ however export built in latex statements such as the
formula below:

\alpha * \pi *  \sum_{i}^{N}

Test it in the following weeks.

Like that you can write posts about your learning in statistics in
possibly a fast way.

*** Expression parsed?

Notice that org does not parse latex expression as the one above in
=verbatim=. The text in such mode is literally represented.

The same holds for example chunks as the one below.

#+begin_example
\alpha * \pi *  \sum_{i}^{N}
#+end_example

nThe *best solution* is therefore to write the mathematical formula on
a separate line centering that.

The below does not work cause html does not parse latex functions but
it centers the text so it potentially works with all of the other
things you are interested to center.

#+BEGIN_HTML
<p style="text-align:center;">
\alpha * \pi *  \sum_{i}^{N}
</p>
#+END_HTML

--- still need to understand how to center. In the meanwhile just
    write on a separate line.

#+begin_center
begin center also does not work. If you ever consider to change the
behaviour and fix the centering it is advisable to manually change the
behaviour of this function. Probably mapped to some html of the wrong
format. There should be a conf.el source code somewhere defining how
the org expressions are converted and you can theoretically manually
adjust such file.
#+end_center

*** TODO Latex plug-in

There is a latex plug-in in nikola.

It is not trivial to use the latter though. I tried to implement it by
downloading the two plug-ins:

- https://plugins.getnikola.com/v7/latex/

- https://plugins.getnikola.com/v7/latex_formula_renderer/

Notice that the second package has many other dependencies I am not
sure to have captured.

I installed miktex here and now something is moving also in the auctex
on emacs. Try ~C-c C-c~ there. 

The issue continues to be the rendering in nikola. Cause it would
actually be very nice to have latex expressions for making complete
resumes and post all the statistics encounters there.

Go over it again whenever you have time.

Theoretically mathjax should already be built-in in both org and
nikola. For some reason the format is not rendering though.
