#+BEGIN_COMMENT
.. title: Work Strategy - On Multi-Teaming and Multi-Threading
.. slug: work-strategy-on-multi-teaming-and-multi-threading
.. date: 2021-10-26 14:14:51 UTC+02:00
.. tags: Time Management and Mind-Set
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT

Ok, so this is a post in line with the previous ones. You are starting
to understand your responsibilities and how the team operates.

It is going to be a fun ride. Let's see how it will go in the long
run.

Here are some notes that will be your northern star in your new
adventure. They should always be fresh in your mind as they will help
you to keep the right amount of serenity at work and to work in the
best possible way given your limited amount of time and mental
resources.

{{{TEASER_END}}}

* Situation

  So you are not really multi-teaming, you are sitting in a very well
  specified team within Group Investment Management. Still you are for
  sure multi-threading, as the amount of people in the team is very
  limited you have to deal with multiple highly engaging topics, where
  deep expertise is required.

  So far I distinctly recognized the following topics:

  - an IT landscape that is far from trivial. It grew large in the
    last decades. There is quite some legacy technology involved,
    there is no clear cut of responsibilities as in larger IT
    companies. You have no architects, developers, testers and
    operations distinction. You have to take over multiple
    responsibilities and wear multiple hats. This multi-task alone
    would be sufficient for a single person to deal with.

  - a business environment that is very rooted and geographically
    distributed and consequently not trivial to understand. After all
    it is a machine encompassing hundreds of professional and you can
    imagine that an overview of it is not a trivial task. Still if you
    want to become *relevant* on the long-run you can not limit
    yourself to your technical island. You have to properly understand
    how the business operates, what the pain points are and who uses
    your system across the group investment management value chain.

  - a market risk system that eventually has a non-trivial
    mathematical and development component. This is not the same
    pain-point as the first item of this list. I intend the first item
    more in the general landscape sense. There the focus lies in the
    interconnections among the different components of the system and
    how to properly mange them. In contrast I intend this item more at
    the low level implementation and understanding of the simulation
    engine necessary to operate the risk system. There you need to
    master the hadoop stack and the concepts of distributed computing
    as well as to keep your mindset mathematically affine.

  So how do you mange the situation?
  
* Managing the Situation

  I think that [[https://hbr.org/2017/11/how-to-stay-focused-if-youre-assigned-to-multiple-projects-at-once][this post]] of harvard business review reasons well with
  what I am feeling right now.

  #+begin_quote
For many people, getting pulled across several different projects is
stressful and less productive than theory would suggest.

Switching attention between tasks takes time and saps your focus and
energy.


Multiple switches change not only your level of accountability but
also your ability to juggle resources when a crunch time
hits. Different components encompass their own unique cultures, including
relationships, routines, symbols, jokes, expectations, and tolerance
for ambiguity, which requires energy to handle.

And unless you carefully plan and negotiate your contribution on each
component, you may end up doing repetitive work instead of pushing
your own development.
  #+end_quote

  The authors suggest then the following working approach to tackle
  the situation:

  #+begin_quote
- *get the big picture:* Focusing narrowly on a given day’s work puts
  you in a reactive, firefighting mode. Schedule a regular status
  check on all your projects to note milestones.

  This relates to my second item of the above list. So do not forget
  about it and schedule periodical time to think about it.

- *Sequence strategically:* Pick one task and focus on it intensely,
  rather than juggling. Start with the task that requires the greatest
  concentration and give it your undivided attention. Decide on a
  distinct set of must-achieve outcomes.

  So basically this is the strategy I decided from the onset of the
  work by rotating across the three different points above. Keep it
  running but also keep the intervals in your calendar and do not
  stick simply to a single task, in order not to loose on the first
  point - the big picture. 

- *protect yourself:* in terms - let your stakeholders know you are
  aware of them and their needs but buy you the needed margin in order
  to work properly.

- *document and communicate progress:* Seeing momentum helps your team
  leaders feel empowered and in control. Be up front when problems
  arise. The earlier you say, “I’ve got a conflict and might have
  trouble delivering 100%,” the more leaders will trust you. One
  seasoned team member in our research said many of his responses to
  team requests are simply two words: “On it.” Even this super-brief
  response tells colleagues that he received their request, so they
  know he’ll follow up when he can provide more details.

  I think this is a very
  important item and this blog and the non-public created
  documentation you can share with the team will help you to reach
  this goal.

- *Know thyself:* Under time pressure, the temptation is for each
  person to contribute where they already have deep knowledge, rather
  than investing in members’ learning and growth. You need to own your
  development goals and your progress toward them. Figure out who else
  on the team you want exposure to. Make your development goals
  explicit, to both your team leader and those experts.

  *very very important*

- *Force thyself:* After identifying your development goals, block out
  time for actual learning. Research shows that a critical determinant
  of learning is time spent reflecting on and integrating new
  information. Obviously, you can’t go overboard and become a
  bottleneck just to carve out contemplation time, but make sure team
  members see reflection as “real work.”

  Also very important. There you have to be especially
  good. Especially in a dynamic team as this you have to show the
  value of such reflection periods and documentation items. I believe
  in it but you have to show it. The documentation and communication
  of progress of the above item might help in this sense.
  #+end_quote

