#+BEGIN_COMMENT
.. title: On Enterprise Applications Architecture
.. slug: on-enterprise-applications-architecture
.. date: 2021-11-01 14:21:20 UTC+01:00
.. tags: IT Architecture
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT

So having moved out of the field of PoC/MvP I must say that I am
starting to understand the difficulties around setting up virtuous
enterprise applications.

You have complex processes and lots of possible solutions. You have to
be agile and nimble. This is the only way to manage the complexity and
still be able to steer your application in a smooth way, in order to
keep up with the technological progress.

This is the ultimate challenge of the job. The complex business logic
calls for complex solutions. I.e. usually when you are under pressure
you make direct mappings of the required business logic into a
system. Without abstracting and without imposing meta-structure the
system gets heavy and looses that nimble and agile component.

In order to deal with the issues above, I started to read [[http://ce.sharif.edu/courses/97-98/2/ce418-1/resources/root/Books/Patterns%20of%20Enterprise%20Application%20Architecture%20-%20Martin%20Fowler.pdf][Patterns of
Enterprise Application Architecture]], here some notes -mainly copy and
past - such that I will hopefully learn in a fast way to make the
right decisions when working on enterprise applications.

{{{TEASER_END}}}

* Simple Rule - Not so easy to follow due to human nature

  You can’t come up with a single architecture that will be right for
  all three.

  Choosing an architecture means that you have to /understand the
  particular problems/ of your system and choose an appropriate design
  based on that understanding. That’s why in this book I don’t give a
  single solution for your enterprise needs. Instead, many of the
  patterns are about choices and alternatives. Even when you choose a
  particular pattern, you’ll have to modify it to meet your
  demands. You can’t build enterprise software without thinking, and
  all any book can do is give you more information to base your
  decisions on.

  If this applies to patterns, it also applies to tools. Although it
  obviously makes sense to pick as small a set of tools as you can to
  develop applications, you also have to recognize that different tools
  are best for different purposes.  Beware of using a tool that is
  really suited for a different kind of application—it may hinder more
  than help.

  
* Patterns

  So the key to get to this meta-level of thinking and to keep the
  system nimble is via patterns.

  This is the art of dividing up many pieces of advice into relatively
  independent chunks so that you can refer to them and discuss them
  more or less separately.

  Patterns aren’t original ideas; they’re very much /observations of
  what happens in the field/. As a result, we pattern authors don’t say
  we “invented” a pattern but rather that we “discovered” one.

  I like this perspective that the book author suggests:

  #+begin_quote
You don’t need to read all of this book, or all of any patterns book,
to find it useful. You just need to read enough to have a sense of
what the patterns are, what problems they solve, and how they solve
them.

You don’t need to know all the details but just enough so that if you
run into one of the problems you can find the pattern in the book.
Only then do you need to really understand the pattern in depth.
  #+end_quote

  this is in fact the way I work. Read a bit in a structured way in
  order to get an idea of what you are talking about.

  Then when you have a clear idea, just go by your own and to google
  specific queries. But it is important for me to start with more
  thorough readings as you have to know what you have to search.

  Otherwise, you will just end up meandering the world wide web.

  
* TODO continue with chapter 1.

  put it in the org-agenda. have lots to read. multiple open
  fronts. time-management again as the solution. monitor how much time
  you spend on each task.
